/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import com.sun.glass.events.KeyEvent;
import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class Check extends javax.swing.JInternalFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    
    public Check() {
        initComponents();
        
        
         con = dbconnect.connect();
        
        tableload();
     //   tableload2();
        tableload3();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchbox = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        expaybox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkoutbox = new com.toedter.calendar.JDateChooser();
        extraDaysbox = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reservedtobox = new com.toedter.calendar.JDateChooser();
        checkinbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bookidbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        idbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/body.jpg"))); // NOI18N

        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setText("Check-in    and    Check-out");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(820, 20, 342, 31);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setFillsViewportHeight(true);
        jTable3.setRowHeight(30);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 560, 910, 260);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 230, 900, 270);

        searchbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        getContentPane().add(searchbox);
        searchbox.setBounds(237, 143, 270, 40);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "CustID", "Fname", "Lname", "City" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(29, 143, 190, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("View Customer  Details");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(29, 86, 227, 22);

        searchbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton);
        searchbutton.setBounds(520, 140, 140, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/add.png"))); // NOI18N
        jButton3.setText("Insert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1410, 780, 140, 50);

        expaybox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        expaybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expayboxActionPerformed(evt);
            }
        });
        getContentPane().add(expaybox);
        expaybox.setBounds(1140, 700, 408, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Extra  Payments");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(980, 710, 154, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("No of  Extra  Days");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(980, 640, 154, 40);
        getContentPane().add(checkoutbox);
        checkoutbox.setBounds(1140, 550, 410, 40);

        extraDaysbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        extraDaysbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                extraDaysboxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                extraDaysboxMouseReleased(evt);
            }
        });
        extraDaysbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraDaysboxActionPerformed(evt);
            }
        });
        extraDaysbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                extraDaysboxKeyPressed(evt);
            }
        });
        getContentPane().add(extraDaysbox);
        extraDaysbox.setBounds(1140, 640, 250, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/bar-chart-reload.png"))); // NOI18N
        jButton4.setText("Generate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1410, 630, 140, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Reserved To");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(980, 460, 101, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Check  out  Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(980, 550, 146, 40);
        getContentPane().add(reservedtobox);
        reservedtobox.setBounds(1140, 460, 410, 40);

        checkinbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkinbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinboxActionPerformed(evt);
            }
        });
        getContentPane().add(checkinbox);
        checkinbox.setBounds(1140, 380, 410, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Check  in  Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(980, 380, 143, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Booking  ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(980, 310, 101, 40);

        bookidbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(bookidbox);
        bookidbox.setBounds(1140, 310, 410, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/bar-chart-reload.png"))); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1410, 230, 140, 50);

        idbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idboxActionPerformed(evt);
            }
        });
        getContentPane().add(idbox);
        idbox.setBounds(1140, 240, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customer  ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(980, 240, 118, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/print.png"))); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(980, 780, 110, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/body.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -250, 1780, 1420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public void clear(){
        idbox.setText("");
        bookidbox.setText("");
        checkinbox.setText("");
        reservedtobox.setDate(null);
        checkoutbox.setDate(null);
        extraDaysbox.setText("");
        expaybox.setText("");
        
    }
    
    public void tableload() {
       try{ 
           String sql;
           sql = "SELECT * FROM cust_reg";
          
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
       } catch (Exception e) {
         // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
 }
 
 public void tableload3() {
       try{ 
           String sql;
           sql = "SELECT * FROM checks";
          
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
             
       } catch (Exception e) {
         // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
 }
      
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");

        Date d1 = null;
        Date d2 = null;

        try {
            d1 = sf.parse(sf.format(reservedtobox.getDate()));
            d2 = sf.parse(sf.format(checkoutbox.getDate()));

        } catch(Exception e){
            e.printStackTrace();
        }

        long diff = d2.getTime() - d1.getTime();

        long sec = diff/ 1000 % 60 ;
        long min = diff/ (60*1000) % 60;
        long hours = diff/ (60*60*1000);
        long days = hours/24;

        extraDaysbox.setText(Long.toString(days));

        String extraPay = extraDaysbox.getText();
        float e = Float.parseFloat(extraPay);

        float extra = e*1000;
        String total=Float.toString(extra);
        expaybox.setText(total);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //insert
        String ID = idbox.getText();
        String Roomno="Reserved";
        String BID = bookidbox.getText();
        String sql2="SELECT RoomNo FROM booking WHERE BookID='"+BID+"'";

        try {
            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();

            if(rs.next()){

                Roomno=(rs.getString("RoomNo"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        //date
        //DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        //Date date;
        String checkin = checkinbox.getText();
        //String reservrdto = reservedtobox.getText();
        //String checkin = df.format(date);

        DateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
        Date date2;
        date2 = checkoutbox.getDate();
        String checkout = df2.format(date2);

        String ex = extraDaysbox.getText();
        String expay = expaybox.getText();

        try {
            String sql = "INSERT INTO checks (custID,bookID,checkIn,checkOut,extra,exPayment) values (?,?,?,?,?,?)";

            pst = con.prepareStatement(sql);

            pst.setString(1,ID);
            pst.setString(2,BID);
            pst.setString(3,checkin);
            pst.setString(4,checkout);
            pst.setString(5,ex );
            pst.setString(6,expay);

            pst.execute();

            tableload3();

            JOptionPane.showMessageDialog(this,"Successfully Inserted");

            clear();

        } catch (SQLException | HeadlessException e) {
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this,e);
        }
        try{
            String sql1="UPDATE room set status=? where RoomNo=?";
            pst = con.prepareStatement(sql1);

            // pst.setStrpst.setString(1,"Reserved");
            pst.setString(1,"Free");
            pst.setString(2,Roomno);

            pst.execute();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void expayboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expayboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expayboxActionPerformed

    private void extraDaysboxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraDaysboxMousePressed

    }//GEN-LAST:event_extraDaysboxMousePressed

    private void extraDaysboxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraDaysboxMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_extraDaysboxMouseReleased

    private void extraDaysboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraDaysboxActionPerformed

    }//GEN-LAST:event_extraDaysboxActionPerformed

    private void extraDaysboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extraDaysboxKeyPressed
        int key = evt.getKeyCode();
        if((key>= evt.VK_0 && key <= evt.VK_9) || (key>= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key== KeyEvent.VK_BACKSPACE){

            extraDaysbox.setEditable(true);
            extraDaysbox.setBackground(Color.white);
        }
        else{
            extraDaysbox.setEditable(false);
            extraDaysbox.setBackground(Color.red);
        }
    }//GEN-LAST:event_extraDaysboxKeyPressed

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void checkinboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkinboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String cid = idbox.getText();

        String sql = "SELECT BookID From booking where custID = "+ cid +" ";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){

                bookidbox.setText(rs.getString("BookID"));

            }else{
                bookidbox.setText("0");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        }

        String sql2 = "SELECT ReservedFrom From booking where custID = "+ cid +" ";
        try {
            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();

            //            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            //            Date bdate;
            //            bdate = rs.getDate("ReservedFrom");
            //            String Dob = df.format(bdate);
            //

            if(rs.next()){

                //                DateFormat f = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
                //                Date d = f.parse(Dob);
                //                jDateChooser2.setDate(d);

                checkinbox.setText(rs.getString("ReservedFrom"));

            }else{

                //                DateFormat f = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
                //                Date d = f.parse(Dob);
                //                checkinbox.setDate(d);
                //
                checkinbox.setText("0");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        }

        String sql3 = "SELECT ReservedTo From booking where custID = "+ cid +" ";
        try {
            pst = con.prepareStatement(sql3);
            rs = pst.executeQuery();

            //
            //            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            //            Date bdate;
            //            bdate = rs.getDate("ReservedTo");
            //            String Dob = df.format(bdate);

            if(rs.next()){
                String ddate=rs.getString("ReservedTo").toString();
                Date edate= new SimpleDateFormat("yyyy-MM-dd").parse((String) ddate);
                reservedtobox.setDate(edate);
                //                 DateFormat f = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
                //                Date d = f.parse(Dob);
                //                jDateChooser2.setDate(d);
                //

                //reservedtobox.setText(rs.getString("ReservedTo"));

            }else{
                //                Date date =  ;
                //                reservedtobox.setDate();
                reservedtobox.setDate(null);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

        int r = jTable3.getSelectedRow();

        String ID = jTable3.getValueAt(r, 0).toString();
        String BID = jTable3.getValueAt(r, 1).toString();
        String checkkin = jTable3.getValueAt(r, 2).toString();
        String reservedTo = jTable3.getValueAt(r, 3).toString();
        String checkout = jTable3.getValueAt(r, 4).toString();
        String ex = jTable3.getValueAt(r, 5).toString();
        String expay = jTable3.getValueAt(r,6).toString();

        idbox.setText(ID);
        bookidbox.setText(BID);

      
        try {
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
            Date d2 = f.parse(checkout);
            checkoutbox.setDate(d2);
        } catch (Exception e) {
        }

        extraDaysbox.setText(ex);
        expaybox.setText(expay);

    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r = jTable1.getSelectedRow();

        String ID = jTable1.getValueAt(r, 0).toString();

        idbox.setText(ID);

    }//GEN-LAST:event_jTable1MouseClicked

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed

        // TODO add your handling code here:
        int typeno = jComboBox3.getSelectedIndex();
        String type = "";
        String key = searchbox.getText();

        switch(typeno){
            case 0:type="";
            break;

            case 1:type="custID";
            break;

            case 2:type="fname";
            break;
            case 3:type="lname";
            break;
            case 4:type="city";
            break;
        }

        String sql ="select * from cust_reg where "+type+" like '"+key+"%'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            rs.last();

            JOptionPane.showMessageDialog(null,rs.getRow()+ " Results Found!");

        } catch (SQLException | HeadlessException e) {
        }

    }//GEN-LAST:event_searchbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String fname = searchbox.getText();
            try {
                String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\check.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(rep);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookidbox;
    private javax.swing.JTextField checkinbox;
    private com.toedter.calendar.JDateChooser checkoutbox;
    private javax.swing.JTextField expaybox;
    private javax.swing.JTextField extraDaysbox;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private com.toedter.calendar.JDateChooser reservedtobox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbutton;
    // End of variables declaration//GEN-END:variables
}
