/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import com.sun.glass.events.KeyEvent;
import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class Cust_reg extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Cust_reg() {
        initComponents();

        con = dbconnect.connect();

        tableload();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fnamebox = new javax.swing.JTextField();
        lnamebox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nicbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dobbox = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        malebox = new javax.swing.JRadioButton();
        femalebox = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        add1box = new javax.swing.JTextField();
        add2box = new javax.swing.JTextField();
        citybox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telbox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 920));
        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 950, 510);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/update.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 730, 130, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/delete.png"))); // NOI18N
        jButton4.setText(" Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 730, 140, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/clear.png"))); // NOI18N
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(850, 730, 120, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(520, 120, 120, 50);

        searchbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(searchbox);
        searchbox.setBounds(230, 120, 270, 40);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "CustID", "Fname", "Lname", "City" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(20, 120, 190, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText(" General    Information");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1130, 40, 290, 48);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText(" ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1000, 110, 101, 40);

        idbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(idbox);
        idbox.setBounds(1130, 110, 250, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/bar-chart-reload.png"))); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1400, 100, 140, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText(" Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1000, 180, 101, 40);

        fnamebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fnamebox.setForeground(new java.awt.Color(204, 204, 204));
        fnamebox.setText(" First Name");
        fnamebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameboxFocusGained(evt);
            }
        });
        fnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameboxActionPerformed(evt);
            }
        });
        fnamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameboxKeyReleased(evt);
            }
        });
        getContentPane().add(fnamebox);
        fnamebox.setBounds(1130, 180, 190, 40);

        lnamebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lnamebox.setForeground(new java.awt.Color(204, 204, 204));
        lnamebox.setText(" Last Name");
        lnamebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnameboxFocusGained(evt);
            }
        });
        lnamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnameboxKeyReleased(evt);
            }
        });
        getContentPane().add(lnamebox);
        lnamebox.setBounds(1360, 180, 180, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("NIC");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1010, 250, 120, 40);

        nicbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nicbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicboxKeyPressed(evt);
            }
        });
        getContentPane().add(nicbox);
        nicbox.setBounds(1130, 250, 410, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText(" Date of Birth");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1000, 320, 120, 40);
        getContentPane().add(dobbox);
        dobbox.setBounds(1130, 320, 410, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText(" Gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1000, 380, 120, 40);

        buttonGroup1.add(malebox);
        malebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        malebox.setText("  Male");
        malebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleboxActionPerformed(evt);
            }
        });
        getContentPane().add(malebox);
        malebox.setBounds(1130, 380, 190, 40);

        buttonGroup1.add(femalebox);
        femalebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        femalebox.setText("  Female");
        femalebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleboxActionPerformed(evt);
            }
        });
        getContentPane().add(femalebox);
        femalebox.setBounds(1350, 380, 190, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText(" Contact   Information");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1140, 450, 290, 48);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1000, 520, 120, 40);

        add1box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add1box.setForeground(new java.awt.Color(204, 204, 204));
        add1box.setText(" Line 1  Address");
        add1box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                add1boxFocusGained(evt);
            }
        });
        add1box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                add1boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add1boxKeyReleased(evt);
            }
        });
        getContentPane().add(add1box);
        add1box.setBounds(1120, 520, 190, 40);

        add2box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add2box.setForeground(new java.awt.Color(204, 204, 204));
        add2box.setText(" Line 2  Address");
        add2box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                add2boxFocusGained(evt);
            }
        });
        add2box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                add2boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add2boxKeyReleased(evt);
            }
        });
        getContentPane().add(add2box);
        add2box.setBounds(1350, 520, 180, 40);

        citybox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        citybox.setForeground(new java.awt.Color(204, 204, 204));
        citybox.setText(" City");
        citybox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityboxFocusGained(evt);
            }
        });
        citybox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityboxKeyReleased(evt);
            }
        });
        getContentPane().add(citybox);
        citybox.setBounds(1120, 590, 410, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText(" Email");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(990, 660, 120, 40);

        emailbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });
        getContentPane().add(emailbox);
        emailbox.setBounds(1120, 660, 410, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Contact  No");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(990, 730, 120, 40);

        telbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telboxKeyPressed(evt);
            }
        });
        getContentPane().add(telbox);
        telbox.setBounds(1120, 730, 410, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/add.png"))); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1410, 800, 120, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel21.setText("               Customer     Registration.");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(450, 20, 450, 29);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/print.png"))); // NOI18N
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(850, 120, 120, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/body.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1570, 890);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 20, 41, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tableload() {
        try {
            String sql;
            sql = "SELECT * FROM cust_reg";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
    }

    public void clear() {
        idbox.setText("");
        fnamebox.setText("");
        lnamebox.setText("");
        nicbox.setText("");
        dobbox.setDate(null);
        buttonGroup1.clearSelection();
        add1box.setText("");
        add2box.setText("");
        citybox.setText("");
        emailbox.setText("");
        telbox.setText("");

        tableload();
    }


    private void nicboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicboxKeyPressed
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_V) {

            nicbox.setEditable(true);
            nicbox.setBackground(Color.white);
        } else {
            nicbox.setEditable(false);
            nicbox.setBackground(Color.red);
        }
    }//GEN-LAST:event_nicboxKeyPressed

    private void lnameboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameboxFocusGained
        lnamebox.setCaretPosition(0);
    }//GEN-LAST:event_lnameboxFocusGained

    private void lnameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameboxKeyPressed
        if (lnamebox.getForeground() != Color.BLACK) {
            if (lnamebox.getText().equals(" Last Name")) {
                lnamebox.setText("");

            }
        }
        lnamebox.setForeground(Color.BLACK);

        int key = evt.getKeyCode();
        if ((key >= evt.VK_A && key <= evt.VK_Z) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_V) {

            lnamebox.setEditable(true);
            lnamebox.setBackground(Color.white);
        } else {
            lnamebox.setEditable(false);
            fnamebox.setBackground(Color.red);
        }

    }//GEN-LAST:event_lnameboxKeyPressed

    private void lnameboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameboxKeyReleased
        if (lnamebox.getText().isEmpty() == true) {
            lnamebox.setText(" Last Name");
            lnamebox.setCaretPosition(0);
            lnamebox.setForeground(new java.awt.Color(204, 204, 204));
        }

    }//GEN-LAST:event_lnameboxKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int custID;
        custID = 1;
        String sql = "SELECT custID+1 from cust_reg";
        try {
            pst = con.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rs = pst.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (rs.next()) {
                idbox.setText(rs.getString("custID+1"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleboxActionPerformed
        gender = "male";
    }//GEN-LAST:event_maleboxActionPerformed

    private void fnameboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameboxFocusGained
        fnamebox.setCaretPosition(0);
    }//GEN-LAST:event_fnameboxFocusGained

    private void fnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameboxActionPerformed

    private void fnameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameboxKeyPressed
        if (fnamebox.getForeground() != Color.BLACK) {
            if (fnamebox.getText().equals(" First Name")) {
                fnamebox.setText("");

            }
        }
        fnamebox.setForeground(Color.BLACK);

        int key = evt.getKeyCode();
        if ((key >= evt.VK_A && key <= evt.VK_Z) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_V) {

            fnamebox.setEditable(true);
            fnamebox.setBackground(Color.white);
        } else {
            fnamebox.setEditable(false);
            fnamebox.setBackground(Color.red);
        }

    }//GEN-LAST:event_fnameboxKeyPressed

    private void fnameboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameboxKeyReleased
        if (fnamebox.getText().isEmpty() == true) {
            fnamebox.setText(" First Name");
            fnamebox.setCaretPosition(0);
            fnamebox.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_fnameboxKeyReleased

    private void femaleboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleboxActionPerformed
        gender = "female";
    }//GEN-LAST:event_femaleboxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r = jTable1.getSelectedRow();

        String ID = jTable1.getValueAt(r, 0).toString();
        String f_name = jTable1.getValueAt(r, 1).toString();
        String l_name = jTable1.getValueAt(r, 2).toString();
        String NIC = jTable1.getValueAt(r, 3).toString();
        String Dob = jTable1.getValueAt(r, 4).toString();
        String Gender = jTable1.getValueAt(r, 5).toString();
        String add1 = jTable1.getValueAt(r, 6).toString();
        String add2 = jTable1.getValueAt(r, 7).toString();
        String City = jTable1.getValueAt(r, 8).toString();
        String Email = jTable1.getValueAt(r, 9).toString();
        String tel = jTable1.getValueAt(r, 10).toString();

        idbox.setText(ID);
        fnamebox.setText(f_name);
        lnamebox.setText(l_name);
        nicbox.setText(NIC);

        try {
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            Date d = f.parse(Dob);
            dobbox.setDate(d);
        } catch (Exception e) {
        }

        if (Gender.equals("female")) {

            malebox.setSelected(false);
            femalebox.setSelected(true);
        } else {

            malebox.setSelected(true);
            femalebox.setSelected(false);
        }

        //genderbox.setSelectedItem(gender);
        add1box.setText(add1);
        add2box.setText(add2);
        citybox.setText(City);
        emailbox.setText(Email);
        telbox.setText(tel);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //update
        String ID = idbox.getText();
        String f_name = fnamebox.getText();
        String l_name = lnamebox.getText();
        String NIC = nicbox.getText();
        //dob
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date bdate;
        bdate = dobbox.getDate();
        String Dob = df.format(bdate);

        String Gender = gender;
        String add1 = add1box.getText();
        String add2 = add2box.getText();
        String City = citybox.getText();
        String Email = emailbox.getText();
        String tel = telbox.getText();

        try {

            StringTokenizer atsign = new StringTokenizer(Email, "@");
            StringTokenizer dotsign = new StringTokenizer(Email, ".");

            if (tel.length() != 10) {
                JOptionPane.showMessageDialog(this, "Please Enter Valid Phone Number");

            } else if (NIC.length() != 10) {
                JOptionPane.showMessageDialog(this, "Please Enter Valid NIC Number");

            } else if (atsign.countTokens() != 2 && dotsign.countTokens() != 2) {
                JOptionPane.showMessageDialog(null, "Please Enter valid Email Address");

            } else {

            String sql = "UPDATE cust_reg set fname=?,lname=?,nic=?,dob=?,gender=?,address1=?,address2=?,city=?,email=?,phone=? where custID=?";

            pst = con.prepareStatement(sql);

            pst.setString(1, f_name);
            pst.setString(2, l_name);
            pst.setString(3, NIC);
            pst.setString(4, Dob);
            pst.setString(5, Gender);
            pst.setString(6, add1);
            pst.setString(7, add2);
            pst.setString(8, City);
            pst.setString(9, Email);
            pst.setString(10, tel);
            pst.setString(11, ID);

            pst.execute();

            tableload();

            JOptionPane.showMessageDialog(this, "Successfully Updated", "Customer", JOptionPane.INFORMATION_MESSAGE);
            clear();
            }

        } catch (HeadlessException e) {
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, e);

        } catch (SQLException ex) {
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //  delete
        String ID = idbox.getText();
        String sql = "DELETE from cust_reg where custID=?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, ID);
            pst.execute();

            tableload();
            JOptionPane.showMessageDialog(this, "Successfully deleted");
            clear();

        } catch (SQLException | HeadlessException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        clear();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int typeno = jComboBox3.getSelectedIndex();
        String type = "";
        String key = searchbox.getText();

        switch (typeno) {
            case 0:
                type = "";
                break;

            case 1:
                type = "custID";
                break;

            case 2:
                type = "fname";
                break;
            case 3:
                type = "lname";
                break;
            case 4:
                type = "city";
                break;
        }

        String sql = "select * from cust_reg where " + type + " like '" + key + "%'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            rs.last();

            JOptionPane.showMessageDialog(null, rs.getRow() + " Results Found!");

        } catch (SQLException | HeadlessException e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void add2boxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add2boxFocusGained
        add2box.setCaretPosition(0);
    }//GEN-LAST:event_add2boxFocusGained

    private void add2boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add2boxKeyPressed

        if (add2box.getForeground() != Color.BLACK) {
            if (add2box.getText().equals(" Line 2  Address")) {
                add2box.setText("");

            }
        }
        add2box.setForeground(Color.BLACK);

    }//GEN-LAST:event_add2boxKeyPressed

    private void add2boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add2boxKeyReleased
        if (add2box.getText().isEmpty() == true) {
            add2box.setText("  Line 2  Address");
            add2box.setCaretPosition(0);
            add2box.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_add2boxKeyReleased

    private void telboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telboxKeyPressed

        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE) {

            telbox.setEditable(true);
            telbox.setBackground(Color.white);
        } else {
            telbox.setEditable(false);
            telbox.setBackground(Color.red);
        }
    }//GEN-LAST:event_telboxKeyPressed

    private void add1boxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add1boxFocusGained
        add1box.setCaretPosition(0);
    }//GEN-LAST:event_add1boxFocusGained

    private void add1boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add1boxKeyPressed

        if (add1box.getForeground() != Color.BLACK) {
            if (add1box.getText().equals(" Line 1  Address")) {
                add1box.setText("");

            }
        }
        add1box.setForeground(Color.BLACK);

    }//GEN-LAST:event_add1boxKeyPressed

    private void add1boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add1boxKeyReleased

        if (add1box.getText().isEmpty() == true) {
            add1box.setText("  Line 1  Address");
            add1box.setCaretPosition(0);
            add1box.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_add1boxKeyReleased

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void cityboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityboxFocusGained
        citybox.setCaretPosition(0);
    }//GEN-LAST:event_cityboxFocusGained

    private void cityboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityboxKeyPressed

        if (citybox.getForeground() != Color.BLACK) {
            if (citybox.getText().equals(" City")) {
                citybox.setText("");

            }
        }
        citybox.setForeground(Color.BLACK);

    }//GEN-LAST:event_cityboxKeyPressed

    private void cityboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityboxKeyReleased
        if (citybox.getText().isEmpty() == true) {
            citybox.setText("  City ");
            citybox.setCaretPosition(0);
            citybox.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_cityboxKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //insert
        String ID = idbox.getText();
        String f_name = fnamebox.getText();
        String l_name = lnamebox.getText();
        String NIC = nicbox.getText();
        //date
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date bdate;
        bdate = dobbox.getDate();

        String Gender = gender;
        String add1 = add1box.getText();
        String add2 = add2box.getText();
        String City = citybox.getText();
        String Email = emailbox.getText();
        String tel = telbox.getText();

        try {

            StringTokenizer atsign = new StringTokenizer(Email, "@");
            StringTokenizer dotsign = new StringTokenizer(Email, ".");

            if (f_name.isEmpty() || l_name.isEmpty() || NIC.isEmpty() || bdate == null || Gender.isEmpty() || add1.isEmpty() || add2.isEmpty() || City.isEmpty() || Email.isEmpty() || tel.isEmpty()) {

                JOptionPane.showMessageDialog(null, "Please fill details");

            } else if (tel.length() != 10) {
                JOptionPane.showMessageDialog(this, "Please Enter Valid Phone Number");

            } else if (NIC.length() != 10) {
                JOptionPane.showMessageDialog(this, "Please Enter Valid NIC Number");

            } else if (atsign.countTokens() != 2 && dotsign.countTokens() != 2) {
                JOptionPane.showMessageDialog(null, "Please Enter valid Email Address");

            } else {
                String Dob = df.format(bdate);
                String sql = "INSERT INTO cust_reg (custID,fname,lname,nic,dob,gender,address1,address2,city,email,phone) values (?,?,?,?,?,?,?,?,?,?,?)";

                pst = con.prepareStatement(sql);

                pst.setString(1, ID);
                pst.setString(2, f_name);
                pst.setString(3, l_name);
                pst.setString(4, NIC);
                pst.setString(5, Dob);
                pst.setString(6, Gender);
                pst.setString(7, add1);
                pst.setString(8, add2);
                pst.setString(9, City);
                pst.setString(10, Email);
                pst.setString(11, tel);

                pst.execute();

                tableload();
                JOptionPane.showMessageDialog(this, "Successfully Inserted", "Customer", JOptionPane.INFORMATION_MESSAGE);
                clear();

            }

        } catch (SQLException | HeadlessException e) {
            System.out.println(e);
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int typeno = jComboBox3.getSelectedIndex();
        String type = "";
        String key = searchbox.getText();
        switch (typeno) {
            case 0:
                type = "";
                break;

            case 1:
                type = "custID";
                break;

            case 2:
                type = "fname";
                break;
            case 3:
                type = "lname";
                break;
            case 4:
                type = "city";
                break;
        }
        if (key.isEmpty()) {
            try {
                String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\customer.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(rep);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else {
            try {
                System.out.print(type);
                JasperDesign jd = JRXmlLoader.load("C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\customer.jrxml");
                String sql = "select * from cust_reg where fname like '" + key + "%'";
                JRDesignQuery n1 = new JRDesignQuery();
                n1.setText(sql);
                jd.setQuery(n1);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add1box;
    private javax.swing.JTextField add2box;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField citybox;
    private com.toedter.calendar.JDateChooser dobbox;
    private javax.swing.JTextField emailbox;
    private javax.swing.JRadioButton femalebox;
    private javax.swing.JTextField fnamebox;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JRadioButton malebox;
    private javax.swing.JTextField nicbox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField telbox;
    // End of variables declaration//GEN-END:variables

    private String gender;

}
