package customer;

import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MUNESH
 */
public final class CustomerHome extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int log;
    
    public CustomerHome() {
        initComponents();
        con = dbconnect.connect();
        today.setText(showDate());
        showTime();
        
        jDesktopPane1.removeAll();
        Animation an=new Animation();
        jDesktopPane1.add(an).setVisible(true);
        
    }
    public CustomerHome(int lg,String n) {
        initComponents();
        con = dbconnect.connect();
        today.setText(showDate());
        showTime();
        
        jDesktopPane1.removeAll();
        Animation an=new Animation();
        jDesktopPane1.add(an).setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hallname = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        ovel = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        today = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home1 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ehandling = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rawhandling = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainmenu = new javax.swing.JLabel();
        mainmenuicon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rawstock = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        estock = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        purchasing = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        supplier = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        hallname.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        hallname.setForeground(new java.awt.Color(255, 255, 255));
        hallname.setText("RAVINDRA RECEPTION HALL");
        jPanel1.add(hallname);
        hallname.setBounds(660, 40, 580, 50);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Customer Main");
        jPanel1.add(title);
        title.setBounds(860, 110, 170, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(170, 22, 1580, 10);

        logo.setText(" ");
        jPanel1.add(logo);
        logo.setBounds(20, 10, 200, 160);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(230, 92, 1460, 10);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/minimize.png"))); // NOI18N
        minimize.setText(" ");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(1840, 10, 40, 32);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/close.png"))); // NOI18N
        close.setText(" ");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1880, 10, 40, 32);

        ovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/logoutback.png"))); // NOI18N
        ovel.setText(" ");
        jPanel1.add(ovel);
        ovel.setBounds(1750, 30, 100, 100);

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setIcon(new javax.swing.ImageIcon("C:\\Users\\MUNESH\\Desktop\\chathu.jpg")); // NOI18N
        user.setText(" ");
        user.setOpaque(true);
        jPanel1.add(user);
        user.setBounds(1750, 30, 100, 100);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("W.A.H.C Weerasinghe");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(name);
        name.setBounds(1740, 140, 140, 20);

        time.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("  ");
        jPanel1.add(time);
        time.setBounds(1480, 110, 210, 30);

        today.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        today.setForeground(new java.awt.Color(255, 255, 255));
        today.setText("  ");
        today.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(today);
        today.setBounds(320, 110, 230, 30);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 160);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        home1.setBackground(new java.awt.Color(0, 0, 0));
        home1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                home1MouseReleased(evt);
            }
        });
        home1.setLayout(null);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/home.png"))); // NOI18N
        home.setText(" ");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        home1.add(home);
        home.setBounds(130, 0, 70, 70);

        jPanel2.add(home1);
        home1.setBounds(0, 230, 320, 70);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        logout.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");
        logout.add(jLabel7);
        jLabel7.setBounds(120, 20, 80, 22);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/logout.png"))); // NOI18N
        jLabel21.setText(" ");
        logout.add(jLabel21);
        jLabel21.setBounds(10, 0, 64, 64);

        jPanel2.add(logout);
        logout.setBounds(0, 980, 320, 70);

        ehandling.setBackground(new java.awt.Color(0, 0, 0));
        ehandling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ehandling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ehandlingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ehandlingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ehandlingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ehandlingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ehandlingMouseReleased(evt);
            }
        });
        ehandling.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Room Reservation");
        ehandling.add(jLabel5);
        jLabel5.setBounds(73, 23, 190, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/touch-screen (2).png"))); // NOI18N
        jLabel6.setText(" ");
        ehandling.add(jLabel6);
        jLabel6.setBounds(10, 0, 64, 64);

        jPanel2.add(ehandling);
        ehandling.setBounds(0, 410, 320, 70);

        rawhandling.setBackground(new java.awt.Color(0, 0, 0));
        rawhandling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rawhandling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rawhandlingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rawhandlingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rawhandlingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rawhandlingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rawhandlingMouseReleased(evt);
            }
        });
        rawhandling.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Customer Registration");
        rawhandling.add(jLabel1);
        jLabel1.setBounds(73, 23, 190, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/user (1).png"))); // NOI18N
        jLabel2.setText(" ");
        rawhandling.add(jLabel2);
        jLabel2.setBounds(10, 0, 64, 64);

        jPanel2.add(rawhandling);
        rawhandling.setBounds(0, 320, 320, 70);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 160, 320, 2);

        mainmenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainmenu.setForeground(new java.awt.Color(255, 255, 255));
        mainmenu.setText("MAIN MENU");
        jPanel2.add(mainmenu);
        mainmenu.setBounds(100, 170, 130, 30);

        mainmenuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/menu.png"))); // NOI18N
        mainmenuicon.setText(" ");
        jPanel2.add(mainmenuicon);
        mainmenuicon.setBounds(10, 170, 32, 32);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 210, 320, 2);

        rawstock.setBackground(new java.awt.Color(0, 0, 0));
        rawstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rawstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rawstockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rawstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rawstockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rawstockMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rawstockMouseReleased(evt);
            }
        });
        rawstock.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Check-In & Check-Out");
        rawstock.add(jLabel11);
        jLabel11.setBounds(80, 20, 200, 22);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/clipboard-verification-symbol.png"))); // NOI18N
        jLabel12.setText(" ");
        rawstock.add(jLabel12);
        jLabel12.setBounds(10, 0, 64, 64);

        jPanel2.add(rawstock);
        rawstock.setBounds(0, 500, 320, 70);

        estock.setBackground(new java.awt.Color(0, 0, 0));
        estock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estockMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                estockMouseReleased(evt);
            }
        });
        estock.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Handle Payments");
        estock.add(jLabel9);
        jLabel9.setBounds(80, 20, 210, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/give-money (1).png"))); // NOI18N
        jLabel10.setText(" ");
        estock.add(jLabel10);
        jLabel10.setBounds(10, 0, 64, 64);

        jPanel2.add(estock);
        estock.setBounds(0, 590, 320, 70);

        purchasing.setBackground(new java.awt.Color(0, 0, 0));
        purchasing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purchasing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                purchasingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                purchasingMouseReleased(evt);
            }
        });
        purchasing.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Manage Rooms");
        purchasing.add(jLabel13);
        jLabel13.setBounds(80, 20, 163, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/bank-building.png"))); // NOI18N
        jLabel14.setText(" ");
        purchasing.add(jLabel14);
        jLabel14.setBounds(10, 0, 64, 64);

        jPanel2.add(purchasing);
        purchasing.setBounds(0, 680, 320, 70);

        supplier.setBackground(new java.awt.Color(0, 0, 0));
        supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supplierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                supplierMouseReleased(evt);
            }
        });
        supplier.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Remind Customer");
        supplier.add(jLabel15);
        jLabel15.setBounds(80, 20, 163, 22);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/supplier.png"))); // NOI18N
        jLabel22.setText(" ");
        supplier.add(jLabel22);
        jLabel22.setBounds(10, 0, 64, 64);

        jPanel2.add(supplier);
        supplier.setBounds(0, 770, 320, 70);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 1080);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jDesktopPane1);
        jDesktopPane1.setBounds(320, 160, 1600, 920);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rawhandlingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawhandlingMouseEntered
        rawhandling.setBackground(Color.BLUE);
    }//GEN-LAST:event_rawhandlingMouseEntered

    private void rawhandlingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawhandlingMouseExited
        rawhandling.setBackground(Color.BLACK);
    }//GEN-LAST:event_rawhandlingMouseExited

    private void rawhandlingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawhandlingMousePressed
        rawhandling.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_rawhandlingMousePressed

    private void rawhandlingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawhandlingMouseReleased
        rawhandling.setForeground(Color.BLACK);
        
        jDesktopPane1.removeAll();
        Cust_reg cr= null;
        cr = new Cust_reg();
        jDesktopPane1.add(cr).setVisible(true);
        
    }//GEN-LAST:event_rawhandlingMouseReleased

    private void ehandlingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseEntered
        ehandling.setBackground(Color.BLUE);
    }//GEN-LAST:event_ehandlingMouseEntered

    private void ehandlingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseExited
        ehandling.setBackground(Color.BLACK);
    }//GEN-LAST:event_ehandlingMouseExited

    private void ehandlingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMousePressed
        ehandling.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_ehandlingMousePressed

    private void ehandlingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseReleased
        ehandling.setForeground(Color.BLACK);
        
        jDesktopPane1.removeAll();
        Room_Reservation rr= null;
        try {
            rr = new Room_Reservation();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(rr).setVisible(true);
        
    }//GEN-LAST:event_ehandlingMouseReleased

    private void rawstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMouseEntered
        rawstock.setBackground(Color.BLUE);
    }//GEN-LAST:event_rawstockMouseEntered

    private void rawstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMouseExited
        rawstock.setBackground(Color.BLACK);
    }//GEN-LAST:event_rawstockMouseExited

    private void rawstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMousePressed
        rawstock.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_rawstockMousePressed

    private void rawstockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMouseReleased
        rawstock.setForeground(Color.BLACK);
        
        jDesktopPane1.removeAll();
        Check ch= null;
        ch = new Check();
        jDesktopPane1.add(ch).setVisible(true);
    }//GEN-LAST:event_rawstockMouseReleased

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
//        home1.setBackground(Color.BLUE);
    }//GEN-LAST:event_home1MouseEntered

    private void home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseExited
        //      home1.setBackground(Color.BLACK);
    }//GEN-LAST:event_home1MouseExited

    private void home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MousePressed
        //      home1.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_home1MousePressed

    private void home1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseReleased
        //      home1.setForeground(Color.BLACK);
    }//GEN-LAST:event_home1MouseReleased

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(Color.BLUE);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        logout.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        log = 0;
        Main.Main m = new Main.Main(0, null);
        m.setVisible(true);
        this.dispose();
        logout.setForeground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseReleased

    private void supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseEntered
        supplier.setBackground(Color.BLUE);
    }//GEN-LAST:event_supplierMouseEntered

    private void supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseExited
        supplier.setBackground(Color.BLACK);
    }//GEN-LAST:event_supplierMouseExited

    private void supplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMousePressed
        supplier.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_supplierMousePressed

    private void supplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseReleased
        supplier.setForeground(Color.BLACK);
        
        jDesktopPane1.removeAll();
        remainder r= null;
        r = new remainder();
        jDesktopPane1.add(r).setVisible(true);
    }//GEN-LAST:event_supplierMouseReleased

    private void estockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseEntered
        estock.setBackground(Color.BLUE);
    }//GEN-LAST:event_estockMouseEntered

    private void estockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseExited
        estock.setBackground(Color.BLACK);
    }//GEN-LAST:event_estockMouseExited

    private void estockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMousePressed
        estock.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_estockMousePressed

    private void estockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseReleased
        estock.setForeground(Color.BLACK);
        
        jDesktopPane1.removeAll();
        Payment pa= null;
        pa = new Payment();
        jDesktopPane1.add(pa).setVisible(true);
    }//GEN-LAST:event_estockMouseReleased

    private void purchasingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseEntered
        purchasing.setBackground(Color.BLUE);
    }//GEN-LAST:event_purchasingMouseEntered

    private void purchasingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseExited
        purchasing.setBackground(Color.BLACK);
    }//GEN-LAST:event_purchasingMouseExited

    private void purchasingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMousePressed
        purchasing.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_purchasingMousePressed

    private void purchasingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseReleased
        purchasing.setForeground(Color.BLACK);
        
        jDesktopPane1.removeAll();
        ManageRooms mr= null;
        mr = new ManageRooms();
        jDesktopPane1.add(mr).setVisible(true);
    }//GEN-LAST:event_purchasingMouseReleased

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/homehover.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/home.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/homepressed.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        jDesktopPane1.removeAll();
        Animation an=new Animation();
        jDesktopPane1.add(an).setVisible(true);
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/home.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseReleased

    private void rawhandlingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawhandlingMouseClicked
        
        
    }//GEN-LAST:event_rawhandlingMouseClicked

    private void rawstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMouseClicked
      
    }//GEN-LAST:event_rawstockMouseClicked

    private void purchasingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseClicked
       
    }//GEN-LAST:event_purchasingMouseClicked

    private void estockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseClicked
       
    }//GEN-LAST:event_estockMouseClicked

    private void ehandlingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ehandlingMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/minimize_hover.png"));
        minimize.setIcon(III);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/minimize.png"));
        minimize.setIcon(III);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        this.setState(CustomerHome.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/close_hover.png"));
        close.setIcon(III);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/close.png"));
        close.setIcon(III);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome().setVisible(true);
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            }
        });
    }

    String showDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        return (s.format(d));
    }

    void showTime() {
        try {
            new Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Date d = new Date();
                    SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                    time.setText(s.format(d));
                }
            }
            ).start();
        } catch (Exception e) {
            System.out.print(e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JPanel ehandling;
    private javax.swing.JPanel estock;
    private javax.swing.JLabel hallname;
    private javax.swing.JLabel home;
    private javax.swing.JPanel home1;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel mainmenu;
    private javax.swing.JLabel mainmenuicon;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel ovel;
    private javax.swing.JPanel purchasing;
    private javax.swing.JPanel rawhandling;
    private javax.swing.JPanel rawstock;
    private javax.swing.JPanel supplier;
    private javax.swing.JLabel time;
    private javax.swing.JLabel title;
    private javax.swing.JLabel today;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
