/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import com.sun.glass.events.KeyEvent;
import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Payment extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    customer c = new customer();

    public Payment() {
        initComponents();

        con = dbconnect.connect();

        tableload();
        tableload2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        searchbox2 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        paymentbox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        transportbox = new javax.swing.JTextField();
        otherbox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cidbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        reservationbox = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        datebox = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        ptypebox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        advancebox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totpaidbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        statusbox = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        searchbox = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton12 = new javax.swing.JButton();
        searchbox3 = new javax.swing.JTextField();
        search1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        paymentbox1 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        transportbox1 = new javax.swing.JTextField();
        otherbox1 = new javax.swing.JTextField();
        reservationbox1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cidbox1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eventbox1 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        datebox1 = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        ptypebox1 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        advancebox1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        totpaidbox1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        statusbox1 = new javax.swing.JComboBox();
        jButton18 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        searchbox1 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        searchbutton1 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        cidbox2 = new javax.swing.JTextField();
        eventbox2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(null);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(318, 1421, 86, 23);

        searchbox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(searchbox2);
        searchbox2.setBounds(240, 500, 270, 40);

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        search.setText(" Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(530, 490, 140, 50);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Print Receipt");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(431, 1421, 114, 23);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "PaymentID", "CustID", "PaymentDate", "PaymentType", "TotalPayment", "Status" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(30, 500, 190, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Receipt");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(551, 1421, 86, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText(" Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(219, 1421, 93, 23);

        jToggleButton1.setText("print Bil");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(134, 1422, 75, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 560, 810, 240);

        paymentbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentboxActionPerformed(evt);
            }
        });
        getContentPane().add(paymentbox);
        paymentbox.setBounds(1100, 390, 300, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/different-currencies.png"))); // NOI18N
        jButton2.setText(" Total  Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(870, 380, 210, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("   Other  Payments");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(860, 330, 206, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("   Payment  For  Transport");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(860, 270, 217, 40);

        transportbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(transportbox);
        transportbox.setBounds(1100, 270, 300, 40);

        otherbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(otherbox);
        otherbox.setBounds(1100, 330, 300, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("   Payment  For  Reservation");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(860, 210, 226, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("   Payment  For  Event");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(860, 150, 179, 40);

        cidbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cidbox);
        cidbox.setBounds(1670, 240, 300, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("   Customer  ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(860, 90, 143, 40);

        reservationbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reservationbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationboxActionPerformed(evt);
            }
        });
        getContentPane().add(reservationbox);
        reservationbox.setBounds(1100, 210, 300, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/bar-chart-reload.png"))); // NOI18N
        jButton3.setText("Generate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1240, 90, 160, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Date");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(930, 490, 104, 43);
        getContentPane().add(datebox);
        datebox.setBounds(1110, 490, 300, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Payment  Type");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(930, 540, 140, 50);

        ptypebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ptypebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  Payment  Type", "Paid", "Not  Paid", "Advance  Paid", "Total  Payment  Paid", " " }));
        getContentPane().add(ptypebox);
        ptypebox.setBounds(1110, 550, 300, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Advance   Paid");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(930, 600, 140, 50);

        advancebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        advancebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                advanceboxKeyPressed(evt);
            }
        });
        getContentPane().add(advancebox);
        advancebox.setBounds(1110, 610, 300, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Total  Amount  Paid");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1020, 1210, 159, 50);

        totpaidbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totpaidbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totpaidboxKeyPressed(evt);
            }
        });
        getContentPane().add(totpaidbox);
        totpaidbox.setBounds(1110, 670, 300, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Status");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(930, 720, 140, 50);

        statusbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  status", "Processing", "Payment  successful" }));
        statusbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusboxActionPerformed(evt);
            }
        });
        getContentPane().add(statusbox);
        statusbox.setBounds(1110, 730, 300, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/add.png"))); // NOI18N
        jButton6.setText("Insert");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1270, 790, 140, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setText("Handle     Payments.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(740, 20, 280, 31);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setFillsViewportHeight(true);
        jTable3.setRowHeight(30);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 200, 800, 240);

        searchbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        getContentPane().add(searchbox);
        searchbox.setBounds(240, 120, 270, 40);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "CustID", "Fname", "Lname", "City" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(30, 120, 190, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("View Payment Details");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 450, 227, 22);

        searchbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton);
        searchbutton.setBounds(520, 120, 140, 50);

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(1600, 920));
        jInternalFrame1.getContentPane().setLayout(null);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Clear");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton12);
        jButton12.setBounds(318, 1421, 86, 23);

        searchbox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(searchbox3);
        searchbox3.setBounds(230, 560, 270, 40);

        search1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search1.setText(" Search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(search1);
        search1.setBounds(520, 550, 140, 50);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("Print Receipt");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton13);
        jButton13.setBounds(431, 1421, 114, 23);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "PaymentID", "CustID", "PaymentDate", "PaymentType", "TotalPayment", "Status" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jComboBox4);
        jComboBox4.setBounds(20, 560, 190, 40);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("Receipt");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton14);
        jButton14.setBounds(551, 1421, 86, 23);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText(" Update");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton15);
        jButton15.setBounds(219, 1421, 93, 23);

        jToggleButton3.setText("print Bil");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(134, 1422, 75, 25);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setFillsViewportHeight(true);
        jTable2.setRowHeight(30);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jInternalFrame1.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 650, 630, 270);

        paymentbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(paymentbox1);
        paymentbox1.setBounds(950, 580, 300, 40);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setText("Calculate  Total  Payment");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton16);
        jButton16.setBounds(680, 580, 261, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("   Other  Payments");
        jInternalFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(710, 510, 206, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("   Payment  For  Transport");
        jInternalFrame1.getContentPane().add(jLabel16);
        jLabel16.setBounds(710, 430, 217, 40);

        transportbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(transportbox1);
        transportbox1.setBounds(950, 430, 300, 40);

        otherbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(otherbox1);
        otherbox1.setBounds(950, 510, 300, 40);

        reservationbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reservationbox1.setBorder(null);
        reservationbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationbox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(reservationbox1);
        reservationbox1.setBounds(950, 360, 300, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("   Payment  For  Reservation");
        jInternalFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(710, 360, 226, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("   Payment  For  Event");
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 290, 179, 40);

        cidbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(cidbox1);
        cidbox1.setBounds(950, 140, 300, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("   Customer  ID");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 140, 143, 40);

        eventbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eventbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventbox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(eventbox1);
        eventbox1.setBounds(950, 290, 300, 40);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setText("Generate");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton17);
        jButton17.setBounds(1110, 210, 140, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Date");
        jInternalFrame1.getContentPane().add(jLabel18);
        jLabel18.setBounds(964, 760, 104, 43);
        jInternalFrame1.getContentPane().add(datebox1);
        datebox1.setBounds(1154, 750, 410, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Payment  Type");
        jInternalFrame1.getContentPane().add(jLabel19);
        jLabel19.setBounds(964, 818, 140, 50);

        ptypebox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ptypebox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  Payment  Type", "Paid", "Not  Paid", "Advance  Paid", "Total  Payment  Paid", " " }));
        jInternalFrame1.getContentPane().add(ptypebox1);
        ptypebox1.setBounds(1154, 823, 410, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Advance   Paid");
        jInternalFrame1.getContentPane().add(jLabel20);
        jLabel20.setBounds(964, 891, 140, 50);

        advancebox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        advancebox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                advancebox1KeyPressed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(advancebox1);
        advancebox1.setBounds(1154, 896, 410, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Total  Amount  Paid");
        jInternalFrame1.getContentPane().add(jLabel21);
        jLabel21.setBounds(964, 964, 159, 50);

        totpaidbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totpaidbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totpaidbox1KeyPressed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(totpaidbox1);
        totpaidbox1.setBounds(1154, 969, 410, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Status");
        jInternalFrame1.getContentPane().add(jLabel22);
        jLabel22.setBounds(964, 1037, 140, 50);

        statusbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusbox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  status", "Processing", "Payment  successful" }));
        statusbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusbox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(statusbox1);
        statusbox1.setBounds(1154, 1042, 410, 40);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setText("Insert");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton18);
        jButton18.setBounds(1420, 1130, 140, 50);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Handle     Payments.");
        jInternalFrame1.getContentPane().add(jLabel23);
        jLabel23.setBounds(844, 22, 205, 22);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setFillsViewportHeight(true);
        jTable4.setRowHeight(30);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);

        jInternalFrame1.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(10, 220, 580, 250);

        searchbox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(searchbox1);
        searchbox1.setBounds(237, 143, 270, 40);

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "CustID", "Fname", "Lname", "City" }));
        jInternalFrame1.getContentPane().add(jComboBox6);
        jComboBox6.setBounds(29, 143, 190, 40);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("View Customer  Details");
        jInternalFrame1.getContentPane().add(jLabel24);
        jLabel24.setBounds(29, 86, 227, 22);

        searchbutton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        searchbutton1.setText("Search");
        searchbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbutton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(searchbutton1);
        searchbutton1.setBounds(520, 140, 140, 50);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton19.setText("Clear");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton19);
        jButton19.setBounds(0, 0, 63, 23);

        jToggleButton4.setText("print Bil");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(0, 0, 75, 25);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton20.setText("Receipt");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton20);
        jButton20.setBounds(0, 0, 79, 23);

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton21.setText(" Update");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton21);
        jButton21.setBounds(0, 0, 81, 23);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(600, 240, 140, 50);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/update.png"))); // NOI18N
        jButton9.setText(" Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(310, 810, 140, 50);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/clear.png"))); // NOI18N
        jButton10.setText("Clear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(470, 810, 140, 50);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/invoice.png"))); // NOI18N
        jButton11.setText("Receipt");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(630, 810, 140, 50);
        getContentPane().add(cidbox2);
        cidbox2.setBounds(1100, 90, 130, 40);

        eventbox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eventbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventbox2ActionPerformed(evt);
            }
        });
        getContentPane().add(eventbox2);
        eventbox2.setBounds(1100, 150, 300, 40);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Total  Amount  Paid");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(930, 660, 170, 50);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("View Customer  Details");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(29, 86, 227, 22);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/body.jpg"))); // NOI18N
        jLabel27.setText(" ");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 1590, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tableload() {
        try {
            String sql;
            sql = "SELECT * FROM cust_reg";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            jTable3.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
    }

    public void tableload2() {
        try {
            String sql;
            sql = "SELECT * FROM payment_handle";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
    }

    public void clear() {

        cidbox.setText("");
        reservationbox.setText("");
        reservationbox.setText("");
        transportbox.setText("");
        otherbox.setText("");
        paymentbox.setText("");
        //pidbox.setText("");
        datebox.setDate(null);
        ptypebox.setSelectedIndex(0);
        advancebox.setText("");
        totpaidbox.setText("");
        statusbox.setSelectedIndex(0);
        ;

        tableload();
    }


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clear();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        int typeno = jComboBox3.getSelectedIndex();
        String type = "";
        String key = searchbox2.getText();

        switch (typeno) {
            case 0:
                type = "";
                break;

            case 1:
                type = "PID";
                break;

            case 2:
                type = "CID";
                break;

            case 3:
                type = "pdate";
                break;

            case 4:
                type = "PayType";
                break;

            case 5:
                type = "Totl";
                break;

            case 6:
                type = "Status";
                break;

        }

        rs = c.Paymentsearch(type, key);

        jTable1.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_searchActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

//        try{
//
//            boolean complete = jTextArea1.print();
//            if(complete){
//
//                JOptionPane.showMessageDialog(null, "Done printing","Information",JOptionPane.INFORMATION_MESSAGE);
//            }
//            else{
//
//                JOptionPane.showMessageDialog(null,"printing","Printer",JOptionPane.ERROR_MESSAGE);
//            }
//        }
//        catch(PrinterException e){
//
//            JOptionPane.showMessageDialog(null,e);
//        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        double event = Double.parseDouble(reservationbox.getText());
        double reservation = Double.parseDouble(reservationbox.getText());
        double transport = Double.parseDouble(transportbox.getText());
        double other = Double.parseDouble(otherbox.getText());
        double total = Double.parseDouble(paymentbox.getText());

        receipt re;
        try {
            re = new receipt(event, reservation, transport, other, total);
            re.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }

//        jTextArea1.append("Ravindra Reception Hall\n" + "Kosgama\n" + "036 2255355\n" + "_______________________________________\n" + "\tReceipt\n\n" + "Payment for Event\t\t" + event + "\nPayment for Room Reservation\t" + reservation + "\nPayment for Transport\t\t" + transport + "\nOther Payments\t\t" + other + "\n_______________________________________\n" + "\nTotal Payment\t\t\t" + total + "\n\n\n\n\n" + "_______________________________________\n" + "\tThank you for your visit");
//
//        try{
//            FileWriter writer = new FileWriter ("C:\\Users\\DELL\\Desktop\\Receipt.txt");
//            try(BufferedWriter w = new BufferedWriter(writer)){
//                jTextArea1.write(w);
//
//            }
//
//        } catch (IOException ex) {
//            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //update
        String cid = cidbox.getText();

        //date
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date Ptype;
        Ptype = datebox.getDate();
        String Paydate = df.format(Ptype);

        String PayType = ptypebox.getSelectedItem().toString();
        String advance = advancebox.getText();
        String Total = totpaidbox.getText();
        String pstatus = statusbox.getSelectedItem().toString();
        // String pid = pidbox.getText();

        try {
            String sql = "UPDATE payment_handle set pdate=?,PayType=?,Advance=?,Total=?,Status=? where CID=?";

            pst = con.prepareStatement(sql);

            //    pst.setString(1, cid);
            pst.setString(1, Paydate);
            pst.setString(2, PayType);
            pst.setString(3, advance);
            pst.setString(4, Total);
            pst.setString(5, pstatus);
            pst.setString(6, cid);

            pst.execute();

            tableload2();

            JOptionPane.showMessageDialog(this, "Successfully Updated");
            clear();

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

//
//        PrinterJob pj = PrinterJob.getPrinterJob();
//        pj.setPrintable(new BillPrintable(),getPageFormat(pj));
//        try{
//            pj.print();
//
//        }catch(PrinterException ex){
//
//            ex.printStackTrace();
//            System.out.println(ex);
//        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r = jTable1.getSelectedRow();

        String pdate = jTable1.getValueAt(r, 1).toString();
        String ptype = jTable1.getValueAt(r, 2).toString();
        String advance = jTable1.getValueAt(r, 3).toString();
        String totpaid = jTable1.getValueAt(r, 4).toString();
        String status = jTable1.getValueAt(r, 5).toString();

        try {
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            Date d = f.parse(pdate);
            datebox.setDate(d);
        } catch (Exception e) {
        }

        ptypebox.setSelectedItem(ptype);
        advancebox.setText(advance);
        totpaidbox.setText(totpaid);
        statusbox.setSelectedItem(status);

        try {
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            Date d = f.parse(pdate);
            datebox.setDate(d);
        } catch (Exception e) {
        }

        advancebox.setText(advance);
        totpaidbox.setText(totpaid);
        statusbox.setSelectedItem(status);

    }//GEN-LAST:event_jTable1MouseClicked

    private void paymentboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentboxActionPerformed

    }//GEN-LAST:event_paymentboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String event = reservationbox.getText();
        float e = Float.parseFloat(event);
        String resevartion = reservationbox.getText();
        float r = Float.parseFloat(resevartion);
        String transport = transportbox.getText();
        float t = Float.parseFloat(transport);
        String other = otherbox.getText();
        float o = Float.parseFloat(other);
        float tot = e + r + t + o;
        String total = Float.toString(tot);
        paymentbox.setText(total);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reservationboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String cid = cidbox2.getText();
        String nic="0";
        try {
            String sql1 = "SELECT * FROM cust_reg WHERE custID like '" + cid + "' ";
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();
            if (rs.next()) {
                nic = rs.getString("nic");
            }
        } catch (Exception e) {

        }
        String sql = "select Total from event_booking where Cus_NIC = '" + nic + "' ";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {

                eventbox2.setText(rs.getString("Total"));

            } else {
                eventbox2.setText("0");
            }

        } catch (SQLException | HeadlessException e) {
        }

        String sql2 = "select Payment from booking where custID = '" + cid + "' ";
        try {

            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();

            if (rs.next()) {

                reservationbox.setText(rs.getString("Payment"));

            } else {
                reservationbox.setText("0");
            }

        } catch (SQLException | HeadlessException e) {
        }

        String sql3 = "select Cost_Calc from vehicle_booking where Customer_NIC = '" + nic + "' ";
        try {

            pst = con.prepareStatement(sql3);
            rs = pst.executeQuery();

            if (rs.next()) {

                transportbox.setText(rs.getString("Cost_Calc"));

            } else {
                transportbox.setText("0");
            }

        } catch (SQLException | HeadlessException e) {
            System.out.print(e);
        }

        String sql4 = "select exPayment from checks where custID = '" + cid + "' ";
        try {

            pst = con.prepareStatement(sql4);
            rs = pst.executeQuery();

            if (rs.next()) {

                otherbox.setText(rs.getString("exPayment"));
            } else {
                otherbox.setText("0");
            }

        } catch (SQLException | HeadlessException e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void statusboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusboxActionPerformed

    private void advanceboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advanceboxKeyPressed
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE) {

            advancebox.setEditable(true);
            advancebox.setBackground(Color.white);
        } else {
            advancebox.setEditable(false);
            advancebox.setBackground(Color.red);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_advanceboxKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //insert

        String cid = cidbox2.getText();
        // String PID = pidbox.getText();
        String pay = paymentbox.getText();
        String ptype = ptypebox.getSelectedItem().toString();

        //date
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date bdate;
        bdate = datebox.getDate();
        String PDate = df.format(bdate);

        String advance = advancebox.getText();;
        String totpaid = totpaidbox.getText();
        String status = statusbox.getSelectedItem().toString();

        try {
            String sql = "INSERT INTO payment_handle (CID,payment,pdate,PayType,Advance,Total,Status) values (?,?,?,?,?,?,?)";

            pst = con.prepareStatement(sql);

            // pst.setString(1,ID);
            pst.setString(1, cid);
            pst.setString(2, pay);
            pst.setString(3, PDate);
            pst.setString(4, ptype);
            pst.setString(5, advance);
            pst.setString(6, totpaid);
            pst.setString(7, status);

            pst.execute();

            tableload2();

            JOptionPane.showMessageDialog(this, "Successfully Recorded");

            clear();

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void totpaidboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totpaidboxKeyPressed
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE) {

            totpaidbox.setEditable(true);
            totpaidbox.setBackground(Color.white);
        } else {
            totpaidbox.setEditable(false);
            totpaidbox.setBackground(Color.red);
        }
    }//GEN-LAST:event_totpaidboxKeyPressed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

//        int r = jTable3.getSelectedRow();
//
//        String ID = jTable3.getValueAt(r, 0).toString();
//        String BID = jTable3.getValueAt(r, 1).toString();
//        String checkkin = jTable3.getValueAt(r, 2).toString();
//        String reservedTo = jTable3.getValueAt(r, 3).toString();
//        String checkout = jTable3.getValueAt(r, 4).toString();
//        String ex = jTable3.getValueAt(r, 5).toString();
//        String expay = jTable3.getValueAt(r,6).toString();
//
//        idbox.setText(ID);
//        bookidbox.setText(BID);
//
//       
//        try {
//            DateFormat f = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
//            Date d2 = f.parse(checkout);
//            checkoutbox.setDate(d2);
//        } catch (Exception e) {
//        }
//
//        extraDaysbox.setText(ex);
//        expaybox.setText(expay);
        int r = jTable3.getSelectedRow();

        String ID = jTable3.getValueAt(r, 0).toString();

        cidbox2.setText(ID);
    }//GEN-LAST:event_jTable3MouseClicked

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed

        // TODO add your handling code here:
        int typeno = jComboBox5.getSelectedIndex();
        String type = "";
        String key = searchbox.getText();

        switch (typeno) {
            case 0:
                type = "";
                break;

            case 1:
                type = "custID";
                break;

            case 2:
                type = "fname";
                break;
            case 3:
                type = "lname";
                break;
            case 4:
                type = "city";
                break;
        }

        rs = c.customersearch(type, key);
        jTable3.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void paymentbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentbox1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void reservationbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationbox1ActionPerformed

    private void eventbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventbox1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void advancebox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advancebox1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_advancebox1KeyPressed

    private void totpaidbox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totpaidbox1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_totpaidbox1KeyPressed

    private void statusbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusbox1ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    private void searchbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbox1ActionPerformed

    private void searchbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbutton1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //update
        String cid = cidbox.getText();

        //date
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date Ptype;
        Ptype = datebox.getDate();
        String Paydate = df.format(Ptype);

        String PayType = ptypebox.getSelectedItem().toString();
        String advance = advancebox.getText();
        String Total = totpaidbox.getText();
        String pstatus = statusbox.getSelectedItem().toString();
        // String pid = pidbox.getText();

        try {
            String sql = "UPDATE payment_handle set pdate=?,PayType=?,Advance=?,Total=?,Status=? where CID=?";

            pst = con.prepareStatement(sql);

            //    pst.setString(1, cid);
            pst.setString(1, Paydate);
            pst.setString(2, PayType);
            pst.setString(3, advance);
            pst.setString(4, Total);
            pst.setString(5, pstatus);
            pst.setString(6, cid);

            pst.execute();

            tableload2();

            JOptionPane.showMessageDialog(this, "Successfully Updated");
            clear();

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        clear();
        tableload2();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        double event = Double.parseDouble(reservationbox.getText());
        double reservation = Double.parseDouble(reservationbox.getText());
        double transport = Double.parseDouble(transportbox.getText());
        double other = Double.parseDouble(otherbox.getText());
        double total = Double.parseDouble(paymentbox.getText());

        receipt re;
        try {
            re = new receipt(event, reservation, transport, other, total);
            re.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void eventbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventbox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advancebox;
    private javax.swing.JTextField advancebox1;
    private javax.swing.JTextField cidbox;
    private javax.swing.JTextField cidbox1;
    private javax.swing.JTextField cidbox2;
    private com.toedter.calendar.JDateChooser datebox;
    private com.toedter.calendar.JDateChooser datebox1;
    private javax.swing.JTextField eventbox1;
    private javax.swing.JTextField eventbox2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField otherbox;
    private javax.swing.JTextField otherbox1;
    private javax.swing.JTextField paymentbox;
    private javax.swing.JTextField paymentbox1;
    private javax.swing.JComboBox ptypebox;
    private javax.swing.JComboBox ptypebox1;
    private javax.swing.JTextField reservationbox;
    private javax.swing.JTextField reservationbox1;
    private javax.swing.JButton search;
    private javax.swing.JButton search1;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField searchbox1;
    private javax.swing.JTextField searchbox2;
    private javax.swing.JTextField searchbox3;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton searchbutton1;
    private javax.swing.JComboBox statusbox;
    private javax.swing.JComboBox statusbox1;
    private javax.swing.JTextField totpaidbox;
    private javax.swing.JTextField totpaidbox1;
    private javax.swing.JTextField transportbox;
    private javax.swing.JTextField transportbox1;
    // End of variables declaration//GEN-END:variables
}
