/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import dbconnect.dbconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class remainder extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    customer c = new customer();

    public remainder() {
        initComponents();

        con = dbconnect.connect();

        tableload();
        loadreminder();

    }

    public void tableload() {
        try {
            String sql;
            sql = "SELECT * FROM cust_reg";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            custTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
    }

    public void clear() {

        idbox.setText("");
        namebox.setText("");
        mailbox.setText("");
        subbox.setText("");
        descriptionbox.setText("");

        loadreminder();
    }

    public void loadreminder() {
        try {

            con = dbconnect.connect();
            String sql;
            sql = "select * from reminder";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

//            Connection c=DBconnect.connect();
//        Statement s = c.createStatement();
//        ResultSet rs = s.executeQuery("select id as 'Reminder ID',customerid as 'Customer ID',email as 'Email' from reminder");
            remindTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mailbox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();
        subbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        searchbutton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        descriptionbox = new javax.swing.JTextArea();
        jComboBox5 = new javax.swing.JComboBox();
        searchbox1 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        remindTable = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox();
        searchbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Customer  ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 191, 140, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Email  Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 340, 140, 50));

        idbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 196, 410, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Customer Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 267, 140, 50));

        mailbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(mailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 345, 410, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("View  customer  details  ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 85, 227, -1));

        namebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 272, 410, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Subject");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 416, 140, 50));

        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        custTable.setFillsViewportHeight(true);
        custTable.setRowHeight(30);
        custTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                custTableMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(custTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 191, 900, 265));

        subbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(subbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 421, 410, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 502, 140, 50));

        searchbutton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        searchbutton1.setText("Search");
        searchbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 503, 140, 50));

        descriptionbox.setColumns(20);
        descriptionbox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        descriptionbox.setRows(5);
        jScrollPane5.setViewportView(descriptionbox);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 502, 410, 159));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "Remainder ID", "Description", "Remainder Date", "Customer Email", "Email Status", "" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 508, 190, 40));
        getContentPane().add(searchbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 510, 270, 40));

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/clear.png"))); // NOI18N
        jButton16.setText("Clear");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1214, 726, 150, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText(" View  Reminder   details  ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 463, 251, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/speech-bubble-oval-shape-with-text-lines.png"))); // NOI18N
        jButton3.setText("SEND EMAIL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 726, -1, 40));

        remindTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        remindTable.setFillsViewportHeight(true);
        remindTable.setRowHeight(30);
        remindTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remindTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(remindTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 571, 900, 284));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "CustID", "Fname", "Lname", "NIC", "City" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 125, 190, 40));
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 127, 270, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setText("Remind  Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 13, 269, -1));

        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 120, 140, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/print.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 120, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/body.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custTableMouseClicked

        int r = custTable.getSelectedRow();

        String id = custTable.getValueAt(r, 0).toString();
        String f_name = custTable.getValueAt(r, 1).toString();
        String email = custTable.getValueAt(r, 9).toString();
        // String fname =custTable.getValueAt(r, 3).toString();

        idbox.setText(id);
        namebox.setText(f_name);
        //.setText(contacno);

        mailbox.setText(email);
    }//GEN-LAST:event_custTableMouseClicked

    private void custTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_custTableMouseEntered

    private void searchbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbutton1ActionPerformed
        int typeno = jComboBox5.getSelectedIndex();
        String type = "";
        String key = searchbox1.getText();

        switch (typeno) {
            case 0:
                type = "";
                break;

            case 1:
                type = "custID";
                break;
            case 2:
                type = "email";
                break;
            case 3:
                type = "fname";
                break;

        }

        rs = c.Remaindersearch(type, key);

        remindTable.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_searchbutton1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed


    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String id = idbox.getText();
        String cus  = namebox.getText();
        String email = mailbox.getText();
        String sub = subbox.getText();
        String dis = subbox.getText();
        
        try {

            StringTokenizer atsign = new StringTokenizer(email, "@");
            StringTokenizer dotsign = new StringTokenizer(email, ".");

            if (id.isEmpty() || cus.isEmpty() || email.isEmpty() ||  sub.isEmpty() || dis.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill details");
            } else if (atsign.countTokens() != 2 && dotsign.countTokens() != 2) {
                JOptionPane.showMessageDialog(null, "Please Enter valid Email Address");
            } else {
                try {
                    Date d = new Date();
                    String dt = new SimpleDateFormat("yyyy-MM-dd").format(d);
                    GMailclient g = new GMailclient(mailbox.getText(), subbox.getText(), descriptionbox.getText());
                    con = dbconnect.connect();

                    //Connection c=DBconnect.connect();
                    Statement s = con.createStatement();
                    s.executeUpdate("INSERT INTO reminder(cid,email,description,rdate) values('" + idbox.getText() + "','" + mailbox.getText() + "','" + descriptionbox.getText() + "' ,'" + dt + "')");

                    loadreminder();

                    JOptionPane.showMessageDialog(rootPane, "Succesfully Sent!!");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Email Failed!!");
                    System.out.println(e);
                }
            }
        }catch(Exception e)
                    {
                    
                    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void remindTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remindTableMouseClicked

        int r = remindTable.getSelectedRow();

        //getting value of the respective row
        String id = remindTable.getValueAt(r, 0).toString();
        String cid = remindTable.getValueAt(r, 1).toString();
        String email = remindTable.getValueAt(r, 2).toString();
        String description = remindTable.getValueAt(r, 3).toString();
        String date = remindTable.getValueAt(r, 4).toString();

        System.out.println(date);
        //ridbox.setText(id);

        idbox.setText(cid);
        subbox.setText(email);
        descriptionbox.setText(description);
    }//GEN-LAST:event_remindTableMouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        int typeno = jComboBox4.getSelectedIndex();
        String type = "";
        String key = searchbox.getText();

        switch (typeno) {
            case 0:
                type = "";
                break;

            case 1:
                type = "custID";
                break;

            case 2:
                type = "fname";
                break;
            case 3:
                type = "email";
                break;

        }

        rs = c.customersearch(type, key);

        custTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fname = searchbox1.getText();
        if (fname.isEmpty()) {
            try {
                String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\reminder.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(rep);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else {
            try {

                JasperDesign jd = JRXmlLoader.load("C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\reminder.jrxml");
                String sql = "select * from reminder where cid like '%" + fname + "%'";
                JRDesignQuery n1 = new JRDesignQuery();
                n1.setText(sql);
                jd.setQuery(n1);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable custTable;
    private javax.swing.JTextArea descriptionbox;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField mailbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTable remindTable;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField searchbox1;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton searchbutton1;
    private javax.swing.JTextField subbox;
    // End of variables declaration//GEN-END:variables
}
