/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import dbconnect.dbconnect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class Reservation extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    private String RoomNo;
    private String Price;
    customer c;
    
    public Reservation() {
        initComponents();
        this.c = new customer();
        con = dbconnect.connect();
    }
    
     public Reservation(String roomno,String price) throws ClassNotFoundException, SQLException {
        this.c = new customer();
        
        initComponents();
        
        this.RoomNo=roomno;
        roomnobox.setText(RoomNo);
        System.out.println(RoomNo);
        
        this.Price=price;
        pricebox.setText(Price);
        System.out.println(Price);
        
        con = dbconnect.connect();
        
        tableload();
        tableload2();
        
    }
     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbox2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchbox = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        roomnobox = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cidbox = new javax.swing.JTextField();
        bookingfrombox = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        bookingtobox = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Noofdaysbox = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        bidbox = new javax.swing.JLabel();
        pricebox = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totpaybox = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        statusbox = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 920));
        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(searchbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 270, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setFillsViewportHeight(true);
        jTable2.setRowHeight(30);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 211, 1030, 260));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 1030, 240));
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, 40));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "CustID", "Fname", "Lname", "NIC", "City" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("View   Customer  details");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 48));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  search  type", "BookID", "RoomNo", "RoomType", "ReservedFrom", "ReservedTo", "Status", "PaymentStatus", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 190, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 140, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/search.png"))); // NOI18N
        jButton1.setText(" Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 140, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/update.png"))); // NOI18N
        jButton2.setText(" Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 820, 140, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/delete.png"))); // NOI18N
        jButton3.setText(" Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 820, 140, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/clear.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 820, 140, 50));

        roomnobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomnobox.setText("              ");
        getContentPane().add(roomnobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 270, 300, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Booking  From");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 380, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Customer  ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Room  No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 270, 140, 40));

        cidbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 210, 300, 40));
        getContentPane().add(bookingfrombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 380, 300, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Booking  To");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 440, 140, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/add.png"))); // NOI18N
        jButton6.setText("Insert");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 700, 140, 50));
        getContentPane().add(bookingtobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 440, 300, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Room Price");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 140, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("No of Days Booking");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 500, 140, 40));

        Noofdaysbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Noofdaysbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 500, 130, 40));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/bar-chart-reload.png"))); // NOI18N
        jButton10.setText("Generate");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 500, 160, 50));
        getContentPane().add(bidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 101, 79, 19));

        pricebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(pricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 330, 300, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Payment");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 570, 140, 40));

        totpaybox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(totpaybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 570, 300, 40));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/images/different-currencies.png"))); // NOI18N
        jToggleButton1.setText("Payment");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseReleased(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 700, 150, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 630, 140, 40));

        statusbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enter the booking status", "Reserved", "Occupied", "Free" }));
        getContentPane().add(statusbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 630, 300, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/print.png"))); // NOI18N
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 120, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel10.setText("Manage    Room    Reservations.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/body.jpg"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tableload() {
       try{ 
           String sql;
           sql = "SELECT * FROM cust_reg";
          
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
           
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
             
       } catch (Exception e) {
         // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
    } 
    
    public void tableload2() {
       try{ 
           String sql2;
           sql2 = "SELECT * FROM booking";
          
             pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();
           
           
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
       } catch (Exception e) {
           System.out.println(e);
           JOptionPane.showMessageDialog(this,e);
         // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
    } 
    
    public void clear(){
        bidbox.setText("");
        cidbox.setText("");
        roomnobox.setText("");
        pricebox.setText("");
        bookingfrombox.setDate(null);
        bookingtobox.setDate(null);
        Noofdaysbox.setText("");
        totpaybox.setText("");
//        ptypebox.setSelectedIndex(0);
//        amountbox.setText("");
//        statusbox.setSelectedIndex(0);
//        bstatusbox.setSelectedIndex(0);
        
        tableload2();
    }
    
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int r = jTable2.getSelectedRow();

        String ID = jTable2.getValueAt(r, 0).toString();

        cidbox.setText(ID);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r = jTable1.getSelectedRow();

        String bookid = jTable1.getValueAt(r, 0).toString();
        String  cid = jTable1.getValueAt(r, 1).toString();
        String Roomno = jTable1.getValueAt(r, 2).toString();
        String price = jTable1.getValueAt(r, 3).toString();
        String Dfrom = jTable1.getValueAt(r, 4).toString();
        String Dto = jTable1.getValueAt(r, 5).toString();
        String days = jTable1.getValueAt(r, 6).toString();
        String payment = jTable1.getValueAt(r, 7).toString();
        String paytype = jTable1.getValueAt(r, 8).toString();
        String paidamount = jTable1.getValueAt(r, 9).toString();
        String pstatus  = jTable1.getValueAt(r, 10).toString();
        String bookstatus= jTable1.getValueAt(r, 11).toString();

        bidbox.setText(bookid);
        cidbox.setText(cid);
        roomnobox.setText(Roomno);
        pricebox.setText(price);
        //bookingfrombox.setDate(null);

        try {
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
            Date d = f.parse(Dfrom);
            bookingfrombox.setDate(d);

        } catch (Exception e) {
        }

        try {
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
            Date d = f.parse(Dto);
            bookingtobox.setDate(d);

        } catch (Exception e) {
        }

        Noofdaysbox.setText(days);
        totpaybox.setText(payment);
        //        ptypebox.setSelectedItem(paytype);
        //        amountbox.setText(paidamount);
        //        statusbox.setSelectedItem(pstatus);
        //        bstatusbox.setSelectedItem(bookstatus);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        int typeno = jComboBox1.getSelectedIndex();
        String type = "";
        String key = searchbox.getText();

        switch(typeno){
            case 0:type="";
            break;

            case 1:type="custID";
            break;

            case 2:type="fname";
            break;
            case 3:type="lname";
            break;
            case 4:type="city";
            break;
        }

        rs = c.customersearch(type, key);

        jTable2.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int typeno = jComboBox4.getSelectedIndex();
        String type = "";
        String key = searchbox2.getText();

        switch(typeno){
            case 0:type="";
            break;

            case 1:type="BookID";
            break;

            case 2:type="RoomNo";
            break;

            case 3:type="ReservedFrom";
            break;

            case 4:type="ReservedTo";
            break;

            case 5:type="PayStatus";
            break;

            case 6:type="BookStatus";
            break;
        }

        rs=c.Reservationsearch(type, key);

        jTable1.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //update
        String cid = cidbox.getText();
        String Roomno = roomnobox.getText();
        String  price = pricebox.getText();

        //from
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date bdate;
        bdate = bookingfrombox.getDate();
        String Dfrom = df.format(bdate);

        //to
        DateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
        Date bdate2;
        bdate2 = bookingtobox.getDate();
        String Dto = df.format(bdate2);

        String  days = Noofdaysbox.getText();
        String  payment = totpaybox.getText();
        //        String paytype = ptypebox.getSelectedItem().toString();
        //        String total = amountbox.getText();
        //        String pstatus = statusbox.getSelectedItem().toString();
        //        String Bookstatus = bstatusbox.getSelectedItem().toString();

        try {
            String sql ="UPDATE booking set custID=?,RoomNo=?,Price=?,ReservedFrom=?,ReservedTo=?,days=?,Payment=?,PaymentType=?,TotAmountPaid=?,PayStatus=?,BookStatus=? where BookID=?";

            pst = con.prepareStatement(sql);

            pst.setString(1,cid);
            pst.setString(2,Roomno);
            pst.setString(3,price);
            pst.setString(4,Dfrom);
            pst.setString(5,Dto);
            pst.setString(6,days);
            pst.setString(7,payment);
            //            pst.setString(8,paytype );
            //            pst.setString(9,total);
            //            pst.setString(10,pstatus);
            //            pst.setString(11,Bookstatus);

            pst.execute();

            tableload2();

            JOptionPane.showMessageDialog(this,"Successfully Updated","Customer",JOptionPane.INFORMATION_MESSAGE);
            clear();

        } catch (SQLException | HeadlessException e) {
            Logger.getLogger(Cust_reg.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this,"Successfully Updated");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //  delete
        int x=  JOptionPane.showConfirmDialog(null,"Do You want to delete ?","Delete",JOptionPane.YES_NO_OPTION);

        if(x==0){
            String bookid = bidbox.getText();
            String sql="DELETE from booking where BoomID='"+bookid+"'";

            try {
                pst =con.prepareStatement(sql);
                pst.execute();

                //load table
                tableload2();
                JOptionPane.showMessageDialog(this,"Successfully deleted");
                clear();

            } catch (SQLException | HeadlessException e) {
                System.out.println(e);
            }
        }

        //                JOptionPane.showMessageDialog(this,"Successfully cansel","Customer",JOptionPane.INFORMATION_MESSAGE);
        //                String bookid = bidbox.getText();
        //                String sql = "DELETE from booking where bookid=?";
        //                try {
            //                        pst=con.prepareStatement(sql);
            //                        pst.setString(1,bookid);
            //                        pst.execute();
            //
            //                        tableload2();
            //                        JOptionPane.showMessageDialog(this,"Successfully Canceled");
            //                        clear();
            //
            //                    } catch (SQLException | HeadlessException e) {
            //                        System.out.println(e);
            //                    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        //insert
        String cid = cidbox.getText();
        String Roomno = roomnobox.getText();
        String  price = pricebox.getText();

        //from
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date bdate;
        bdate = bookingfrombox.getDate();
        String Dfrom = df.format(bdate);

        //to
        DateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
        Date bdate2;
        bdate2 = bookingtobox.getDate();
        String Dto = df.format(bdate2);

        String  days = Noofdaysbox.getText();
        String  payment = totpaybox.getText();
        //        String paytype = ptypebox.getSelectedItem().toString();
        //        String total = amountbox.getText();
        //  String pstatus = statusbox.getSelectedItem().toString();
        String Bookstatus = statusbox.getSelectedItem().toString();

        try {
            String sql = "INSERT INTO booking (custID,RoomNo,Price,ReservedFrom,ReservedTo,days,Payment,BookStatus) values (?,?,?,?,?,?,?,?)";

            pst = con.prepareStatement(sql);

            // pst.setString(1,ID);
            pst.setString(1,cid);
            pst.setString(2,Roomno);
            pst.setString(3,price);
            pst.setString(4,Dfrom);
            pst.setString(5,Dto);
            pst.setString(6,days);
            pst.setString(7,payment);
            //            pst.setString(8,paytype );
            //            pst.setString(9,total);
            //            pst.setString(10,pstatus);
            pst.setString(8,Bookstatus);

            pst.execute();

            JOptionPane.showMessageDialog(this,"Successfully Recorded");
            tableload2();
            clear();

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this,e);
        }
        try{
            String sql1="UPDATE room set status=? where RoomNo=?";
            pst = con.prepareStatement(sql1);

            // pst.setStrpst.setString(1,"Reserved");
            pst.setString(1,"Reserved");
            pst.setString(2,Roomno);

            pst.execute();
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");

        Date d1 = null;
        Date d2 = null;

        try {
            d1 = sf.parse(sf.format(bookingfrombox.getDate()));
            d2 = sf.parse(sf.format(bookingtobox.getDate()));

        } catch(Exception e){
            e.printStackTrace();
        }

        long diff = d2.getTime() - d1.getTime();

        long sec = diff/ 1000 % 60 ;
        long min = diff/ (60*1000) % 60;
        long hours = diff/ (60*60*1000);
        long days = hours/24;

        Noofdaysbox.setText(Long.toString(days));

        //payment
        String da = Noofdaysbox.getText();
        float x = Float.parseFloat(da);

        String pay = pricebox.getText();
        float y = Float.parseFloat(pay);

        float totPay = x*y;
        String total=Float.toString(totPay);
        totpaybox.setText(total);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jToggleButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseReleased

    }//GEN-LAST:event_jToggleButton1MouseReleased

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        CustomerHome h = new CustomerHome();
        h.setVisible(true);
        h.jDesktopPane1.removeAll();
        Payment pa = new Payment();
        h.jDesktopPane1.add(pa);
        pa.show();
        
        
        
        
        Payment pas = null;
        pas = new Payment();
        pas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int typeno = jComboBox4.getSelectedIndex();
        String type = "";
        String key = searchbox2.getText();

        switch(typeno){
            case 0:type="";
            break;

            case 1:type="BookID";
            break;

            case 2:type="RoomNo";
            break;

            case 3:type="ReservedFrom";
            break;

            case 4:type="ReservedTo";
            break;

            case 5:type="PayStatus";
            break;

            case 6:type="BookStatus";
            break;
        }
        if (key.isEmpty()) {
            try {
                String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\booking.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(rep);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else {
            try {

                JasperDesign jd = JRXmlLoader.load("C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\booking.jrxml");
                String sql = "select * from booking where BookID like '%" + key + "%'";
                JRDesignQuery n1 = new JRDesignQuery();
                n1.setText(sql);
                jd.setQuery(n1);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Noofdaysbox;
    private javax.swing.JLabel bidbox;
    private com.toedter.calendar.JDateChooser bookingfrombox;
    private com.toedter.calendar.JDateChooser bookingtobox;
    private javax.swing.JTextField cidbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel pricebox;
    private javax.swing.JLabel roomnobox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField searchbox2;
    private javax.swing.JComboBox statusbox;
    private javax.swing.JTextField totpaybox;
    // End of variables declaration//GEN-END:variables
}
