/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class Equipment extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Inventory i = new Inventory();
    String p = "1";

    public Equipment() {
        initComponents(); 
        con = dbconnect.connect();

        viewttable(); //tableload
        JTableHeader theader = OrderTable.getTableHeader(); //change table header 
        theader.setFont(new Font("Tahoma", Font.BOLD, 14));
    }

    public void viewttable() {  
        searchbox.setText("");
        try {
            String sql = "SELECT * FROM equipmet";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            OrderTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        qtybox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idbox = new javax.swing.JLabel();
        pricebox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        valuebox = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        brandbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        reject = new javax.swing.JPanel();
        rtext = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        avaliability = new javax.swing.JPanel();
        atext = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        equipment = new javax.swing.JPanel();
        etext = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(1600, 920));
        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        searchbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
        });
        jPanel1.add(searchbox);
        searchbox.setBounds(290, 200, 310, 40);

        qtybox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtybox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyboxKeyPressed(evt);
            }
        });
        jPanel1.add(qtybox);
        qtybox.setBounds(1270, 530, 300, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Equipment Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1080, 450, 135, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Qty");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1080, 550, 28, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total value(Rs) ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1080, 660, 126, 22);

        idbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idbox.setText("           ");
        jPanel1.add(idbox);
        idbox.setBounds(1270, 370, 280, 40);

        pricebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pricebox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                priceboxMouseReleased(evt);
            }
        });
        pricebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceboxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceboxKeyTyped(evt);
            }
        });
        jPanel1.add(pricebox);
        pricebox.setBounds(1270, 580, 300, 40);

        OrderTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        OrderTable.setAutoscrolls(false);
        OrderTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OrderTable.setFillsViewportHeight(true);
        OrderTable.setGridColor(new java.awt.Color(204, 204, 204));
        OrderTable.setRowHeight(30);
        OrderTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        OrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrderTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 270, 1020, 580);

        valuebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valuebox.setText("       ");
        jPanel1.add(valuebox);
        valuebox.setBounds(1270, 640, 280, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Manufacture");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1080, 500, 120, 22);

        namebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        namebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameboxKeyPressed(evt);
            }
        });
        jPanel1.add(namebox);
        namebox.setBounds(1270, 430, 300, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Price rate(Rs)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1080, 600, 106, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Equipment Id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1080, 390, 107, 22);

        brandbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        brandbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandboxActionPerformed(evt);
            }
        });
        brandbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandboxKeyPressed(evt);
            }
        });
        jPanel1.add(brandbox);
        brandbox.setBounds(1270, 480, 300, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/textfield300.png"))); // NOI18N
        jLabel6.setText(" ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1270, 640, 300, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/textfield300.png"))); // NOI18N
        jLabel8.setText(" ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1270, 370, 300, 40);

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/search.png"))); // NOI18N
        search.setText("Search");
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(660, 190, 120, 50);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/delete.png"))); // NOI18N
        delete.setText("Delete");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(1450, 800, 120, 50);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/add.png"))); // NOI18N
        add.setText("Add");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(1080, 800, 120, 50);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/update.png"))); // NOI18N
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(1260, 800, 120, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/print.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(930, 190, 120, 50);

        reject.setBackground(new java.awt.Color(204, 204, 204));
        reject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rejectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rejectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rejectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rejectMouseReleased(evt);
            }
        });
        reject.setLayout(null);

        rtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtext.setText("Rejected Equipments");
        reject.add(rtext);
        rtext.setBounds(80, 20, 170, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/avialibility.png"))); // NOI18N
        jLabel16.setText(" ");
        reject.add(jLabel16);
        jLabel16.setBounds(10, 0, 64, 64);

        jPanel1.add(reject);
        reject.setBounds(630, 40, 250, 70);

        avaliability.setBackground(new java.awt.Color(204, 204, 204));
        avaliability.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avaliability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        avaliability.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avaliabilityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avaliabilityMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                avaliabilityMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                avaliabilityMouseReleased(evt);
            }
        });
        avaliability.setLayout(null);

        atext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        atext.setText("Avaliability");
        avaliability.add(atext);
        atext.setBounds(80, 20, 140, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/avialibility.png"))); // NOI18N
        jLabel15.setText(" ");
        avaliability.add(jLabel15);
        jLabel15.setBounds(10, 0, 64, 64);

        jPanel1.add(avaliability);
        avaliability.setBounds(330, 40, 250, 70);

        equipment.setBackground(new java.awt.Color(204, 204, 204));
        equipment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        equipment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equipmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equipmentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                equipmentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                equipmentMouseReleased(evt);
            }
        });
        equipment.setLayout(null);

        etext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etext.setText("Equipment Stock");
        equipment.add(etext);
        etext.setBounds(80, 20, 140, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/fstock.png"))); // NOI18N
        jLabel14.setText(" ");
        equipment.add(jLabel14);
        jLabel14.setBounds(10, 0, 64, 64);

        jPanel1.add(equipment);
        equipment.setBounds(30, 40, 250, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/body.jpg"))); // NOI18N
        jLabel9.setText(" ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1600, 890);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1600, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //mouse click event search
            String search = searchbox.getText();
            try {
                String sql4 = "SELECT * FROM equipmet WHERE EquipmentName like '%" + search + "%' ";
                pst = con.prepareStatement(sql4);
                rs = pst.executeQuery();
                OrderTable.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_searchboxKeyPressed

    private void qtyboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyboxKeyPressed
        int key = evt.getKeyCode(); // qty validation
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACK_SPACE || key == KeyEvent.VK_ENTER) {
            qtybox.setEditable(true);
            qtybox.setBackground(Color.white);
        } else {
            getToolkit().beep();
            qtybox.setEditable(false);
            qtybox.setBackground(Color.LIGHT_GRAY);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pricebox.requestFocusInWindow();
        }
    }//GEN-LAST:event_qtyboxKeyPressed

    private void priceboxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceboxMouseReleased

    }//GEN-LAST:event_priceboxMouseReleased

    private void priceboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceboxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { // calculate total
            String qty = qtybox.getText();
            String rate = pricebox.getText();
            float no1 = Float.parseFloat(qty);
            float no2 = Float.parseFloat(rate);
            float result = no1 * no2;
            String value = Float.toString(result);
            valuebox.setText(value);
        }
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACK_SPACE || key == KeyEvent.VK_PERIOD || key == KeyEvent.VK_ENTER) {
            pricebox.setEditable(true);
            pricebox.setBackground(Color.white);
        } else {
            getToolkit().beep();
            pricebox.setEditable(false);
            pricebox.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_priceboxKeyPressed

    private void priceboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceboxKeyTyped

    }//GEN-LAST:event_priceboxKeyTyped

    private void OrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTableMouseClicked
        //table mouse click
        int row = OrderTable.getSelectedRow();

        String itemid = OrderTable.getValueAt(row, 0).toString();
        String itemname = OrderTable.getValueAt(row, 1).toString();
        String brand = OrderTable.getValueAt(row, 2).toString();
        String qty = OrderTable.getValueAt(row, 3).toString();
        String rate = OrderTable.getValueAt(row, 4).toString();
        String total = OrderTable.getValueAt(row, 5).toString();

        idbox.setText(itemid);
        namebox.setText(itemname);
        brandbox.setText(brand);
        qtybox.setText(qty);
        pricebox.setText(rate);
        valuebox.setText(total);
    }//GEN-LAST:event_OrderTableMouseClicked

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed

    private void nameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameboxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            brandbox.requestFocusInWindow();
        }
    }//GEN-LAST:event_nameboxKeyPressed

    private void brandboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandboxActionPerformed

    private void brandboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandboxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            qtybox.requestFocusInWindow();
        }
    }//GEN-LAST:event_brandboxKeyPressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String search = searchbox.getText();
        rs=i.searchequipment(search);
        OrderTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String eqid = idbox.getText(); // delete button
        if (eqid.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select equipment");
        } else {
            int x = JOptionPane.showConfirmDialog(null, "Do You really want to deelte");
            if (x == 0) {
                i.deleteequipment(eqid);
                idbox.setText("");
                namebox.setText("");
                qtybox.setText("");
                brandbox.setText("");
                pricebox.setText("");
                valuebox.setText("");

                viewttable();
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String eqid = idbox.getText();  //add button
        String eqname = namebox.getText();
        String brand = brandbox.getText();
        String qty = qtybox.getText();
        String rate = pricebox.getText();
        String senddate = showDate();
        if (eqname.isEmpty() || brand.isEmpty() || qty.isEmpty() || rate.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill details");
        } else {
            float no1 = Float.parseFloat(qty);
            float no2 = Float.parseFloat(rate);
            float result = no1 * no2;
            String value = Float.toString(result);
            valuebox.setText(value);
            int x = JOptionPane.showConfirmDialog(null, "Do You really want confirm");
            if (x == 0) {
                i.addequipment(eqname, brand, qty, rate, value, senddate);
                idbox.setText("");
                namebox.setText("");
                qtybox.setText("");
                brandbox.setText("");
                pricebox.setText("");
                valuebox.setText("");

                viewttable();
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String eqid = idbox.getText(); //update button
        String eqname = namebox.getText();
        String brand = brandbox.getText();
        String qty = qtybox.getText();
        String rate = pricebox.getText();
        if (eqname.isEmpty() || brand.isEmpty() || qty.isEmpty() || rate.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select equipment");
        } else {
            float no1 = Float.parseFloat(qty);
            float no2 = Float.parseFloat(rate);
            float result = no1 * no2;
            String value = Float.toString(result);
            valuebox.setText(value);
            int x = JOptionPane.showConfirmDialog(null, "Do You really want to update");
            if (x == 0) {
                i.updateequipment(eqid, eqname, brand, qty, rate, value, rate);
                idbox.setText("");
                namebox.setText("");
                qtybox.setText("");
                brandbox.setText("");
                pricebox.setText("");
                valuebox.setText("");

                viewttable();
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void equipmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentMouseEntered
        equipment.setBackground(new Color(51, 51, 51));
        etext.setForeground(Color.white);
    }//GEN-LAST:event_equipmentMouseEntered

    private void equipmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentMouseExited
        equipment.setBackground(new Color(204, 204, 204));
        etext.setForeground(Color.BLACK);
    }//GEN-LAST:event_equipmentMouseExited

    private void equipmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentMousePressed
        equipment.setBackground(new Color(255, 255, 255));
        etext.setForeground(Color.BLACK);
    }//GEN-LAST:event_equipmentMousePressed

    private void equipmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentMouseReleased
        p="1";
        viewttable();
        equipment.setBackground(new Color(204, 204, 204));
        etext.setForeground(Color.BLACK);
    }//GEN-LAST:event_equipmentMouseReleased

    private void avaliabilityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliabilityMouseEntered
        avaliability.setBackground(new Color(51, 51, 51));
        atext.setForeground(Color.white);
    }//GEN-LAST:event_avaliabilityMouseEntered

    private void avaliabilityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliabilityMouseExited
        avaliability.setBackground(new Color(204, 204, 204));
        atext.setForeground(Color.BLACK);
    }//GEN-LAST:event_avaliabilityMouseExited

    private void avaliabilityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliabilityMousePressed
        avaliability.setBackground(new Color(255, 255, 255));
        atext.setForeground(Color.BLACK);
    }//GEN-LAST:event_avaliabilityMousePressed

    private void avaliabilityMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliabilityMouseReleased
        p="1";
        try {
            String sql = "SELECT EquipmentId,EquipmentName,Manufacture,Qty FROM equipmet order by Qty";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            OrderTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
        avaliability.setBackground(new Color(204, 204, 204));
        atext.setForeground(Color.BLACK);
    }//GEN-LAST:event_avaliabilityMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (p.equals("1")) {
            String name = searchbox.getText();
            if (name.isEmpty()) {
                try {
                    String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\equipment.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(rep);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                    JasperViewer.viewReport(jp);
                } catch (JRException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            } else {
                try {

                    JasperDesign jd = JRXmlLoader.load("C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\equipment.jrxml");
                    String sql = "select * from equipmet where EquipmentName like '%" + name + "%'";
                    JRDesignQuery n1 = new JRDesignQuery();
                    n1.setText(sql);
                    jd.setQuery(n1);
                    JasperReport jr = JasperCompileManager.compileReport(jd);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                    JasperViewer.viewReport(jp);
                } catch (JRException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        } 
        else {
            try {
                    String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\reject.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(rep);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                    JasperViewer.viewReport(jp);
                } catch (JRException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rejectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectMouseEntered
        reject.setBackground(new Color(51, 51, 51));
        rtext.setForeground(Color.white);
    }//GEN-LAST:event_rejectMouseEntered

    private void rejectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectMouseExited
        reject.setBackground(new Color(204, 204, 204));
        rtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_rejectMouseExited

    private void rejectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectMousePressed
        reject.setBackground(new Color(255, 255, 255));
        rtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_rejectMousePressed

    private void rejectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectMouseReleased
        p="2";
        try {
            String sql = "SELECT * FROM rejectequipment order by Date";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            OrderTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
        reject.setBackground(new Color(204, 204, 204));
        rtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_rejectMouseReleased
    String showDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        return (s.format(d));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton add;
    private javax.swing.JLabel atext;
    private javax.swing.JPanel avaliability;
    private javax.swing.JTextField brandbox;
    private javax.swing.JButton delete;
    private javax.swing.JPanel equipment;
    private javax.swing.JLabel etext;
    private javax.swing.JLabel idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField pricebox;
    private javax.swing.JTextField qtybox;
    private javax.swing.JPanel reject;
    private javax.swing.JLabel rtext;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton update;
    private javax.swing.JLabel valuebox;
    // End of variables declaration//GEN-END:variables
}
