/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event;

import dbconnect.dbconnect;
import java.awt.Color;
import static java.awt.PageAttributes.MediaType.B1;
import static java.awt.PageAttributes.MediaType.B3;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP™
 */
public class Manage_Services extends javax.swing.JInternalFrame {
PreparedStatement pst=null;
     Connection conn=null;
      ResultSet table=null;
       EventClass ac=new EventClass(dbconnect.connect()); 
       
       
       
    /**
     * Creates new form Manage_Services
     */
    public Manage_Services() {
        initComponents();
        conn=dbconnect.connect();
         ac.JpanelColor(this.OFFER);
         ac.getDeco(decoSelect);
         ac.getDeco(Item);
         addVehicleCombo();
    }
    public void tableLoad(String sq)
      {  
         
         try{
            
            pst =conn.prepareStatement(sq);
            table=pst.executeQuery();
           tableMix.setModel(DbUtils.resultSetToTableModel(table));
         }catch(Exception e){
            System.out.println(e);
         }
      }
    ////////////////////
    public void addVehicleCombo(){
        try
        {
            String Sql = "SELECT  Wedd_Car FROM wedd_car_detail ";
            this.pst= (com.mysql.jdbc.PreparedStatement) this.conn.prepareStatement(Sql);
            table=pst.executeQuery();
            while(table.next())
            {
               availableVehicles.addItem(table.getString("Wedd_Car"));
            }
        }
        catch(Exception e){
            System.out.println("Combo Box Loading Error : "+e);
        }
    }
    
    public String selectValues(String v1,String v2){
      
        String B8=null ;
          try{
        if((v1!= null && v2 == null)||(v2!= null && v1== null)){
        B8=v1;
        }else if((v1== null && v2 != null)||(v2== null && v1!= null)){
          B8=v2;
    }else{
         JOptionPane.showMessageDialog(null, "You can choose only one Option at once");
             B8="no choice";
         }
        }catch(Exception e){
            System.out.println(e);
        }
       
     return B8;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        CP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        OFFER = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        PHOTO = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DECO = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FXP = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        VEHI = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        base = new javax.swing.JPanel();
        cusMenu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Cricename = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Rprice = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Cprice = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Ccurryname = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Sprice = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Csaladname = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        DEprice = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Cdessertname = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        DRprice = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Cdrinkname = new javax.swing.JTextField();
        CMenu_Add = new javax.swing.JButton();
        CUS_delete = new javax.swing.JButton();
        CUS_update = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        decoration = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Did = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Dprice = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        Dname = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        DECO_delete = new javax.swing.JButton();
        DECO_Add = new javax.swing.JButton();
        DECO_reset = new javax.swing.JButton();
        vehicle = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        availableVehicles = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        assignCost = new javax.swing.JTextField();
        AddCOST = new javax.swing.JButton();
        photographer = new javax.swing.JPanel();
        fixedpackages = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Fpackagename = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Fricename = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Fcurryname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Fsaladname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Fdessertname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Fdrinkname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Fprice = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        packageID = new javax.swing.JLabel();
        decoSelect = new javax.swing.JComboBox<>();
        front = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        OfferTypeCombo = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        Offer_ITEM_TypeCombo = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        Item = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        StartDate = new com.toedter.calendar.JDateChooser();
        jLabel38 = new javax.swing.JLabel();
        EndDate = new com.toedter.calendar.JDateChooser();
        jLabel39 = new javax.swing.JLabel();
        addOFFERS = new javax.swing.JButton();
        UpdateOFFER = new javax.swing.JButton();
        deleteOFFER = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMix = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 920));
        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        CP.setBackground(new java.awt.Color(0, 0, 0));
        CP.setForeground(new java.awt.Color(255, 255, 255));
        CP.setMaximumSize(new java.awt.Dimension(200, 120));
        CP.setMinimumSize(new java.awt.Dimension(200, 120));
        CP.setPreferredSize(new java.awt.Dimension(200, 120));
        CP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CPMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customized Packages");

        javax.swing.GroupLayout CPLayout = new javax.swing.GroupLayout(CP);
        CP.setLayout(CPLayout);
        CPLayout.setHorizontalGroup(
            CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        CPLayout.setVerticalGroup(
            CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CPLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        OFFER.setBackground(new java.awt.Color(0, 0, 0));
        OFFER.setForeground(new java.awt.Color(255, 255, 255));
        OFFER.setMaximumSize(new java.awt.Dimension(200, 120));
        OFFER.setMinimumSize(new java.awt.Dimension(200, 120));
        OFFER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OFFERMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OFFERMousePressed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Offers");

        javax.swing.GroupLayout OFFERLayout = new javax.swing.GroupLayout(OFFER);
        OFFER.setLayout(OFFERLayout);
        OFFERLayout.setHorizontalGroup(
            OFFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OFFERLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OFFERLayout.setVerticalGroup(
            OFFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OFFERLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(45, 45, 45))
        );

        PHOTO.setBackground(new java.awt.Color(0, 0, 0));
        PHOTO.setForeground(new java.awt.Color(255, 255, 255));
        PHOTO.setMaximumSize(new java.awt.Dimension(200, 120));
        PHOTO.setMinimumSize(new java.awt.Dimension(200, 120));
        PHOTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHOTOMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PHOTOMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PHOTOLayout = new javax.swing.GroupLayout(PHOTO);
        PHOTO.setLayout(PHOTOLayout);
        PHOTOLayout.setHorizontalGroup(
            PHOTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHOTOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PHOTOLayout.setVerticalGroup(
            PHOTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHOTOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(45, 45, 45))
        );

        DECO.setBackground(new java.awt.Color(0, 0, 0));
        DECO.setForeground(new java.awt.Color(255, 255, 255));
        DECO.setMaximumSize(new java.awt.Dimension(200, 120));
        DECO.setMinimumSize(new java.awt.Dimension(200, 120));
        DECO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DECOMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DECOMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Decorations");

        javax.swing.GroupLayout DECOLayout = new javax.swing.GroupLayout(DECO);
        DECO.setLayout(DECOLayout);
        DECOLayout.setHorizontalGroup(
            DECOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DECOLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DECOLayout.setVerticalGroup(
            DECOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DECOLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FXP.setBackground(new java.awt.Color(0, 0, 0));
        FXP.setForeground(new java.awt.Color(255, 255, 255));
        FXP.setMaximumSize(new java.awt.Dimension(200, 120));
        FXP.setMinimumSize(new java.awt.Dimension(200, 120));
        FXP.setPreferredSize(new java.awt.Dimension(200, 120));
        FXP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FXPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FXPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FXPMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fixed Packages");

        javax.swing.GroupLayout FXPLayout = new javax.swing.GroupLayout(FXP);
        FXP.setLayout(FXPLayout);
        FXPLayout.setHorizontalGroup(
            FXPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FXPLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        FXPLayout.setVerticalGroup(
            FXPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FXPLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        VEHI.setBackground(new java.awt.Color(0, 0, 0));
        VEHI.setForeground(new java.awt.Color(255, 255, 255));
        VEHI.setMaximumSize(new java.awt.Dimension(200, 120));
        VEHI.setMinimumSize(new java.awt.Dimension(200, 120));
        VEHI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VEHIMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VEHIMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   Vehicle");

        javax.swing.GroupLayout VEHILayout = new javax.swing.GroupLayout(VEHI);
        VEHI.setLayout(VEHILayout);
        VEHILayout.setHorizontalGroup(
            VEHILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VEHILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VEHILayout.setVerticalGroup(
            VEHILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VEHILayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(OFFER, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(FXP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DECO, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VEHI, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PHOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2366, 2366, 2366))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OFFER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PHOTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DECO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FXP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VEHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3530, 120));

        background.setMinimumSize(new java.awt.Dimension(1600, 890));
        background.setPreferredSize(new java.awt.Dimension(1600, 890));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base.setLayout(new java.awt.CardLayout());

        cusMenu.setBackground(new java.awt.Color(255, 255, 255));
        cusMenu.setMinimumSize(new java.awt.Dimension(1480, 400));
        cusMenu.setPreferredSize(new java.awt.Dimension(1480, 400));
        cusMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("cus menu");
        cusMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Rice Name");
        cusMenu.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 153, -1, -1));

        Cricename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Cricename, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 194, 180, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Rice Price");
        cusMenu.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 252, -1, -1));

        Rprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Rprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 287, 180, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Curry  Price");
        cusMenu.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 252, -1, -1));

        Cprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Cprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 287, 170, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Curry Name");
        cusMenu.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 153, -1, -1));

        Ccurryname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Ccurryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 194, 170, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Salad  Price");
        cusMenu.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 252, -1, -1));

        Sprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Sprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 287, 170, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Salad  Name");
        cusMenu.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 153, -1, -1));

        Csaladname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Csaladname, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 194, 170, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Dessert  Price");
        cusMenu.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 252, -1, -1));

        DEprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(DEprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 287, 170, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Dessert  Name");
        cusMenu.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 153, -1, -1));

        Cdessertname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Cdessertname, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 194, 170, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Drink Price");
        cusMenu.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 252, -1, -1));

        DRprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(DRprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 287, 170, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Drink  Name");
        cusMenu.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        Cdrinkname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusMenu.add(Cdrinkname, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 194, 170, 30));

        CMenu_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMenu_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/add-button-inside-black-circle.png"))); // NOI18N
        CMenu_Add.setText("ADD");
        CMenu_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMenu_AddActionPerformed(evt);
            }
        });
        cusMenu.add(CMenu_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 230, 40));

        CUS_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CUS_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/throw-to-paper-bin.png"))); // NOI18N
        CUS_delete.setText("DELETE");
        CUS_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUS_deleteActionPerformed(evt);
            }
        });
        cusMenu.add(CUS_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, 230, 40));

        CUS_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CUS_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/management (2).png"))); // NOI18N
        CUS_update.setText("UPDATE");
        CUS_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUS_updateActionPerformed(evt);
            }
        });
        cusMenu.add(CUS_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 230, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/three-circling-arrows.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        cusMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1079, 277, 230, 40));

        base.add(cusMenu, "card4");

        decoration.setBackground(new java.awt.Color(255, 255, 255));
        decoration.setMinimumSize(new java.awt.Dimension(1480, 400));
        decoration.setPreferredSize(new java.awt.Dimension(1480, 400));
        decoration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("decoration");
        decoration.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Item ID");
        decoration.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        Did.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decoration.add(Did, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 280, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Item Price");
        decoration.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        Dprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpriceActionPerformed(evt);
            }
        });
        decoration.add(Dprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 290, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Item Name");
        decoration.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        Dname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decoration.add(Dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 280, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/management (2).png"))); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        decoration.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 210, 40));

        DECO_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DECO_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/throw-to-paper-bin.png"))); // NOI18N
        DECO_delete.setText("DELETE");
        DECO_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DECO_deleteActionPerformed(evt);
            }
        });
        decoration.add(DECO_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 210, 40));

        DECO_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DECO_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/add-button-inside-black-circle.png"))); // NOI18N
        DECO_Add.setText("ADD");
        DECO_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DECO_AddActionPerformed(evt);
            }
        });
        decoration.add(DECO_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 210, 40));

        DECO_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DECO_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/three-circling-arrows.png"))); // NOI18N
        DECO_reset.setText("Clear");
        DECO_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DECO_resetActionPerformed(evt);
            }
        });
        decoration.add(DECO_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 210, 40));

        base.add(decoration, "card5");

        vehicle.setBackground(new java.awt.Color(255, 255, 255));
        vehicle.setMinimumSize(new java.awt.Dimension(1480, 400));
        vehicle.setPreferredSize(new java.awt.Dimension(1480, 400));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("vehicle");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Available Vehicles");

        availableVehicles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Assign Cost");

        assignCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        AddCOST.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddCOST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/add-button-inside-black-circle.png"))); // NOI18N
        AddCOST.setText("Add Cost");
        AddCOST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCOSTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicleLayout = new javax.swing.GroupLayout(vehicle);
        vehicle.setLayout(vehicleLayout);
        vehicleLayout.setHorizontalGroup(
            vehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleLayout.createSequentialGroup()
                .addGroup(vehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(vehicleLayout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addGroup(vehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assignCost, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddCOST, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(availableVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))))
                .addContainerGap(805, Short.MAX_VALUE))
        );
        vehicleLayout.setVerticalGroup(
            vehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(availableVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignCost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(AddCOST, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        base.add(vehicle, "card6");

        photographer.setBackground(new java.awt.Color(255, 255, 255));
        photographer.setMinimumSize(new java.awt.Dimension(1480, 400));
        photographer.setPreferredSize(new java.awt.Dimension(1480, 400));

        javax.swing.GroupLayout photographerLayout = new javax.swing.GroupLayout(photographer);
        photographer.setLayout(photographerLayout);
        photographerLayout.setHorizontalGroup(
            photographerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1480, Short.MAX_VALUE)
        );
        photographerLayout.setVerticalGroup(
            photographerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        base.add(photographer, "card7");

        fixedpackages.setBackground(new java.awt.Color(255, 255, 255));
        fixedpackages.setMinimumSize(new java.awt.Dimension(1480, 400));
        fixedpackages.setPreferredSize(new java.awt.Dimension(1480, 400));
        fixedpackages.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("fixed packages");
        fixedpackages.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Package Name");
        fixedpackages.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 87, 24));

        Fpackagename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fixedpackages.add(Fpackagename, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 280, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Rice Name");
        fixedpackages.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 20));

        Fricename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fixedpackages.add(Fricename, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 280, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Curry Name");
        fixedpackages.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));

        Fcurryname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fixedpackages.add(Fcurryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 280, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Salad Name");
        fixedpackages.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, 20));

        Fsaladname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fixedpackages.add(Fsaladname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 280, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Dessert Name");
        fixedpackages.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        Fdessertname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fdessertname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FdessertnameActionPerformed(evt);
            }
        });
        fixedpackages.add(Fdessertname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 280, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Drinks");
        fixedpackages.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 70, 20));

        Fdrinkname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fdrinkname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FdrinknameActionPerformed(evt);
            }
        });
        fixedpackages.add(Fdrinkname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 250, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Price (Per Person)");
        fixedpackages.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        Fprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FpriceActionPerformed(evt);
            }
        });
        fixedpackages.add(Fprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 250, 40));

        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/add-button-inside-black-circle.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        fixedpackages.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 210, 40));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/management (2).png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        fixedpackages.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 210, 40));

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/throw-to-paper-bin.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        fixedpackages.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 210, 40));

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/three-circling-arrows.png"))); // NOI18N
        reset.setText("Clear");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        fixedpackages.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 270, 210, 40));

        packageID.setText("Package id");
        fixedpackages.add(packageID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        decoSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------Item--------" }));
        decoSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decoSelectActionPerformed(evt);
            }
        });
        fixedpackages.add(decoSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 280, 30));

        base.add(fixedpackages, "card3");

        front.setBackground(new java.awt.Color(255, 255, 255));
        front.setMinimumSize(new java.awt.Dimension(1480, 400));
        front.setPreferredSize(new java.awt.Dimension(1480, 400));
        front.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        front.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 20));

        jLabel13.setText("promotions");
        front.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("Offer  Type");
        front.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 130, -1));

        OfferTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------Type------------------", "Price Based", "GuestCount  Based", "Month Based" }));
        front.add(OfferTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, 30));

        jLabel35.setText("Offer  Item Type");
        front.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 110, 20));

        Offer_ITEM_TypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Type----------", "Deco Item", "Discount" }));
        front.add(Offer_ITEM_TypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 30));

        jLabel36.setText("Item");
        front.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        front.add(Item, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 240, 30));
        front.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 240, 10));
        front.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 240, 10));
        front.add(StartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 250, 30));

        jLabel38.setText("Start Date");
        front.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 70, 20));
        front.add(EndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 260, 30));

        jLabel39.setText("End Date");
        front.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 80, 20));

        addOFFERS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addOFFERS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/add-button-inside-black-circle.png"))); // NOI18N
        addOFFERS.setText("ADD");
        addOFFERS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOFFERSActionPerformed(evt);
            }
        });
        front.add(addOFFERS, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, 230, 40));

        UpdateOFFER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateOFFER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/management (2).png"))); // NOI18N
        UpdateOFFER.setText("UPDATE");
        UpdateOFFER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateOFFERActionPerformed(evt);
            }
        });
        front.add(UpdateOFFER, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 230, 40));

        deleteOFFER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteOFFER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/throw-to-paper-bin.png"))); // NOI18N
        deleteOFFER.setText("DELETE");
        deleteOFFER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOFFERActionPerformed(evt);
            }
        });
        front.add(deleteOFFER, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 230, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/three-circling-arrows.png"))); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        front.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 230, 40));

        jLabel40.setText("Offering Value");
        front.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, 20));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/eye.png"))); // NOI18N
        jButton7.setText("View Table");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        front.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 230, 40));

        base.add(front, "card2");

        background.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 1350, 420));

        tableMix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMixMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMix);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 1350, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/body.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1600, 890));
        jLabel2.setMinimumSize(new java.awt.Dimension(1600, 890));
        jLabel2.setPreferredSize(new java.awt.Dimension(1600, 890));
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 890));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1126));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FXPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FXPMouseClicked
        // TODO add your handling code here:
         cusMenu.setVisible(false);
        decoration.setVisible(false);
        front.setVisible(false);
        vehicle.setVisible(false);
        photographer.setVisible(false); 
        fixedpackages.setVisible(true);
        
        //table load
        String sq="SELECT * FROM fixed_package";
        tableLoad(sq);
        
        
        
    }//GEN-LAST:event_FXPMouseClicked

    private void CPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPMouseClicked
        // TODO add your handling code here:
        fixedpackages.setVisible(false);
        cusMenu.setVisible(true);
        decoration.setVisible(false);
        front.setVisible(false);
        vehicle.setVisible(false);
        photographer.setVisible(false); 
        
         //table load
        String sq="SELECT * FROM cus_menu";
        tableLoad(sq);
    }//GEN-LAST:event_CPMouseClicked

    private void DECOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DECOMouseClicked
        // TODO add your handling code here:
         fixedpackages.setVisible(false);
        cusMenu.setVisible(false);
        decoration.setVisible(true);
        front.setVisible(false);
        vehicle.setVisible(false);
        photographer.setVisible(false); 
        
         //table load
        String sq="SELECT * FROM decoration";
        tableLoad(sq);
    }//GEN-LAST:event_DECOMouseClicked

    private void VEHIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VEHIMouseClicked
        // TODO add your handling code here:
        fixedpackages.setVisible(false);
        cusMenu.setVisible(false);
        decoration.setVisible(false);
        front.setVisible(false);
        vehicle.setVisible(true);
        photographer.setVisible(false); 
    }//GEN-LAST:event_VEHIMouseClicked

    private void PHOTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHOTOMouseClicked
        // TODO add your handling code here:
          fixedpackages.setVisible(false);
        cusMenu.setVisible(false);
        decoration.setVisible(false);
        front.setVisible(false);
        vehicle.setVisible(false);
        photographer.setVisible(true); 
           
    }//GEN-LAST:event_PHOTOMouseClicked

    private void FXPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FXPMousePressed
        // TODO add your handling code here:
        FXP.setBackground(new Color(102,102,102));
         CP.setBackground(Color.BLACK);
          DECO.setBackground(Color.BLACK);
           VEHI.setBackground(Color.BLACK);
            PHOTO.setBackground(Color.BLACK);
            OFFER.setBackground(Color.BLACK);
    }//GEN-LAST:event_FXPMousePressed

    private void CPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPMousePressed
        // TODO add your handling code here:
        CP.setBackground(new Color(102,102,102));
          FXP.setBackground(Color.BLACK);
           DECO.setBackground(Color.BLACK);
            VEHI.setBackground(Color.BLACK);
             PHOTO.setBackground(Color.BLACK);
             OFFER.setBackground(Color.BLACK);
    }//GEN-LAST:event_CPMousePressed

    private void DECOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DECOMousePressed
        // TODO add your handling code here:
        DECO.setBackground(new Color(102,102,102));
         CP.setBackground(Color.BLACK);
          FXP.setBackground(Color.BLACK);
           VEHI.setBackground(Color.BLACK);
            PHOTO.setBackground(Color.BLACK);
            OFFER.setBackground(Color.BLACK);
    }//GEN-LAST:event_DECOMousePressed

    private void VEHIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VEHIMousePressed
        // TODO add your handling code here:
        VEHI.setBackground(new Color(102,102,102));
         DECO.setBackground(Color.BLACK);
          FXP.setBackground(Color.BLACK);
           CP.setBackground(Color.BLACK);
            PHOTO.setBackground(Color.BLACK);
            OFFER.setBackground(Color.BLACK);
    }//GEN-LAST:event_VEHIMousePressed

    private void PHOTOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHOTOMousePressed
        // TODO add your handling code here:
        PHOTO.setBackground(new Color(102,102,102));
         VEHI.setBackground(Color.BLACK);
          FXP.setBackground(Color.BLACK);
           CP.setBackground(Color.BLACK);
            DECO.setBackground(Color.BLACK);
            OFFER.setBackground(Color.BLACK);
    }//GEN-LAST:event_PHOTOMousePressed

    private void FXPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FXPMouseExited
        // TODO add your handling code here:
      //   FXP.setBackground(Color.BLACK);
        
    }//GEN-LAST:event_FXPMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Update?");
        if(x==0){
       int row=tableMix.getSelectedRow();
       String no=tableMix.getModel().getValueAt(row, 0).toString();     
       String B1 = this. Fpackagename.getText();
       String B2 = this. Fricename.getText();
       String B3 = this.Fcurryname.getText();
       String B4 = this. Fsaladname.getText();
       String B5 = this. Fdessertname.getText();
       String B6 = this. Fdrinkname.getText();
       String B7 = this. Fprice.getText();
       
       
        String q ="UPDATE fixed_package SET Package_Name='"+B1+"',Rice='"+B2+"',Curry='"+B3+"',Salad='"+B4+"',Dessert='"+B5+"',Drink='"+B6+"',PricePer_Person="+B7+" WHERE Package_ID="+no+"";
        
         if(ac.UpdateTable(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Updating Sucess");
           
        }
       
        else
        {
            JOptionPane.showMessageDialog(null, "Data Updating Failed");
        }
      // tableLoad(q);
        }
          

    }//GEN-LAST:event_updateActionPerformed
    private void DECO_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DECO_resetActionPerformed
        // TODO add your handling code here:
            Did.setText(null);
            Dname.setText(null);
            Dprice.setText(null);
    }//GEN-LAST:event_DECO_resetActionPerformed

    private void tableMixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMixMouseClicked
        // TODO add your handling code here:
        //fixed packages
         try {
             
             int row=tableMix.getSelectedRow();
             String no=tableMix.getModel().getValueAt(row, 0).toString();
             String b="SELECT * FROM fixed_package where Package_ID="+no+"";
             pst=conn.prepareStatement(b);
             table=pst.executeQuery();
             if(table.next())
             {
              packageID.setText(no);
              Fpackagename.setText(table.getString("Package_Name"));
              Fricename.setText(table.getString("Rice"));
              Fcurryname.setText(table.getString("Curry"));
              Fsaladname.setText(table.getString("Salad"));
              Fdessertname.setText(table.getString("Dessert"));
              Fdrinkname.setText(table.getString("Drink"));
              Fprice.setText(table.getString("PricePer_Person"));
             }
         } catch (SQLException ex) {
            System.out.println(ex);
         }
         
         //Cuctomized Package
         
         try {
             
             int row=tableMix.getSelectedRow();
             String no=tableMix.getModel().getValueAt(row, 0).toString();
             String b="SELECT * FROM cus_menu WHERE Entry_ID="+no+"";
             pst=conn.prepareStatement(b);
             table=pst.executeQuery();
             if(table.next())
             {
           // Rprice.setText(no);
            Cricename.setText(table.getString("C_Rice"));
            Rprice.setText(table.getString("Rice_Price"));
            Ccurryname.setText(table.getString("C_Curry"));
            Cprice.setText(table.getString("Curry_Price"));
             Csaladname.setText(table.getString("C_Salad"));
              Sprice.setText(table.getString("Salad_Price"));
              Cdessertname.setText(table.getString("C_Dessert"));
              DEprice.setText(table.getString("Dessert_Price"));
             Cdrinkname.setText(table.getString("C_Drink"));
              DRprice.setText(table.getString("Drink_Price"));
             }
         } catch (SQLException ex) {
            System.out.println(ex);
         }
         
         //decoration
          try {
             
             int row=tableMix.getSelectedRow();
             String no=tableMix.getModel().getValueAt(row, 0).toString();
             String b="SELECT * FROM decoration where Item_ID='"+no+"'";
             pst=conn.prepareStatement(b);
             table=pst.executeQuery();
             if(table.next())
             {
           // Rprice.setText(no);
            Did.setText(table.getString("Item_ID"));
            Dname.setText(table.getString("Item_Name"));
            Dprice.setText(table.getString("Price"));
             
             }
         } catch (SQLException ex) {
            System.out.println(ex);
         }
          
          //OFFERS
           try {
             
             int row=tableMix.getSelectedRow();
             String no=tableMix.getModel().getValueAt(row, 0).toString();
             String b="SELECT *FROM offers where Offer_ID="+no+"";
             pst=conn.prepareStatement(b);
             table=pst.executeQuery();
             if(table.next())
             {
             // packageID.setText(no);
             OfferTypeCombo.setSelectedItem(table.getString("Offer_Type"));
             Offer_ITEM_TypeCombo.setSelectedItem(table.getString("Offer_ItemType"));
           Item.setSelectedItem(table.getString("Offering_Value"));
             
                 String date=table.getString("Starting_Date");
                Date edate=new SimpleDateFormat("yyyy-MM-dd").parse((String) date);
               StartDate.setDate(edate);
               
                String Edate=table.getString("Ending_Date");
                Date edate1=new SimpleDateFormat("yyyy-MM-dd").parse((String) Edate);
                EndDate.setDate(edate1);

             /*
                String Sdate=table.getString("Starting_Date");
                ((JTextField)StartDate.getDateEditor().getUiComponent()).setText(Sdate);
                
                String Edate=table.getString("Ending_Date");
                ((JTextField)EndDate.getDateEditor().getUiComponent()).setText(Edate);
              */
             }
         } catch (SQLException ex) {
            System.out.println(ex);
         } catch (ParseException ex) {
        Logger.getLogger(Manage_Services.class.getName()).log(Level.SEVERE, null, ex);
    }
         
    }//GEN-LAST:event_tableMixMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here: EventClass ab= new EventClass(dbconnect.connect());
        
       String B1 = this. Fpackagename.getText();
       String B2 = this. Fricename.getText();
       String B3 = this.Fcurryname.getText();
       String B4 = this. Fsaladname.getText();
       String B5 = this. Fdessertname.getText();
       String B6 = this. Fdrinkname.getText();
       String B7 = this. Fprice.getText();
       
      
        String q =" INSERT INTO fixed_package(Package_Name, Rice, Curry, Salad, Dessert, Drink,PricePer_Person) VALUES ('"+B1+"','"+B2+"','"+B3+"','"+B4+"','"+ B5+"','"+B6+"',"+B7+")";
         tableLoad(q);   
        if(ac.addData(q)==true)
        {      tableLoad(q);
            JOptionPane.showMessageDialog(null, "Data Adding Sucess");
           
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Adding Failed");
        }
        
    tableLoad(q);
        
    }//GEN-LAST:event_addActionPerformed

    private void CMenu_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMenu_AddActionPerformed
        // TODO add your handling code here:
        String B1 = this. Cricename.getText();
       String B2 = this.Rprice.getText();
       String B3 = this. Ccurryname.getText();
       String B4 = this. Cprice.getText();
       String B5 = this.  Csaladname.getText();
       String B6 = this. Sprice.getText();
       String B7 = this.Cdessertname.getText();
       String B8 = this. DEprice.getText();
       String B9 = this.Cdrinkname.getText();
       String B10 = this. DRprice.getText();
       
       
      
        String q ="INSERT INTO cus_menu(C_Rice, Rice_Price, C_Curry, Curry_Price, C_Salad, Salad_Price,C_Dessert,Dessert_Price,C_Drink,Drink_Price) VALUES ('"+B1+"',"+B2+",'"+B3+"',"+B4+",'"+B5+"',"+B6+",'"+B7+"',"+B8+",'"+B9+"',"+B10+")";
            
            
        if(ac.addData(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Adding Sucess");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Adding Failed");
        }
        tableLoad(q);
        
    }//GEN-LAST:event_CMenu_AddActionPerformed

    private void DECO_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DECO_AddActionPerformed
        // TODO add your handling code here:
       String B1 = this.Did.getText();
       String B2 = this.Dname.getText();
       String B3 = this.Dprice.getText();
      
       String q =" INSERT INTO decoration(Item_ID,Item_Name,Price) VALUES ('"+B1+"','"+B2+"',"+B3+")";
            
        if(ac.addData(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Adding Sucess");
           tableLoad(q);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Adding Failed");
        }
        tableLoad(q);
    }//GEN-LAST:event_DECO_AddActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Update?");
        if(x==0){
          String B1 = this.Did.getText();
       String B2 = this.Dname.getText();
       String B3 = this.Dprice.getText();
        
       
        String q ="UPDATE decoration set Item_Name = '"+B2+"',Price= '"+B3+"'  WHERE Item_ID='"+B1+"'";
        
         if(ac.UpdateTable(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Updating Sucess");
           tableLoad(q);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Updating Failed");
        }
       tableLoad(q);
        }  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CUS_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUS_updateActionPerformed
        // TODO add your handling code here:
         int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Update?");
        if(x==0){
       int row=tableMix.getSelectedRow();
       String no=tableMix.getModel().getValueAt(row, 0).toString();     
       String B1 = this. Cricename.getText();
       String B2 = this.Rprice.getText();
       String B3 = this. Ccurryname.getText();
       String B4 = this. Cprice.getText();
       String B5 = this.  Csaladname.getText();
       String B6 = this. Sprice.getText();
       String B7 = this.Cdessertname.getText();
       String B8 = this. DEprice.getText();
       String B9 = this.Cdrinkname.getText();
       String B10 = this. DRprice.getText();
        
       String q ="UPDATE cus_menu SET C_Rice='"+B1+"',Rice_Price="+B2+",C_Curry='"+B3+"',Curry_Price="+B4+",C_Salad='"+B5+"',Salad_Price="+B6+",C_Dessert='"+B7+"',Dessert_Price="+B8+",C_Drink='"+B9+"',Drink_Price="+B10+" WHERE Entry_ID="+no+"";
        
        if(ac.UpdateTable(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Updating Sucess");
           tableLoad(q);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Updating Failed");
        }
       tableLoad(q);
        
    }                                        
        
    }//GEN-LAST:event_CUS_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
       int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Delete?");
       if(x==0){
       int row=tableMix.getSelectedRow();
       String no=tableMix.getModel().getValueAt(row, 0).toString();     
      
       String q ="DELETE FROM fixed_package WHERE Package_ID="+no+"";
        
        if(ac.DeleteValues(q,this.tableMix)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Sucess");
          
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Failed");
        }
        tableLoad(q);
       }                                       
        
    }//GEN-LAST:event_deleteActionPerformed

    private void CUS_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUS_deleteActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Delete?");
       if(x==0){
       int row=tableMix.getSelectedRow();
       String no=tableMix.getModel().getValueAt(row, 0).toString();     
      
       String q ="DELETE FROM cus_menu WHERE Entry_ID="+no+"";
        
        if(ac.DeleteValues(q,this.tableMix)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Sucess");
          
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Failed");
        }
        tableLoad(q);
       }                             
    }//GEN-LAST:event_CUS_deleteActionPerformed

    private void DECO_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DECO_deleteActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Delete?");
       if(x==0){
       int row=tableMix.getSelectedRow();
       String no=tableMix.getModel().getValueAt(row, 0).toString();     
      
       String q ="DELETE FROM decoration WHERE Item_ID='"+no+"'";
        
        if(ac.DeleteValues(q,this.tableMix)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Sucess");
          
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Failed");
        }
        tableLoad(q);
       }                          
    }//GEN-LAST:event_DECO_deleteActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
              packageID.setText(null);
              Fpackagename.setText(null);
              Fricename.setText(null);
              Fcurryname.setText(null);
              Fsaladname.setText(null);
              Fdessertname.setText(null);
              Fdrinkname.setText(null);
              Fprice.setText(null);
    }//GEN-LAST:event_resetActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            Cricename.setText(null);
            Rprice.setText(null);
            Ccurryname.setText(null);
            Cprice.setText(null);
            Csaladname.setText(null);
            Sprice.setText(null);
            Cdessertname.setText(null);
            DEprice.setText(null);
            Cdrinkname.setText(null);
            DRprice.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void OFFERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OFFERMouseClicked
        // TODO add your handling code here:
         fixedpackages.setVisible(false);
        cusMenu.setVisible(false);
        decoration.setVisible(false);
        front.setVisible(true);
        vehicle.setVisible(false);
        photographer.setVisible(false); 
        
        String sq="SELECT * FROM offers ";
        tableLoad(sq);
    }//GEN-LAST:event_OFFERMouseClicked

    private void OFFERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OFFERMousePressed
        // TODO add your handling code here:
         PHOTO.setBackground(Color.BLACK);
         VEHI.setBackground(Color.BLACK);
          FXP.setBackground(Color.BLACK);
           CP.setBackground(Color.BLACK);
            DECO.setBackground(Color.BLACK);
            OFFER.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_OFFERMousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String sq="SELECT * FROM offers ";
        tableLoad(sq);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addOFFERSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOFFERSActionPerformed
        // TODO add your handling code here:
       String B1 = OfferTypeCombo.getSelectedItem().toString();
       String B2 =Offer_ITEM_TypeCombo.getSelectedItem().toString();
       
      String value1 = Item.getSelectedItem().toString();
       //String value2 = Discount.getText();
       System.out.println(B2);
       
      // String B10 = selectValues(value1,value2);
      
        DateFormat df1=new SimpleDateFormat("yyyy-MM-dd");
        Date Edate1;
        Edate1=StartDate.getDate();
        String B4=df1.format(Edate1);
        System.out.println(B4);
        
       // DateFormat df2=new SimpleDateFormat("yyyy-MM-dd");
        Date Edate2;
        Edate2=EndDate.getDate();
        String B5=df1.format(Edate2);
        System.out.println(B5);
       // System.out.println(B10);
       
      
        String q =" INSERT INTO offers(Offer_Type,Offer_ItemType,Offering_Value, Starting_Date, Ending_Date) VALUES ('"+B1+"','"+B2+"','"+value1+"','"+B4+"','"+ B5+"')";
         tableLoad(q);   
        if(ac.addData(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Adding Sucess");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Adding Failed");
        }
     
    }//GEN-LAST:event_addOFFERSActionPerformed

    private void UpdateOFFERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateOFFERActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Update?");
        if(x==0){
       int row=tableMix.getSelectedRow();
       String no=tableMix.getModel().getValueAt(row, 0).toString();     
       String B1 = this.OfferTypeCombo.getSelectedItem().toString();
       String B2 = this.Offer_ITEM_TypeCombo.getSelectedItem().toString();
        String B6 = this.Item.getSelectedItem().toString();
        System.out.println(B6);
        
        DateFormat df1=new SimpleDateFormat("yyyy-MM-dd");
        Date Edate1;
        Edate1=StartDate.getDate();
        String B4=df1.format(Edate1);
        System.out.println(B4);
        
        DateFormat df2=new SimpleDateFormat("yyyy-MM-dd");
        Date Edate2;
        Edate2=EndDate.getDate();
        String B5=df2.format(Edate2);
        System.out.println(B5);
       
        String q ="UPDATE offers SET Offer_Type='"+B1+"',Offer_ItemType='"+B2+"',Offering_Value='"+B6+"',Starting_Date='"+B4+"',Ending_Date='"+B5+"'  WHERE Offer_ID= "+no+"";
        
         if(ac.UpdateTable(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Updating Sucess");
           tableLoad(q);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Updating Failed");
        }
       
        }  
    }//GEN-LAST:event_UpdateOFFERActionPerformed

    private void deleteOFFERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOFFERActionPerformed
        // TODO add your handling code here:
         int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Delete?");
       if(x==0){
       int row=tableMix.getSelectedRow();
       String no=tableMix.getModel().getValueAt(row, 0).toString();     
      
       String q ="DELETE FROM offers WHERE Offer_ID="+no+"";
        
        if(ac.DeleteValues(q,this.tableMix)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Sucess");
          
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Failed");
        }
       
              System.out.println("man");
       }                                       
        
    }//GEN-LAST:event_deleteOFFERActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
             OfferTypeCombo.setSelectedItem(null);
             Offer_ITEM_TypeCombo.setSelectedItem(null);
             Item.setSelectedItem(null);
             StartDate.setDate(null);
              EndDate.setDate(null);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void decoSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decoSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decoSelectActionPerformed

    private void AddCOSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCOSTActionPerformed
        // TODO add your handling code here:
        String c=assignCost.getText();
        System.out.println(c);
        String vid2=ac.getIDFromCombo("Vehicle_ID","wedd_car_detail","Wedd_Car",this.availableVehicles);
        System.out.println(vid2);
        String q="UPDATE wedd_car_detail SET Cost='"+c+"' WHERE Vehicle_ID='"+vid2+"'";
        
         if(ac.addData(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Adding Sucess");
         
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Adding Failed");
        }
       
                                            
        
    }//GEN-LAST:event_AddCOSTActionPerformed

    private void FdessertnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FdessertnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FdessertnameActionPerformed

    private void DpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DpriceActionPerformed

    private void FpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FpriceActionPerformed

    private void FdrinknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FdrinknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FdrinknameActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCOST;
    private javax.swing.JButton CMenu_Add;
    private javax.swing.JPanel CP;
    private javax.swing.JButton CUS_delete;
    private javax.swing.JButton CUS_update;
    private javax.swing.JTextField Ccurryname;
    private javax.swing.JTextField Cdessertname;
    private javax.swing.JTextField Cdrinkname;
    private javax.swing.JTextField Cprice;
    private javax.swing.JTextField Cricename;
    private javax.swing.JTextField Csaladname;
    private javax.swing.JPanel DECO;
    private javax.swing.JButton DECO_Add;
    private javax.swing.JButton DECO_delete;
    private javax.swing.JButton DECO_reset;
    private javax.swing.JTextField DEprice;
    private javax.swing.JTextField DRprice;
    private javax.swing.JTextField Did;
    private javax.swing.JTextField Dname;
    private javax.swing.JTextField Dprice;
    private com.toedter.calendar.JDateChooser EndDate;
    private javax.swing.JPanel FXP;
    private javax.swing.JTextField Fcurryname;
    private javax.swing.JTextField Fdessertname;
    private javax.swing.JTextField Fdrinkname;
    private javax.swing.JTextField Fpackagename;
    private javax.swing.JTextField Fprice;
    private javax.swing.JTextField Fricename;
    private javax.swing.JTextField Fsaladname;
    private javax.swing.JComboBox<String> Item;
    private javax.swing.JPanel OFFER;
    private javax.swing.JComboBox<String> OfferTypeCombo;
    private javax.swing.JComboBox<String> Offer_ITEM_TypeCombo;
    private javax.swing.JPanel PHOTO;
    private javax.swing.JTextField Rprice;
    private javax.swing.JTextField Sprice;
    private com.toedter.calendar.JDateChooser StartDate;
    private javax.swing.JButton UpdateOFFER;
    private javax.swing.JPanel VEHI;
    private javax.swing.JButton add;
    private javax.swing.JButton addOFFERS;
    private javax.swing.JTextField assignCost;
    private javax.swing.JComboBox<String> availableVehicles;
    private javax.swing.JPanel background;
    private javax.swing.JPanel base;
    private javax.swing.JPanel cusMenu;
    private javax.swing.JComboBox<String> decoSelect;
    private javax.swing.JPanel decoration;
    private javax.swing.JButton delete;
    private javax.swing.JButton deleteOFFER;
    private javax.swing.JPanel fixedpackages;
    private javax.swing.JPanel front;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel packageID;
    private javax.swing.JPanel photographer;
    private javax.swing.JButton reset;
    private javax.swing.JTable tableMix;
    private javax.swing.JButton update;
    private javax.swing.JPanel vehicle;
    // End of variables declaration//GEN-END:variables
}
