/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event;

import static Event.Add_Booking.ValidatePhone;
import dbconnect.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP™
 */
public class View_Booking extends javax.swing.JInternalFrame {
     PreparedStatement pst=null;
     Connection conn=null;
      ResultSet table=null;
      EventClass ac=new EventClass(dbconnect.connect()); 
    /**
     * Creates new form View_Booking
     */
    public View_Booking() {
       initComponents();
        conn=dbconnect.connect();
        BookingtableLoad();
    }
    public void tableLoad()
      {  
          String bid=bookingID.getText();
          String nic=NIC.getText();
         try{
            String  sq="SELECT *FROM event_booking WHERE Booking_ID='"+bid+"' OR Cus_NIC='"+nic+"'";
            pst =conn.prepareStatement(sq);
            table = pst.executeQuery();
            booking.setModel(DbUtils.resultSetToTableModel(table));
         }catch(Exception e){
             
         }
      }
      ///////////////////////////////////////////////   
         public void BookingtableLoad()
      {  
          //String bid=bookingID.getText();
         // String nic=NIC.getText();
         try{
            String  sq="SELECT *FROM event_booking ";
            pst =conn.prepareStatement(sq);
            table = pst.executeQuery();
            booking.setModel(DbUtils.resultSetToTableModel(table));
         }catch(Exception e){
             
         }
      }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        booking = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bookingID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        NIC = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bookingid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cusname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cusnic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pstatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        etype = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        menuno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        eventdate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Extra = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cuscontact = new javax.swing.JTextField();
        bookeddate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        UpdateERROR = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1600, 890));
        jPanel1.setMinimumSize(new java.awt.Dimension(1600, 890));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 890));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View  Booking  ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        booking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(booking);

        jTabbedPane1.addTab("Booking", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("", jScrollPane2);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 76, 1260, 260));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/search (1).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 83));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("booking ID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 64, 25));

        bookingID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(bookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 260, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Customer NIC ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        NIC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 19, 297, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/magnifier-tool.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 175, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 28, 1550, 380));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Update Booking");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Booking ID ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 110, 20));

        bookingid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(bookingid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 250, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/management (3).png"))); // NOI18N
        jLabel4.setText("image");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Customer Name ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        cusname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(cusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Customer  NIC");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 20));

        cusnic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(cusnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Payment Status ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));
        jPanel3.add(pstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 100, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 260, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Total");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 260, 30));

        jLabel11.setText("Event Type");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        etype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wedding", "Party" }));
        jPanel3.add(etype, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 260, 30));

        jLabel12.setText("Menu NO ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, 20));

        menuno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunoActionPerformed(evt);
            }
        });
        jPanel3.add(menuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 260, 30));

        jLabel13.setText("Event Date");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 20));
        jPanel3.add(eventdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 260, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Extra");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, -1, -1));

        Extra.setColumns(20);
        Extra.setRows(5);
        jScrollPane3.setViewportView(Extra);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 270, 90));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/management (2).png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, -1, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/throw-to-paper-bin.png"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/three-circling-arrows.png"))); // NOI18N
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 230, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 230, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 190, 230, 40));

        jButton4.setText("Primt");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, -120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Customer contact number");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));

        cuscontact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(cuscontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 270, 30));
        jPanel3.add(bookeddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 110, -1));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Event Time");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));
        jPanel3.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 270, 30));

        UpdateERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(UpdateERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, 100, -1));

        jLabel14.setText("Booked Date");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 1550, 320));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/images/body.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jLabel21.setMaximumSize(new java.awt.Dimension(1600, 890));
        jLabel21.setMinimumSize(new java.awt.Dimension(1600, 890));
        jLabel21.setPreferredSize(new java.awt.Dimension(1600, 890));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
       tableLoad();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMouseClicked
        // TODO add your handling code here:
         try {
             
             int row=booking.getSelectedRow();
             String no=booking.getModel().getValueAt(row, 0).toString();
             String b="select *from event_booking where booking_ID="+no+"";
             pst=conn.prepareStatement(b);
             table=pst.executeQuery();
             if(table.next())
             {
                String bd=table.getString("Booked_Date");
                bookeddate.setText(bd);
                Extra.setText(table.getString("Extra"));
                cuscontact.setText(table.getString("Cus_Contact"));
                bookingid.setText(no);
                cusname.setText(table.getString("Cus_Name"));
                cusnic.setText(table.getString("Cus_NIC"));
                pstatus.setText(table.getString("Payment_Status"));
                total.setText(table.getString("Total"));
                etype.addItem(table.getString("Event_Type"));
                menuno.setText(table.getString("Menu_NO"));
                 
                String date=table.getString("Event_Date");
                Date edate=new SimpleDateFormat("yyyy-MM-dd").parse((String) date);
                eventdate.setDate(edate);
               
                //((JTextField)eventdate.getDateEditor().getUiComponent()).setText(date);
             }
         } catch (SQLException ex) {
            System.out.println(ex);
         } catch (ParseException ex) {
             Logger.getLogger(View_Booking.class.getName()).log(Level.SEVERE, null, ex);
         }                                   
    }//GEN-LAST:event_bookingMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        
         int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Update?");
        if(x==0){
         String  UPbookingid = bookingid.getText();
          String UPcusname = cusname.getText();
           String UPcusnic =  cusnic.getText();
           String UPtotal =  total.getText();
            String UPetype =  etype.getSelectedItem().toString();
             String UPmenuno =  menuno.getText();
              String UPdateStatus = ac.getCurrentDate();;
               String UPcuscontact =  cuscontact.getText();
               String UPExtra =    Extra.getText();
               
        DateFormat datef=new SimpleDateFormat("yyyy-MM-dd");
        Date Edate2;
        Edate2=eventdate.getDate();
        String UPeventdate=datef.format(Edate2);
       // System.out.println(UPeventdate);
        
        //DateFormat tff=new SimpleDateFormat("HH:mm:ss");
        //String UPtime=tff.format(new Date());
        //System.out.println(UPtime);
        
  
        String q ="UPDATE event_booking SET  Event_Type='"+UPetype+"', Event_Date='"+UPeventdate+"', Menu_NO="+UPmenuno+", Total="+UPtotal+", Cus_Name='"+UPcusname+"', Cus_NIC='"+UPcusnic+"', Cus_Contact="+UPcuscontact+", Extra='"+UPExtra+"',Update_Status='"+UPdateStatus+"' WHERE Booking_ID = "+UPbookingid+"";
             //Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/eventm_db", "root", " ");
            String B8=cuscontact.getText();
             if(ValidatePhone(B8)==false)
           {
           cuscontact.setBackground(Color.red);
           
           UpdateERROR.setText("Invalid Date format !!");
           }else{
         if(ac.UpdateTable(q)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Updating Sucess");
         
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Updating Failed");
        }
       
      }  
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int x=JOptionPane.showConfirmDialog(null,"Do ypu really want to Delete?");
       if(x==0){
       int row=booking.getSelectedRow();
       String no=booking.getModel().getValueAt(row, 0).toString();     
      
       String q ="DELETE FROM event_booking WHERE Booking_ID="+no+"";
        
        if(ac.DeleteValues(q,this.booking)==true)
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Sucess");
          
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Deleting Failed");
        }
       }                                       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                bookeddate.setText(null);
                Extra.setText(null);
                cuscontact.setText(null);
                bookingid.setText(null);
                cusname.setText(null);
                cusnic.setText(null);
                pstatus.setText(null);
                total.setText(null);
                etype.addItem(null);
                menuno.setText(null);
                eventdate.setDate(null);
                 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void menunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Extra;
    private javax.swing.JTextField NIC;
    private javax.swing.JLabel UpdateERROR;
    private javax.swing.JLabel bookeddate;
    private javax.swing.JTable booking;
    private javax.swing.JTextField bookingID;
    private javax.swing.JTextField bookingid;
    private javax.swing.JTextField cuscontact;
    private javax.swing.JTextField cusname;
    private javax.swing.JTextField cusnic;
    private javax.swing.JComboBox<String> etype;
    private com.toedter.calendar.JDateChooser eventdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField menuno;
    private javax.swing.JLabel pstatus;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
