/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportmanagement;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Praveena
 */
public class TransportMain extends javax.swing.JFrame {

    /**
     * Creates new form TransportMain
     */
    public TransportMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hallname = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ovel = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ehandling = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainmenu = new javax.swing.JLabel();
        mainmenuicon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rawstock = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        estock = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        supplier = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        hallname.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        hallname.setForeground(new java.awt.Color(255, 255, 255));
        hallname.setText("RAVINDRA RECEPTION HALL");
        jPanel1.add(hallname);
        hallname.setBounds(660, 40, 580, 50);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("TRANSPORT MANAGEMENT");
        jPanel1.add(title);
        title.setBounds(750, 110, 310, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(170, 22, 1580, 10);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/logo.png"))); // NOI18N
        logo.setText(" ");
        jPanel1.add(logo);
        logo.setBounds(10, 20, 230, 140);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(230, 92, 1460, 10);

        ovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/logoutback.png"))); // NOI18N
        ovel.setText(" ");
        jPanel1.add(ovel);
        ovel.setBounds(1800, 20, 100, 100);

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportmanagement/praveena.jpg"))); // NOI18N
        user.setText(" ");
        user.setOpaque(true);
        jPanel1.add(user);
        user.setBounds(1800, 20, 100, 100);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Praveena Sarathchandra");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(name);
        name.setBounds(1750, 130, 160, 20);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 160);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        logout.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");
        logout.add(jLabel7);
        jLabel7.setBounds(160, 20, 80, 22);

        jLabel21.setText(" ");
        logout.add(jLabel21);
        jLabel21.setBounds(10, 0, 64, 16);

        jLabel22.setText(" ");
        logout.add(jLabel22);
        jLabel22.setBounds(30, 0, 64, 16);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportmanagement/imgs/logout.png"))); // NOI18N
        jLabel23.setText(" ");
        logout.add(jLabel23);
        jLabel23.setBounds(80, 0, 64, 64);

        jPanel2.add(logout);
        logout.setBounds(0, 980, 320, 70);

        ehandling.setBackground(new java.awt.Color(0, 0, 0));
        ehandling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ehandling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ehandlingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ehandlingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ehandlingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ehandlingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ehandlingMouseReleased(evt);
            }
        });
        ehandling.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Booking Details");
        ehandling.add(jLabel5);
        jLabel5.setBounds(120, 20, 165, 22);

        home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wedding-car (4).png"))); // NOI18N
        home1.setText(" ");
        home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                home1MouseReleased(evt);
            }
        });
        ehandling.add(home1);
        home1.setBounds(40, 0, 70, 70);

        jLabel10.setText(" ");
        ehandling.add(jLabel10);
        jLabel10.setBounds(10, 0, 64, 64);

        jPanel2.add(ehandling);
        ehandling.setBounds(0, 330, 320, 70);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 160, 320, 2);

        mainmenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainmenu.setForeground(new java.awt.Color(255, 255, 255));
        mainmenu.setText("MAIN MENU");
        jPanel2.add(mainmenu);
        mainmenu.setBounds(100, 170, 130, 30);

        mainmenuicon.setText(" ");
        jPanel2.add(mainmenuicon);
        mainmenuicon.setBounds(10, 170, 32, 32);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 210, 320, 2);

        rawstock.setBackground(new java.awt.Color(0, 0, 0));
        rawstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rawstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rawstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rawstockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rawstockMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rawstockMouseReleased(evt);
            }
        });
        rawstock.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tour Details");
        rawstock.add(jLabel11);
        jLabel11.setBounds(120, 20, 163, 22);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tourist (2).png"))); // NOI18N
        home.setText(" ");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        rawstock.add(home);
        home.setBounds(30, 0, 70, 70);

        jPanel2.add(rawstock);
        rawstock.setBounds(0, 460, 320, 70);

        estock.setBackground(new java.awt.Color(0, 0, 0));
        estock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estockMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                estockMouseReleased(evt);
            }
        });
        estock.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Wedding Car Details");
        estock.add(jLabel9);
        jLabel9.setBounds(120, 30, 210, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wedding-car.png"))); // NOI18N
        jLabel14.setText(" ");
        estock.add(jLabel14);
        jLabel14.setBounds(40, 0, 64, 64);

        jPanel2.add(estock);
        estock.setBounds(0, 590, 320, 70);

        supplier.setBackground(new java.awt.Color(0, 0, 0));
        supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supplierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                supplierMouseReleased(evt);
            }
        });
        supplier.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Taxi Company");
        supplier.add(jLabel13);
        jLabel13.setBounds(120, 20, 163, 22);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rent-a-car.png"))); // NOI18N
        jLabel24.setText(" ");
        supplier.add(jLabel24);
        jLabel24.setBounds(40, 0, 64, 64);

        jPanel2.add(supplier);
        supplier.setBounds(0, 710, 320, 70);

        jLabel12.setText(" ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 450, 64, 64);

        jLabel6.setText(" ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 230, 64, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportmanagement/imgs/home.png"))); // NOI18N
        jLabel8.setText(" ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 230, 64, 64);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 1080);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jDesktopPane1);
        jDesktopPane1.setBounds(320, 160, 1600, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(Color.BLUE);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        logout.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        logout.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_logoutMouseReleased

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/homehover.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/home.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/homepressed.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/home.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseReleased

    private void ehandlingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ehandlingMouseClicked

    private void ehandlingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseEntered
        ehandling.setBackground(Color.BLUE);
    }//GEN-LAST:event_ehandlingMouseEntered

    private void ehandlingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseExited
        ehandling.setBackground(Color.BLACK);
    }//GEN-LAST:event_ehandlingMouseExited

    private void ehandlingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMousePressed
        ehandling.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_ehandlingMousePressed

    private void ehandlingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseReleased

        jDesktopPane1.removeAll();
        BookingDetails mal=new BookingDetails();
        jDesktopPane1.add(mal).setVisible(true);

    }//GEN-LAST:event_ehandlingMouseReleased

    private void rawstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMouseEntered
        rawstock.setBackground(Color.BLUE);
    }//GEN-LAST:event_rawstockMouseEntered

    private void rawstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMouseExited
        rawstock.setBackground(Color.BLACK);
    }//GEN-LAST:event_rawstockMouseExited

    private void rawstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMousePressed
        rawstock.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_rawstockMousePressed

    private void rawstockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawstockMouseReleased
       // rawstock.setForeground(Color.BLACK);
       jDesktopPane1.removeAll();
        TourDetails mal=new TourDetails();
        jDesktopPane1.add(mal).setVisible(true);
    }//GEN-LAST:event_rawstockMouseReleased

    private void estockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseEntered
        estock.setBackground(Color.BLUE);
    }//GEN-LAST:event_estockMouseEntered

    private void estockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseExited
        estock.setBackground(Color.BLACK);
    }//GEN-LAST:event_estockMouseExited

    private void estockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMousePressed
        estock.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_estockMousePressed

    private void estockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseReleased
        jDesktopPane1.removeAll();
        WeddingCarDetails  wd = new WeddingCarDetails();
        jDesktopPane1.add(wd).setVisible(true);
    }//GEN-LAST:event_estockMouseReleased

    private void supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseEntered
        supplier.setBackground(Color.BLUE);
    }//GEN-LAST:event_supplierMouseEntered

    private void supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseExited
        supplier.setBackground(Color.BLACK);
    }//GEN-LAST:event_supplierMouseExited

    private void supplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMousePressed
        supplier.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_supplierMousePressed

    private void supplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseReleased
        //supplier.setForeground(Color.BLACK);
        jDesktopPane1.removeAll();
        select mal=new select();
        jDesktopPane1.add(mal).setVisible(true);
    }//GEN-LAST:event_supplierMouseReleased

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_home1MouseEntered

    private void home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_home1MouseExited

    private void home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_home1MousePressed

    private void home1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_home1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ehandling;
    private javax.swing.JPanel estock;
    private javax.swing.JLabel hallname;
    private javax.swing.JLabel home;
    private javax.swing.JLabel home1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel mainmenu;
    private javax.swing.JLabel mainmenuicon;
    private javax.swing.JLabel name;
    private javax.swing.JLabel ovel;
    private javax.swing.JPanel rawstock;
    private javax.swing.JPanel supplier;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
