/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintenancemanagement;

import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import dbconnect.dbconnect;
import java.awt.Color;
import static java.awt.Color.red;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Shihan
 */
public class buildings extends javax.swing.JInternalFrame {

String aa=null;
Connection con =null;
PreparedStatement pst =null;
ResultSet rs = null;
String buildnno;
maintenanceclass m=new maintenanceclass();
    
        public buildings() {
        initComponents();
        con=dbconnect.connect();
        viewtable();
        viewtablerep();
    }
        public void viewtable()
    {
         String sqbuild="SELECT * FROM buildingdetails";
            
            try{
                    pst=con.prepareStatement(sqbuild);
                    pst.execute();
                    rs=pst.executeQuery();
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    
            }
            catch(Exception e){
                    JOptionPane.showConfirmDialog(null, e);
            }
    }
            public void viewtablerep()
    {
         String sqveh="SELECT * FROM buildingrepair";
            
            try{
                    pst=con.prepareStatement(sqveh);
                    pst.execute();
                    rs=pst.executeQuery();
                    buildingreptable.setModel(DbUtils.resultSetToTableModel(rs));
    
            }
            catch(Exception e){
                    JOptionPane.showConfirmDialog(null, e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        amnt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        buildingreptable = new javax.swing.JTable();
        bno = new javax.swing.JTextField();
        strs = new javax.swing.JTextField();
        are = new javax.swing.JTextField();
        othr = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        updtbldnrep = new javax.swing.JButton();
        updt1 = new javax.swing.JButton();
        srch = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buildnm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        printbd = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(1690, 940));
        setPreferredSize(new java.awt.Dimension(1690, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Building No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, 120, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Stories :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 120, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Area : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 120, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Other Records ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, 120, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Amount :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 90, 25));

        amnt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amntActionPerformed(evt);
            }
        });
        amnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amntKeyPressed(evt);
            }
        });
        getContentPane().add(amnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 560, 350, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/add.png"))); // NOI18N
        jButton1.setText("Add Entry");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, 150, 50));

        buildingreptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "EntryID", "Descreption", "Amount"
            }
        ));
        buildingreptable.setRowHeight(30);
        buildingreptable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        buildingreptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildingreptableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(buildingreptable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 890, 190));

        bno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(bno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 60, 350, 40));

        strs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        strs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                strsMouseClicked(evt);
            }
        });
        strs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                strsKeyPressed(evt);
            }
        });
        getContentPane().add(strs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, 350, 40));

        are.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        are.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                areKeyPressed(evt);
            }
        });
        getContentPane().add(are, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 160, 350, 40));

        othr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(othr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 210, 350, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Building No", "Stories", "Area", "Other Records"
            }
        ));
        jTable2.setRowHeight(30);
        jTable2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 890, 230));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/add.png"))); // NOI18N
        jButton2.setText("Add Building");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 260, 150, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Remove Building");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("View Building Details");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 40));

        updtbldnrep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updtbldnrep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/update.png"))); // NOI18N
        updtbldnrep.setText("Update");
        updtbldnrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbldnrepActionPerformed(evt);
            }
        });
        getContentPane().add(updtbldnrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 610, 120, 50));

        updt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/update.png"))); // NOI18N
        updt1.setText("Update");
        updt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updt1MouseClicked(evt);
            }
        });
        updt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updt1ActionPerformed(evt);
            }
        });
        getContentPane().add(updt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 260, 120, 50));
        getContentPane().add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 120, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/clear.png"))); // NOI18N
        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Enter Building No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/search.png"))); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BuildingNo :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 410, 160, 20));

        buildnm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(buildnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 410, 350, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Descreption :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 460, 120, 25));

        des.setColumns(20);
        des.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        des.setRows(5);
        jScrollPane1.setViewportView(des);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 460, 350, 90));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Building Repairs");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 350, 290, 40));

        printbd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printbd.setText("Print Building Details");
        printbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbdActionPerformed(evt);
            }
        });
        getContentPane().add(printbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 260, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Print building repair details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 260, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Building Details");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 370, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/body.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1590, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amntActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        String bnmbr=bno.getText();
        String stries=strs.getText();
        String area=are.getText();
        String other=othr.getText();

        if(bnmbr.isEmpty()||stries.isEmpty()||area.isEmpty()||other.isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        }
        else{
        int x=JOptionPane.showConfirmDialog(null,"Add building?");
        if(x==0)
        {
              m.addbldn(bnmbr,stries,area,other);
        }
        bno.setText("");
        strs.setText("");
        are.setText("");
        othr.setText("");
        viewtable();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dscrptn=des.getText();
        String amount=amnt.getText();
        String bn=buildnm.getText();
        
        if(dscrptn.isEmpty()||amount.isEmpty()||bn.isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        }
        else{
        int x=JOptionPane.showConfirmDialog(null,"Proceed?");
        if(x==0)
        {
              m.addbldnrep(bn,dscrptn,amount);

        }
        viewtablerep();
        buildnm.setText("");
        des.setText("");
        amnt.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            String sqdel="DELETE FROM buildingdetails WHERE BuildingNo='"+buildnno+"' ";  
            int x=JOptionPane.showConfirmDialog(null,"Do you want to remove a building?");
            if(x==0){
           try{
                    pst=con.prepareStatement(sqdel);
                    pst.execute();
                    
    
            }
            catch(Exception e){
                    JOptionPane.showConfirmDialog(null, e);
            } 
            viewtable();
            JOptionPane.showMessageDialog(null, "Building removed!");
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void amntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amntKeyPressed
    int key= evt.getKeyCode();//validation
        if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE){
            amnt.setEditable(true);
            amnt.setBackground(Color.white);   
        }
        else{
            getToolkit().beep();
            amnt.setEditable(false);
            amnt.setBackground(red);
            
        }
    }//GEN-LAST:event_amntKeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        
        
        try{
        
        int row=jTable2.getSelectedRow();//select items to the fields
        buildnno=jTable2.getValueAt(row,0).toString();//remove building
        aa=jTable2.getModel().getValueAt(row, 0).toString();
        String a="select * from buildingdetails where BuildingNo='"+aa+"'";
        pst=con.prepareStatement(a);
        rs=pst.executeQuery();
        if(rs.next()){
            bno.setText(rs.getString("BuildingNo"));
            strs.setText(rs.getString("Stories"));
            are.setText(rs.getString("Area"));
            othr.setText(rs.getString("OtherRecords"));
            
        }
        }
                catch(Exception ex)
        {
            System.out.println(ex);
            //Logger.getLogger(vehiclerepair.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void strsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_strsMouseClicked

    private void strsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strsKeyPressed
        int key= evt.getKeyCode();//validation
        if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE){
            strs.setEditable(true);
            strs.setBackground(Color.white);   
        }
        else{
            getToolkit().beep();
            strs.setEditable(false);
            strs.setBackground(red);
            
        }
    }//GEN-LAST:event_strsKeyPressed

    private void areKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areKeyPressed
    int key= evt.getKeyCode();//validation
        if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE){
            are.setEditable(true);
            are.setBackground(Color.white);   
        }
        else{
            getToolkit().beep();
            are.setEditable(false);
            are.setBackground(red);
            
        }
    }//GEN-LAST:event_areKeyPressed

    private void updtbldnrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbldnrepActionPerformed
        String dscrptn=des.getText();
        String amount=amnt.getText();
        String bnm=buildnm.getText(); 
        
        if(dscrptn.isEmpty()||amount.isEmpty()||bnm.isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        }
        else{
        m.updtbldrep(bnm,dscrptn,amount,aa);
        
            viewtablerep();
            des.setText("");
            amnt.setText("");
            buildnm.setText("");
            JOptionPane.showMessageDialog(null, "Entry Updated!");
        }
            
    }//GEN-LAST:event_updtbldnrepActionPerformed

    private void updt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updt1ActionPerformed
        String bldnno=bno.getText();       
        String stries=strs.getText();
        String area=are.getText();
        String other=othr.getText();
        if(bldnno.isEmpty()||stries.isEmpty()||area.isEmpty()||other.isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        }
        else{ 
        m.updtbldn(bldnno,stries,area,other);
        
            viewtable();       
            
            bno.setText("");
            strs.setText("");
            are.setText("");
            othr.setText("");
            JOptionPane.showMessageDialog(null, "Entry Updated!");
        }
    }//GEN-LAST:event_updt1ActionPerformed

    private void buildingreptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingreptableMouseClicked
    try{
        int row=buildingreptable.getSelectedRow();//select items to the fields
        aa=buildingreptable.getModel().getValueAt(row, 0).toString();
        String a="select * from buildingrepair where EntryID='"+aa+"'";
        pst=con.prepareStatement(a);
        rs=pst.executeQuery();
        if(rs.next()){
            buildnm.setText(rs.getString("BuildingNo"));
            des.setText(rs.getString("Descreption"));
            amnt.setText(rs.getString("Amount"));
            
        }
        }
                catch(Exception ex)
        {
            System.out.println(ex);
            //Logger.getLogger(vehiclerepair.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_buildingreptableMouseClicked

    private void updt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updt1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String bldnm=srch.getText();
    String sql="SELECT * FROM buildingrepair WHERE BuildingNo LIKE '%"+bldnm+"%'";
    try{
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery();
        buildingreptable.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(Exception e){
    
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        viewtablerep();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void printbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbdActionPerformed
        try {
                String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\building.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(rep);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_printbdActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String bnum = srch.getText();
        if (bnum.isEmpty()) {
            try {
                String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\buildingrepair.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(rep);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else {
            try {

                JasperDesign jd = JRXmlLoader.load("C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\buildingrepair.jrxml");
                String sql = "select * from buildingrepair where BuildingNo like '%" + bnum + "%'";
                JRDesignQuery n1 = new JRDesignQuery();
                n1.setText(sql);
                jd.setQuery(n1);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amnt;
    private javax.swing.JTextField are;
    private javax.swing.JTextField bno;
    private javax.swing.JTable buildingreptable;
    private javax.swing.JTextField buildnm;
    private javax.swing.JTextArea des;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField othr;
    private javax.swing.JButton printbd;
    private javax.swing.JTextField srch;
    private javax.swing.JTextField strs;
    private javax.swing.JButton updt1;
    private javax.swing.JButton updtbldnrep;
    // End of variables declaration//GEN-END:variables
}
