/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintenancemanagement;

import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import dbconnect.dbconnect;
import java.awt.Color;
import static java.awt.Color.red;
import static java.awt.Color.white;
//import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.Date;

public class licenseandinsurance extends javax.swing.JFrame {
Connection con =null;
PreparedStatement pst =null;
ResultSet rs = null;
String VehicleNmbr;
String aa=null;
maintenanceclass m=new maintenanceclass();
    
public licenseandinsurance() {
        initComponents();
        con=dbconnect.connect();
        viewtablelicn();
        viewtableins();
    }


        public void viewtablelicn()
    {
         String sqlicn="SELECT * FROM license";
            
            try{
                    pst=con.prepareStatement(sqlicn);
                    pst.execute();
                    rs=pst.executeQuery();
                    licensetable.setModel(DbUtils.resultSetToTableModel(rs));
    
            }
            catch(Exception e){
                    JOptionPane.showConfirmDialog(null, e);
            }
    }
                public void viewtableins()
    {
         String sqlicn="SELECT * FROM insurance";
            
            try{
                    pst=con.prepareStatement(sqlicn);
                    pst.execute();
                    rs=pst.executeQuery();
                    insurancetable.setModel(DbUtils.resultSetToTableModel(rs));
    
            }
            catch(Exception e){
                    JOptionPane.showConfirmDialog(null, e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        licensetable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        insurancetable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vnolicn = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lrenew = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        lexp = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        amnt = new javax.swing.JTextField();
        updatelicense = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vnoinsure = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        irenew = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        iexp = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        amnti = new javax.swing.JTextField();
        updateinsurance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(null);

        licensetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "License Renewed On", "License Expires On"
            }
        ));
        licensetable.setFillsViewportHeight(true);
        licensetable.setRowHeight(30);
        licensetable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        licensetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                licensetableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(licensetable);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 50, 890, 150);

        insurancetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Insurance Renewed On", "Insurance Expires On"
            }
        ));
        insurancetable.setFillsViewportHeight(true);
        insurancetable.setRowHeight(30);
        insurancetable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        insurancetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insurancetableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(insurancetable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 280, 890, 150);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("License ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(1020, 50, 100, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Vehicle No :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1020, 80, 110, 25);

        vnolicn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vnolicn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnolicnActionPerformed(evt);
            }
        });
        getContentPane().add(vnolicn);
        vnolicn.setBounds(1300, 70, 190, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("License renewed on :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(1020, 110, 210, 25);
        getContentPane().add(lrenew);
        lrenew.setBounds(1300, 110, 190, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("License Expires on :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1020, 150, 170, 25);
        getContentPane().add(lexp);
        lexp.setBounds(1300, 150, 190, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Amount :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1020, 190, 170, 25);

        amnt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amntKeyPressed(evt);
            }
        });
        getContentPane().add(amnt);
        amnt.setBounds(1300, 190, 190, 30);

        updatelicense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updatelicense.setText("Update");
        updatelicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatelicenseActionPerformed(evt);
            }
        });
        getContentPane().add(updatelicense);
        updatelicense.setBounds(1170, 230, 120, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Insurance");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1020, 260, 120, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Vehicle No :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1020, 290, 110, 25);

        vnoinsure.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vnoinsure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnoinsureActionPerformed(evt);
            }
        });
        getContentPane().add(vnoinsure);
        vnoinsure.setBounds(1300, 280, 190, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Insurance renewed on :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1020, 320, 220, 25);
        getContentPane().add(irenew);
        irenew.setBounds(1300, 320, 190, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Insurance Expires on :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1020, 360, 190, 25);
        getContentPane().add(iexp);
        iexp.setBounds(1300, 360, 190, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Amount :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1020, 400, 170, 25);

        amnti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amnti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amntiKeyPressed(evt);
            }
        });
        getContentPane().add(amnti);
        amnti.setBounds(1300, 400, 190, 30);

        updateinsurance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateinsurance.setText("Update");
        updateinsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateinsuranceActionPerformed(evt);
            }
        });
        getContentPane().add(updateinsurance);
        updateinsurance.setBounds(1170, 480, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void licensetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_licensetableMouseClicked
        //        try{
            int row=licensetable.getSelectedRow();//select items to the fields
            //        String a="select * from license where VehicleNo='"+aa+"'";
            //        aa=licensetable.getModel().getValueAt(row, 0).toString();
            //        pst=con.prepareStatement(a);
            //        rs=pst.executeQuery();
            //        if(rs.next()){
                //vnolicn.setText(rs.getString("VehicleNo"));
                //lrenew.setDate(rs.getDate("LicenseRenewedOn"));
                //lexp.setDate(rs.getDate("LicenseExpiresOn"));
                //amnt.setText(rs.getString("Amount"));
                vnolicn.setText(licensetable.getValueAt(row, 0).toString());
                //        }
            //        }
        //                catch(Exception ex)
        //        {
            //            System.out.println(ex);
            //            //Logger.getLogger(vehiclerepair.class.getName()).log(Level.SEVERE,null,ex);
            //        }
    }//GEN-LAST:event_licensetableMouseClicked

    private void insurancetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insurancetableMouseClicked
        //    try{
            int row=insurancetable.getSelectedRow();//select items to the fields
            //        aa=insurancetable.getModel().getValueAt(row, 0).toString();
            //        String a="select * from insurance where VehicleNo='"+aa+"'";
            //        pst=con.prepareStatement(a);
            //        rs=pst.executeQuery();
            //        if(rs.next()){
                vnoinsure.setText(insurancetable.getValueAt(row, 0).toString());
                //irenew.setSelectedItem(rs.getString("RoomType"));
                //iexp.setSelectedItem(rs.getString("Status"));
                //amnti.setText(rs.getString("CleanedBy"));

                //        }
            //        }
        //                catch(Exception ex)
        //        {
            //            System.out.println(ex);
            //            //Logger.getLogger(vehiclerepair.class.getName()).log(Level.SEVERE,null,ex);
            //        }
    }//GEN-LAST:event_insurancetableMouseClicked

    private void vnolicnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnolicnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnolicnActionPerformed

    private void amntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amntKeyPressed
        int key= evt.getKeyCode();//validation
        if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE){
            amnt.setEditable(true);
            amnt.setBackground(Color.white);
        }
        else{
            getToolkit().beep();
            amnt.setEditable(false);
            amnt.setBackground(red);

        }
    }//GEN-LAST:event_amntKeyPressed

    private void updatelicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatelicenseActionPerformed
        String vnmbr=vnolicn.getText();
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        

        DateFormat de=new SimpleDateFormat("yyyy-MM-dd");
        
        String amntl=amnt.getText();
        System.out.print("asdg");

        if(vnmbr.isEmpty()||df==null||de==null||amntl.isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        }
        else{
        if(vehiclnmbrchck(vnmbr)){
            int x=JOptionPane.showConfirmDialog(null,"Update License details?");
            if(x==0)
            {
                Date lrenewd;
                lrenewd=lrenew.getDate();
                String licndate=df.format(lrenewd);
                
                Date lexdate;
                lexdate=lexp.getDate();
                String licndateex=de.format(lexdate);
                
                m.licnif(licndate,licndateex,amntl,vnmbr);
                viewtablelicn();
                JOptionPane.showMessageDialog(null, "Date Updated");

            }

        }
        else
        {
            int x=JOptionPane.showConfirmDialog(null,"Insert license details?");
            if(x==0)
            {
                Date lrenewd;
                lrenewd=lrenew.getDate();
                String licndate=df.format(lrenewd);
                
                Date lexdate;
                lexdate=lexp.getDate();
                String licndateex=de.format(lexdate);
                
                
                m.licnelse(vnmbr,licndate,licndateex,amntl);
                viewtablelicn();
                JOptionPane.showMessageDialog(null, "Date Inserted");
            }

        }
        vnolicn.setText("");
        amnt.setText("");
        //amnti.setText("");
        lrenew.setDate(null);
        lexp.setDate(null);
        amnt.setBackground(white);
        
        }
        //JOptionPane.showMessageDialog(null, "Date Updated");//msg
    }//GEN-LAST:event_updatelicenseActionPerformed

    private void vnoinsureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnoinsureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnoinsureActionPerformed

    private void amntiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amntiKeyPressed
        int key= evt.getKeyCode();//validation
        if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE){
            amnti.setEditable(true);
            amnti.setBackground(Color.white);
        }
        else{
            getToolkit().beep();
            amnti.setEditable(false);
            amnti.setBackground(red);

        }
    }//GEN-LAST:event_amntiKeyPressed

    private void updateinsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateinsuranceActionPerformed
        String vnmbrins=vnoinsure.getText();
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        

        DateFormat de=new SimpleDateFormat("yyyy-MM-dd");
        
        String amntins=amnti.getText();
        System.out.print("asdg");
        
        if(vnmbrins.isEmpty()||df==null||de==null||amntins.isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        }
        else{
        if(vehiclnmbrchckins(vnmbrins)){
            int x=JOptionPane.showConfirmDialog(null,"Update insurance details?");
            if(x==0)
            {
                Date insrenewd;
                insrenewd=irenew.getDate();
                String insdate=df.format(insrenewd);
                
                Date insexdate;
                insexdate=iexp.getDate();
                String insdateex=de.format(insexdate);
                
                m.insif(insdate,insdateex,amntins,vnmbrins);
                viewtableins();
                JOptionPane.showMessageDialog(null, "Date Updated");
            }

        }
        else
        {
            int x=JOptionPane.showConfirmDialog(null,"Insert insurance details?");
            if(x==0)
            {
                Date insrenewd;
                insrenewd=irenew.getDate();
                String insdate=df.format(insrenewd);
                
                Date insexdate;
                insexdate=iexp.getDate();
                String insdateex=de.format(insexdate);
                
                m.inselse(vnmbrins,insdate,insdateex,amntins);
                viewtableins();
                JOptionPane.showMessageDialog(null, "Date Inserted");
            }

        }
        vnoinsure.setText("");
        irenew.setDate(null);
        iexp.setDate(null);
        amnti.setText("");
        amnti.setBackground(white);
       
        }
        //JOptionPane.showMessageDialog(null, "Date Updated");//msg
    }//GEN-LAST:event_updateinsuranceActionPerformed
    
    public boolean vehiclnmbrchck(String vehiclno ){
        boolean status= true;
        try{
                String sql="SELECT VehicleNo FROM license WHERE VehicleNo like '"+vehiclno+"' ";
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    status=true;
                }
                else{
                    status=false;
                }
           }
        catch(Exception e){
                
             }
        return status;
    }
    
    public boolean vehiclnmbrchckins(String vehiclno ){
        boolean status= true;
        try{
                String sql="SELECT VehicleNo FROM insurance WHERE VehicleNo like '"+vehiclno+"' ";
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    status=true;
                }
                else{
                    status=false;
                }
           }
        catch(Exception e){
                
             }
        return status;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(licenseandinsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(licenseandinsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(licenseandinsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(licenseandinsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new licenseandinsurance().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amnt;
    private javax.swing.JTextField amnti;
    private com.toedter.calendar.JDateChooser iexp;
    private javax.swing.JTable insurancetable;
    private com.toedter.calendar.JDateChooser irenew;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser lexp;
    private javax.swing.JTable licensetable;
    private com.toedter.calendar.JDateChooser lrenew;
    private javax.swing.JButton updateinsurance;
    private javax.swing.JButton updatelicense;
    private javax.swing.JTextField vnoinsure;
    private javax.swing.JTextField vnolicn;
    // End of variables declaration//GEN-END:variables
}
