/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintenancemanagement;

import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Shihan
 */
public final class main extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int log;
   
    public main() {
        initComponents();
        con = dbconnect.connect();
        today.setText(showDate());
        showTime();
        viewvehiclecost();
        viewbuildcost();
        othercost();
        furthercost();
        intofloat();
    }
    public main(int lg ,String n) {
        initComponents();
        con = dbconnect.connect();
        today.setText(showDate());
        showTime();
        viewvehiclecost();
        viewbuildcost();
        othercost();
        furthercost();
        intofloat();
    }
    public void show_images()
    {
        try {
            String a="select * from empdet where Position='Maintenance Supervisor'";
            pst=con.prepareStatement(a);
            rs=pst.executeQuery();
            if(rs.next())
            {
                byte[] b=rs.getBytes("Photo");
                ImageIcon im=new ImageIcon();
                ovel.setIcon(im);
            }
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void viewvehiclecost()
    {
        String sql="SELECT SUM(Amount) AS count FROM vehiclerepair";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
            vrepcost.setText(rs.getString("count"));
           }
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);

        }
    }
        public void viewbuildcost()
    {
        String sql="SELECT SUM(Amount) AS count FROM buildingrepair";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
            brepcost.setText(rs.getString("count"));
           }
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);

        }
        
    }
    
  public void othercost()
    {
        String sql="SELECT SUM(Amount) AS count FROM othermaintenance";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
            orepcost.setText(rs.getString("count"));
           }
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);

        }
    }      
    
  public void furthercost()
    {
        String sql="SELECT SUM(Amount) AS count FROM furtherconstructions";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
            frepcost.setText(rs.getString("count"));
           }
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);

        }
    }
  
  public void intofloat()
  {
      float tot;
      float a=Float.parseFloat(vrepcost.getText());
      float b=Float.parseFloat(brepcost.getText());
      float c=Float.parseFloat(orepcost.getText());
      float d=Float.parseFloat(frepcost.getText());
      tot=a+b+c+d; 
      total.setText(Float.toString(tot));
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hallname = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        ovel = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        today = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home1 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vehrep = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainmenu = new javax.swing.JLabel();
        mainmenuicon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        buildrep = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        clean = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        othr = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        frthr = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DesktopPane2 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        vrepcost = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        frepcost = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        brepcost = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        orepcost = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        hallname.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        hallname.setForeground(new java.awt.Color(255, 255, 255));
        hallname.setText("RAVINDRA RECEPTION HALL");
        jPanel1.add(hallname);
        hallname.setBounds(660, 40, 580, 50);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Maintenance Management System");
        jPanel1.add(title);
        title.setBounds(760, 110, 380, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(170, 22, 1580, 10);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/logor.png"))); // NOI18N
        logo.setText(" ");
        jPanel1.add(logo);
        logo.setBounds(10, 0, 200, 160);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(230, 92, 1460, 10);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/minimize.png"))); // NOI18N
        minimize.setText(" ");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(1840, 10, 40, 32);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/close.png"))); // NOI18N
        close.setText(" ");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1880, 10, 40, 32);

        ovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/logoutback.png"))); // NOI18N
        ovel.setText(" ");
        jPanel1.add(ovel);
        ovel.setBounds(1750, 30, 100, 100);

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setIcon(new javax.swing.ImageIcon("C:\\Users\\MUNESH\\Desktop\\shihan.jpg")); // NOI18N
        user.setText(" ");
        user.setOpaque(true);
        jPanel1.add(user);
        user.setBounds(1750, 30, 100, 100);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Shihan M.S.M");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(name);
        name.setBounds(1760, 130, 120, 20);

        time.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("  ");
        jPanel1.add(time);
        time.setBounds(1480, 110, 210, 30);

        today.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        today.setForeground(new java.awt.Color(255, 255, 255));
        today.setText("  ");
        today.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(today);
        today.setBounds(320, 110, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 160);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        home1.setBackground(new java.awt.Color(0, 0, 0));
        home1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                home1MouseReleased(evt);
            }
        });
        home1.setLayout(null);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/home.png"))); // NOI18N
        home.setText(" ");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        home1.add(home);
        home.setBounds(130, 0, 70, 70);

        jPanel2.add(home1);
        home1.setBounds(0, 230, 320, 70);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        logout.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");
        logout.add(jLabel7);
        jLabel7.setBounds(90, 30, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/logout.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        logout.add(jLabel1);
        jLabel1.setBounds(10, 10, 64, 64);

        jPanel2.add(logout);
        logout.setBounds(0, 930, 320, 90);

        vehrep.setBackground(new java.awt.Color(0, 0, 0));
        vehrep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vehrep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehrepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vehrepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vehrepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vehrepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                vehrepMouseReleased(evt);
            }
        });
        vehrep.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vehicles ");
        vehrep.add(jLabel5);
        jLabel5.setBounds(80, 30, 190, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/car-repairwhite.png"))); // NOI18N
        jLabel6.setText(" ");
        vehrep.add(jLabel6);
        jLabel6.setBounds(10, 10, 64, 64);

        jPanel2.add(vehrep);
        vehrep.setBounds(0, 310, 320, 90);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 160, 320, 2);

        mainmenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainmenu.setForeground(new java.awt.Color(255, 255, 255));
        mainmenu.setText("MAIN MENU");
        jPanel2.add(mainmenu);
        mainmenu.setBounds(100, 170, 130, 30);

        mainmenuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/menu.png"))); // NOI18N
        mainmenuicon.setText(" ");
        jPanel2.add(mainmenuicon);
        mainmenuicon.setBounds(10, 170, 32, 32);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 210, 320, 2);

        buildrep.setBackground(new java.awt.Color(0, 0, 0));
        buildrep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buildrep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buildrepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buildrepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildrepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buildrepMouseReleased(evt);
            }
        });
        buildrep.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buildings ");
        buildrep.add(jLabel11);
        jLabel11.setBounds(80, 30, 190, 29);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/houses.png"))); // NOI18N
        jLabel12.setText(" ");
        buildrep.add(jLabel12);
        jLabel12.setBounds(10, 10, 64, 64);

        jPanel2.add(buildrep);
        buildrep.setBounds(0, 420, 320, 90);

        clean.setBackground(new java.awt.Color(0, 0, 0));
        clean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cleanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cleanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cleanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cleanMouseReleased(evt);
            }
        });
        clean.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("House Keeping");
        clean.add(jLabel9);
        jLabel9.setBounds(80, 30, 230, 29);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/man-cleaning.png"))); // NOI18N
        jLabel10.setText(" ");
        clean.add(jLabel10);
        jLabel10.setBounds(10, 10, 64, 64);

        jPanel2.add(clean);
        clean.setBounds(0, 520, 320, 90);

        othr.setBackground(new java.awt.Color(0, 0, 0));
        othr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        othr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                othrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                othrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                othrMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                othrMouseReleased(evt);
            }
        });
        othr.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Other Maintenance");
        othr.add(jLabel13);
        jLabel13.setBounds(80, 30, 210, 29);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/maintenance.png"))); // NOI18N
        jLabel14.setText(" ");
        othr.add(jLabel14);
        jLabel14.setBounds(10, 10, 64, 64);

        jPanel2.add(othr);
        othr.setBounds(0, 630, 320, 90);

        frthr.setBackground(new java.awt.Color(0, 0, 0));
        frthr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        frthr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                frthrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                frthrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frthrMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                frthrMouseReleased(evt);
            }
        });
        frthr.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Further Constructions");
        frthr.add(jLabel15);
        jLabel15.setBounds(80, 30, 230, 22);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/brickwall.png"))); // NOI18N
        jLabel16.setText(" ");
        frthr.add(jLabel16);
        jLabel16.setBounds(10, 10, 64, 64);

        jPanel2.add(frthr);
        frthr.setBounds(0, 750, 320, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 1080);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        vrepcost.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel3.add(vrepcost);
        vrepcost.setBounds(730, 90, 450, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Cost of building repairs        ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(200, 150, 470, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("Cost of further constructions ");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(200, 310, 480, 40);

        frepcost.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel3.add(frepcost);
        frepcost.setBounds(730, 320, 470, 30);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/brickwall black.png"))); // NOI18N
        jPanel3.add(jLabel22);
        jLabel22.setBounds(110, 290, 70, 70);

        total.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel3.add(total);
        total.setBounds(730, 380, 470, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("Total Cost                           ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(200, 380, 458, 44);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/othermainblack.png"))); // NOI18N
        jPanel3.add(jLabel21);
        jLabel21.setBounds(110, 210, 70, 70);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/houses black.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.setMinimumSize(new java.awt.Dimension(64, 64));
        jLabel19.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jLabel19);
        jLabel19.setBounds(110, 140, 70, 60);

        brepcost.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel3.add(brepcost);
        brepcost.setBounds(730, 160, 460, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/car-repairblack.png"))); // NOI18N
        jPanel3.add(jLabel23);
        jLabel23.setBounds(110, 60, 70, 70);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel26.setText(": Rs.");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(660, 150, 73, 44);

        orepcost.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel3.add(orepcost);
        orepcost.setBounds(730, 240, 460, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel25.setText(": Rs.");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(660, 80, 73, 44);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Cost of other maintenances  ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(200, 230, 459, 40);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel28.setText(": Rs.");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(660, 380, 73, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Cost of vehicle repairs         ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(200, 80, 470, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel27.setText(": Rs.");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(660, 230, 73, 44);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel29.setText(": Rs.");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(660, 310, 73, 44);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/coin.png"))); // NOI18N
        jPanel3.add(jLabel24);
        jLabel24.setBounds(110, 370, 80, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/body.jpg"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 1640, 920);

        jLabel20.setText("jLabel19");
        jLabel20.setMinimumSize(new java.awt.Dimension(64, 64));
        jLabel20.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jLabel20);
        jLabel20.setBounds(140, 80, 40, 40);

        DesktopPane2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1600, 920);

        getContentPane().add(DesktopPane2);
        DesktopPane2.setBounds(320, 160, 1600, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Maintenance/images/homehover.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Maintenance/images/home.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        ImageIcon III = new ImageIcon(getClass().getResource("/Maintenance/images/homepressed.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        ImageIcon III = new ImageIcon(getClass().getResource("/Maintenance/images/home.png"));
        home.setIcon(III);
        DesktopPane2.removeAll();
        DesktopPane2.add(jPanel3);

        jPanel3.show();
    }//GEN-LAST:event_homeMouseReleased

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
        //        home1.setBackground(Color.BLUE);
    }//GEN-LAST:event_home1MouseEntered

    private void home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseExited
        //      home1.setBackground(Color.BLACK);
    }//GEN-LAST:event_home1MouseExited

    private void home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MousePressed
        //      home1.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_home1MousePressed

    private void home1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseReleased
        //      home1.setForeground(Color.BLACK);
    }//GEN-LAST:event_home1MouseReleased

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(Color.BLUE);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        logout.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        logout.setForeground(Color.BLACK);
        log = 0;
        Main.Main m = new Main.Main(0, null);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseReleased

    private void vehrepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehrepMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vehrepMouseClicked

    private void vehrepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehrepMouseEntered
        vehrep.setBackground(Color.BLUE);
    }//GEN-LAST:event_vehrepMouseEntered

    private void vehrepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehrepMouseExited
        vehrep.setBackground(Color.BLACK);
    }//GEN-LAST:event_vehrepMouseExited

    private void vehrepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehrepMousePressed
        vehrep.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_vehrepMousePressed

    private void vehrepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehrepMouseReleased
        vehrep.setForeground(Color.BLACK);
        DesktopPane2.removeAll();
        vehicles vi=new vehicles();
        DesktopPane2.add(vi).setVisible(true);
    }//GEN-LAST:event_vehrepMouseReleased

    private void buildrepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildrepMouseEntered
        buildrep.setBackground(Color.BLUE);
    }//GEN-LAST:event_buildrepMouseEntered

    private void buildrepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildrepMouseExited
        buildrep.setBackground(Color.BLACK);
    }//GEN-LAST:event_buildrepMouseExited

    private void buildrepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildrepMousePressed
        buildrep.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_buildrepMousePressed

    private void buildrepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildrepMouseReleased
        buildrep.setForeground(Color.BLACK);
        DesktopPane2.removeAll();
        buildings build=new buildings();
        DesktopPane2.add(build).setVisible(true);
    }//GEN-LAST:event_buildrepMouseReleased

    private void cleanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseEntered
        clean.setBackground(Color.BLUE);
    }//GEN-LAST:event_cleanMouseEntered

    private void cleanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseExited
        clean.setBackground(Color.BLACK);
    }//GEN-LAST:event_cleanMouseExited

    private void cleanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMousePressed
        clean.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_cleanMousePressed

    private void cleanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseReleased
        clean.setForeground(Color.BLACK);
        DesktopPane2.removeAll();
        cleaning cl=new cleaning();
        DesktopPane2.add(cl).setVisible(true);
    }//GEN-LAST:event_cleanMouseReleased

    private void othrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othrMouseEntered
        othr.setBackground(Color.BLUE);
    }//GEN-LAST:event_othrMouseEntered

    private void othrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othrMouseExited
        othr.setBackground(Color.BLACK);
    }//GEN-LAST:event_othrMouseExited

    private void othrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othrMousePressed
        othr.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_othrMousePressed

    private void othrMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othrMouseReleased
        othr.setForeground(Color.BLACK);
        DesktopPane2.removeAll();
        othermaintenance om=new othermaintenance();
        DesktopPane2.add(om).setVisible(true);
    }//GEN-LAST:event_othrMouseReleased

    private void frthrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frthrMouseEntered
        frthr.setBackground(Color.BLUE);
    }//GEN-LAST:event_frthrMouseEntered

    private void frthrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frthrMouseExited
        frthr.setBackground(Color.BLACK);
    }//GEN-LAST:event_frthrMouseExited

    private void frthrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frthrMousePressed
        frthr.setBackground(new Color(10, 122, 192));
    }//GEN-LAST:event_frthrMousePressed

    private void frthrMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frthrMouseReleased
        frthr.setForeground(Color.BLACK);
        DesktopPane2.removeAll();
        furtherconstructions fc=new furtherconstructions();
        DesktopPane2.add(fc).setVisible(true);
    }//GEN-LAST:event_frthrMouseReleased

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/minimize_hover.png"));
        minimize.setIcon(III);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/minimize.png"));
        minimize.setIcon(III);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        this.setState(main.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/close_hover.png"));
        close.setIcon(III);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/close.png"));
        close.setIcon(III);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    
        String showDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        return (s.format(d));
    }
    
        void showTime() {
        try {
            new Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Date d = new Date();
                    SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                    time.setText(s.format(d));
                }
            }
            ).start();
        } catch (Exception e) {
            System.out.print(e);
        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane2;
    private javax.swing.JLabel brepcost;
    private javax.swing.JPanel buildrep;
    private javax.swing.JPanel clean;
    private javax.swing.JLabel close;
    private javax.swing.JLabel frepcost;
    private javax.swing.JPanel frthr;
    private javax.swing.JLabel hallname;
    private javax.swing.JLabel home;
    private javax.swing.JPanel home1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel mainmenu;
    private javax.swing.JLabel mainmenuicon;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel orepcost;
    private javax.swing.JPanel othr;
    private javax.swing.JLabel ovel;
    private javax.swing.JLabel time;
    private javax.swing.JLabel title;
    private javax.swing.JLabel today;
    private javax.swing.JLabel total;
    private javax.swing.JLabel user;
    private javax.swing.JPanel vehrep;
    private javax.swing.JLabel vrepcost;
    // End of variables declaration//GEN-END:variables
}
