/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintenancemanagement;

import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import dbconnect.dbconnect;
import java.awt.Color;
import static java.awt.Color.red;
import static java.awt.Color.white;
//import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.Date;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Shihan
 */
public class vehicles extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String VehicleNmbr;
    String aa = null;
    maintenanceclass m = new maintenanceclass();

    public vehicles() {
        initComponents();
        con = dbconnect.connect();
        viewtable();
        viewtablerep();

    }

    public void viewtable() {
        String sqveh = "SELECT * FROM vehicledetails";

        try {
            pst = con.prepareStatement(sqveh);
            pst.execute();
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    public void viewtablerep() {
        String sqvehrep = "SELECT * FROM vehiclerepair";

        try {
            pst = con.prepareStatement(sqvehrep);
            pst.execute();
            rs = pst.executeQuery();
            vehiclereptable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        amnt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        vno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        vehiclereptable = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        vnoins = new javax.swing.JTextField();
        mke = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mdl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        typec = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        seats = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        printr = new javax.swing.JButton();
        printv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "VehicleNo", "Make", "Model", "Year", "Type", "No Of Seats"
            }
        ));
        jTable2.setFillsViewportHeight(true);
        jTable2.setPreferredSize(new java.awt.Dimension(450, 120));
        jTable2.setRowHeight(30);
        jTable2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 60, 890, 310);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Remove Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 10, 129, 40);

        updt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/update.png"))); // NOI18N
        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        getContentPane().add(updt);
        updt.setBounds(1210, 780, 120, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/add.png"))); // NOI18N
        jButton4.setText("Add Entry");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1370, 780, 130, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Repair Details");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1040, 410, 230, 40);

        des.setColumns(20);
        des.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        des.setRows(5);
        jScrollPane1.setViewportView(des);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1210, 610, 290, 100);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Amount : ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1040, 720, 120, 20);

        amnt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amnt.setText(" ");
        amnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amntActionPerformed(evt);
            }
        });
        amnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amntKeyPressed(evt);
            }
        });
        getContentPane().add(amnt);
        amnt.setBounds(1210, 720, 290, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Descreption :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1040, 610, 140, 22);
        getContentPane().add(date);
        date.setBounds(1210, 560, 290, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Date :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1040, 560, 90, 22);

        type.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Select Type------", "General Repair", "Damage", "Severe" }));
        getContentPane().add(type);
        type.setBounds(1210, 510, 290, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Repair Type :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1040, 510, 140, 22);

        vno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vno.setText(" ");
        vno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnoActionPerformed(evt);
            }
        });
        getContentPane().add(vno);
        vno.setBounds(1210, 460, 290, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Vehicle No :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1040, 460, 120, 22);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Update License/Insurance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 10, 250, 40);

        vehiclereptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EntryID", "VehicleNo", "RepairType", "Date", "Descreption", "Amount"
            }
        ));
        vehiclereptable.setFillsViewportHeight(true);
        vehiclereptable.setGridColor(new java.awt.Color(204, 204, 204));
        vehiclereptable.setRowHeight(30);
        vehiclereptable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        vehiclereptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehiclereptableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(vehiclereptable);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 470, 890, 340);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(190, 420, 190, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/search.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(390, 420, 120, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/clear.png"))); // NOI18N
        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(520, 419, 130, 41);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Vehicle No :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1030, 70, 110, 25);

        vnoins.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vnoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnoinsActionPerformed(evt);
            }
        });
        getContentPane().add(vnoins);
        vnoins.setBounds(1130, 70, 140, 40);

        mke.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(mke);
        mke.setBounds(1360, 70, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Model :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1030, 120, 80, 25);

        mdl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(mdl);
        mdl.setBounds(1130, 120, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Year :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1290, 120, 80, 25);

        year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearKeyPressed(evt);
            }
        });
        getContentPane().add(year);
        year.setBounds(1360, 120, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Make :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1290, 70, 80, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Type :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1030, 170, 80, 25);

        typec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Select Type-----", "Sedan ", "Saloon", "Multi Purpose Van", "Mini Van", "Passenger Van", "Lorry", "Cab", "Other" }));
        getContentPane().add(typec);
        typec.setBounds(1130, 170, 140, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Seats :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1290, 170, 80, 25);

        seats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seatsKeyPressed(evt);
            }
        });
        getContentPane().add(seats);
        seats.setBounds(1360, 170, 140, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/add.png"))); // NOI18N
        jButton2.setText("Add Vehicle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1360, 220, 140, 50);

        printr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printr.setText("Print repair details");
        printr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printrActionPerformed(evt);
            }
        });
        getContentPane().add(printr);
        printr.setBounds(680, 420, 240, 40);

        printv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printv.setText("Print vehicle details");
        printv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printvActionPerformed(evt);
            }
        });
        getContentPane().add(printv);
        printv.setBounds(680, 10, 240, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Vehicle Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1030, 20, 190, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Enter Vehicle No :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 420, 150, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maintenance/Images/body.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -6, 1600, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String vnmbr = vnoins.getText();
        String make = mke.getText();
        String model = mdl.getText();
        String yr = year.getText();
        String tyc = typec.getSelectedItem().toString();
        String seat = seats.getText();

        if (vnmbr.isEmpty() || make.isEmpty() || model.isEmpty() || yr.isEmpty() || tyc.isEmpty() || seat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        } else {

            int x = JOptionPane.showConfirmDialog(null, "Add Vehicle?");
            if (x == 0) {
                m.addvehicle(vnmbr, make, model, yr, tyc, seat);
            }
            viewtable();
            vnoins.setText("");
            mke.setText("");
            mdl.setText("");
            year.setText("");
            typec.setSelectedIndex(0);
            seats.setText("");
            year.setBackground(white);
            seats.setBackground(white);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vnoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnoinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnoinsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int x = JOptionPane.showConfirmDialog(null, "Do you want to remove a vehicle?");
        if (x == 0) {
            m.removevehicle(VehicleNmbr);

            viewtable();
            JOptionPane.showMessageDialog(null, "Vehicle removed!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();

        VehicleNmbr = jTable2.getValueAt(row, 0).toString();
    }//GEN-LAST:event_jTable2MouseClicked

    private void yearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyPressed
        int key = evt.getKeyCode();//validation
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE) {
            year.setEditable(true);
            year.setBackground(Color.white);
        } else {
            getToolkit().beep();
            year.setEditable(false);
            year.setBackground(red);

        }
    }//GEN-LAST:event_yearKeyPressed

    private void seatsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatsKeyPressed
        int key = evt.getKeyCode();//validation
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE) {
            seats.setEditable(true);
            seats.setBackground(Color.white);
        } else {
            getToolkit().beep();
            seats.setEditable(false);
            seats.setBackground(red);

        }
    }//GEN-LAST:event_seatsKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        licenseandinsurance ln = new licenseandinsurance();
        ln.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void vnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnoActionPerformed

    private void amntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amntActionPerformed

    private void amntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amntKeyPressed
        int key = evt.getKeyCode();//validation
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE) {
            amnt.setEditable(true);
            amnt.setBackground(Color.white);
        } else {
            getToolkit().beep();
            amnt.setEditable(false);
            amnt.setBackground(red);

        }
    }//GEN-LAST:event_amntKeyPressed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        String vehno = vno.getText();
        String ty = type.getSelectedItem().toString();

        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        String dscrptn = des.getText();

        String amount = amnt.getText();

        if (vehno.isEmpty() || ty.isEmpty() || df == null || dscrptn.isEmpty() || amount.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        } else {
            Date repdate;
            repdate = date.getDate();
            String repdte = df.format(repdate);

            m.updaterepair(vehno, ty, repdte, dscrptn, amount, aa);

            viewtablerep();
            vno.setText("");
            type.setSelectedIndex(0);
            des.setText("");
            date.setDate(null);
            amnt.setText("");
            JOptionPane.showMessageDialog(null, "Entry Updated!");
            amnt.setBackground(white);
        }
    }//GEN-LAST:event_updtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String vehno = vno.getText();
        String ty = type.getSelectedItem().toString();

        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        String dscrptn = des.getText();

        String amount = amnt.getText();
        if (vehno.isEmpty() || ty.isEmpty() || df == null || dscrptn.isEmpty() || amount.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Information Required, Please fill!");
        } else {
            int x = JOptionPane.showConfirmDialog(null, "Proceed?");
            if (x == 0) {
                Date repdate;
                repdate = date.getDate();
                String repdte = df.format(repdate);

                m.addrepair(vehno, ty, repdte, dscrptn, amount);
            }
            viewtablerep();
            vno.setText("");
            type.setSelectedIndex(0);
            des.setText("");
            date.setDate(null);
            amnt.setText("");
            amnt.setBackground(white);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void vehiclereptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclereptableMouseClicked
        try {
            int row = vehiclereptable.getSelectedRow();//select items to the fields
            aa = vehiclereptable.getModel().getValueAt(row, 0).toString();
            String a = "select * from vehiclerepair where EntryID='" + aa + "'";
            pst = con.prepareStatement(a);
            rs = pst.executeQuery();
            if (rs.next()) {
                vno.setText(rs.getString("VehicleNo"));
                type.setSelectedItem(rs.getString("RepairType"));
                date.setDate(rs.getDate("Date"));
                des.setText(rs.getString("Descreption"));
                amnt.setText(rs.getString("Amount"));
            }
        } catch (Exception ex) {
            System.out.println(ex);
            //Logger.getLogger(vehiclerepair.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_vehiclereptableMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String vnmbr = search.getText();
        String sql = "SELECT * FROM vehiclerepair WHERE VehicleNo LIKE '%" + vnmbr + "%'";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            vehiclereptable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        viewtablerep();
        search.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void printvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printvActionPerformed
        try {
            String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\vehicles.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(rep);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_printvActionPerformed

    private void printrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printrActionPerformed
        String vname =search.getText();
        if (vname.isEmpty()) {
        try {
            String rep = "C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\vehiclerepair.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(rep);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
        else {
            try {

                JasperDesign jd = JRXmlLoader.load("C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\vehiclerepair.jrxml");
                String sql = "select * from vehiclerepair where VehicleNo like '%" + vname + "%'";
                JRDesignQuery n1 = new JRDesignQuery();
                n1.setText(sql);
                jd.setQuery(n1);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_printrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amnt;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextArea des;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField mdl;
    private javax.swing.JTextField mke;
    private javax.swing.JButton printr;
    private javax.swing.JButton printv;
    private javax.swing.JTextField search;
    private javax.swing.JTextField seats;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> typec;
    private javax.swing.JButton updt;
    private javax.swing.JTable vehiclereptable;
    private javax.swing.JTextField vno;
    private javax.swing.JTextField vnoins;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
