package Resturant;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import dbconnect.dbconnect;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sulakshana
 */
public class addmenu extends javax.swing.JInternalFrame {

   Connection conn = null;
  PreparedStatement pst = null;
  
  ResultSet rs = null;   //get data base data and save all data in re variable
 String id_;
    public addmenu() {
        initComponents();
        
          conn = dbconnect.connect();//connect to Db when page is open
           
           
            //this.getContentPane().setBackground(Color.white);
           tableload();//load table
        
            
    }
    
   public void tableload()//mrthod for gat data nto table
    {
        try {
             String sql = "SELECT Name,Item_code,Discription,Price FROM menu ";   //get values from table addstudnt
        pst=conn.prepareStatement(sql); 
        
      rs=  pst.executeQuery();  //to eexecute Query and result save in rs 
      
      jTable1.setModel(DbUtils.resultSetToTableModel(rs));
      
      
      
      
        } catch (Exception e) {
        }
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        itemcode = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        discription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 920));
        setPreferredSize(new java.awt.Dimension(1600, 920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 100, 40));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 1040, 450));

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel5.setText("Add Menu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 190, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Price");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Discription");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Item code");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(itemcode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(discription, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 380, 450));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/body.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // assign form textfeild inputs to these String variables,,  green text is form feild variable names
        String namefeild = name.getText();
        // String itemcodefeild=itemcode.getText();
        String discriptionfeild = discription.getText();
        String pricefeild=price.getText(); // after assign input to this variable ,,it converts into string value

        if((namefeild.compareTo("")!=0)&&(discriptionfeild.compareTo("")!=0)&&(pricefeild.compareTo("")!=0))
        {
            int d=  JOptionPane.showConfirmDialog(null,"Do you really want to Delete? ");  // if you select
            // yes-->>>it will get that as 0
            // if you select
            // No-->>>it will get that as 1
            // if you select
            // cancel-->>>it will get that as 2

            if(d==0)
            {
                //  String  namee = name.getText();
                String itemcode_ = itemcode.getText();
                //  String  facultyy = faculty.getText();
                //   String  batchh = batch.getText();

                String sql = "DELETE FROM menu where Item_code='"+itemcode_+"'    ";

                try {
                    pst=conn.prepareStatement(sql);
                    pst.execute();
                    tableload();//load table

                } catch (Exception ex) {

                }

            }
            name.setText("");
            itemcode.setText("");
            discription.setText("");
            price.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null,"Select Menu Item To Delete! ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // assign form textfeild inputs to these String variables,,  green text is form feild variable names
        String namefeild = name.getText();
        // String itemcodefeild=itemcode.getText();
        String discriptionfeild = discription.getText();
        String pricefeild=price.getText(); // after assign input to this variable ,,it converts into string value

        if((namefeild.compareTo("")!=0)&&(discriptionfeild.compareTo("")!=0)&&(pricefeild.compareTo("")!=0))
        {
            int x=  JOptionPane.showConfirmDialog(null,"Do you really want to Update? ");  // if you select
            // yes-->>>it will get that as 0
            // if you select
            // No-->>>it will get that as 1
            // if you select
            // cancel-->>>it will get that as 2

            if(x==0)
            {
                String  namee = name.getText();
                String itemcode_ = itemcode.getText();
                String  discription_ = discription.getText();
                String  price_ = price.getText();
                //int Itemcode = Integer.parseInt(rs.getString("Item_code"));
                /* if((itemcode_.startsWith("E")))
                {

                }
                else{
                    JOptionPane.showMessageDialog(null, "Enter a item code start with E");
                }*/
                if((price_.matches("[0-9]+")))
                {

                    String sql = "UPDATE menu SET Name = '"+namee+"',   Discription= '"+discription_+"' ,Price= '"+price_+"' WHERE  Item_code ='"+itemcode_+"'  "; // concat
                    try {
                        pst=conn.prepareStatement(sql);
                        pst.execute();

                        tableload();//load table
                    } catch (Exception ex) {

                    }

                }

                else{
                    JOptionPane.showMessageDialog(null, "Enter a number");
                }

            }
            name.setText("");
            //itemcode.setText("");
            discription.setText("");
            price.setText("");

        }
        else{
            JOptionPane.showMessageDialog(null,"Select Menu Item To Update! ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //image will get when u click on table tuple

        int r = jTable1.getSelectedRow();

        String name_ = jTable1.getValueAt(r, 0) .toString();   // r is selected row ,0 is 0 th col
        String itemcode_ = jTable1.getValueAt(r, 1) .toString();
        String discription_ = jTable1.getValueAt(r, 2) .toString();      //assign select table row and col
        String price_ = jTable1.getValueAt(r, 3) .toString();

        name.setText(name_);
        itemcode.setText(itemcode_);
        discription.setText(discription_);
        price.setText(price_);       // set values for each and every text feilds
    }//GEN-LAST:event_jTable1MouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        //Clear button

        name.setText("");
        itemcode.setText("");
        discription.setText("");
        price.setText("");
        //jPasswordField1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // assign form textfeild inputs to these String variables,,  green text is form feild variable names
        String namefeild = name.getText();
        // String itemcodefeild=itemcode.getText();
        String discriptionfeild = discription.getText();
        String pricefeild=price.getText(); // after assign input to this variable ,,it converts into string value

        if((namefeild.compareTo("")!=0)&&(discriptionfeild.compareTo("")!=0)&&(pricefeild.compareTo("")!=0))
        {

            // if((itemcodefeild.startsWith("E")))
            // {
                if((pricefeild.matches("[0-9]+")))
                {
                    try{

                        String DB = "INSERT INTO menu (Name,Discription,Price) values('" +namefeild+ "'  , '" +discriptionfeild+ "' , '" +pricefeild+ "'  )";//concat method//in java  to input values to a db
                        pst=conn.prepareStatement(DB);
                        pst.execute();
                        //load table after every insert
                        tableload();//load table

                    }
                    catch(Exception x )
                    {
                        // JOptionPane.showMessageDialog(null, "Error");
                    }
                }

                else{
                    JOptionPane.showMessageDialog(null, "Enter a number");
                }
                //}

        }
        //((itemcodefeild.startsWith("E")))
        // if
        //  {
            //  JOptionPane.showMessageDialog(null, "Forum is complete");
            //
            // }

        else
        {
            JOptionPane.showMessageDialog(null, "Forum is incomplete");
        }
        name.setText("");

        discription.setText("");
        price.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        int key=evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD0) ||key==KeyEvent.VK_BACK_SPACE)

        {
            price.setEditable(true);
            price.setBackground(Color.white);
        }
        else
        {
            getToolkit().beep();
            price.setEditable(false);
            price.setBackground(Color.red);
        }
    }//GEN-LAST:event_priceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTextField discription;
    private javax.swing.JLabel itemcode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
