package Resturant;

import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sulakshana
 */
public class contactmaininventory_ extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;

    ResultSet rs = null;   //get data base data and save all data in re variable

    java.util.Date date;
    java.sql.Date sqldate;

    public contactmaininventory_() {
        initComponents();

        conn = dbconnect.connect(); //connect to Db when page is open

        tableload();//load table 

    }



    public String currentday() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int yr = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        return (yr + "-" + (month + 1) + "-" + day);

    }
    public void insert_date() {
        try {
            conn = DBconnectionNew.connect(); //connect to Db when page is open
            date = Date.getDate();
            sqldate = new java.sql.Date(date.getTime());

            String sql = "INSERT into eventorder(requiredDate) values('" + sqldate + "') ";
            pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, x);
        }
    }
    
    
    
    public void tableload()//mrthod for gat data nto table
    {
        try {
            
             
            String sql = "SELECT ItemId,ItemName  FROM rawmaterials where Status='Good' OR Status='Today Expire' OR Status='Ex 1 Day' OR Status='Ex 2 Days'";  //get values from table viewitemlist
             
            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();  //to eexecute Query and result save in rs 

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println("HEllo");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        searchItem = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        Date = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 810, 370));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Search by Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, -1, -1));
        jPanel1.add(searchItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 220, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search.png"))); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, 130, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Restaurant", "Wedding", "Party" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Type");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Quantity");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 340, 420));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("Send Order ->");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 120, 200, 27));

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/body.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 870));

        jLabel9.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel9.setText("Contact Main Inventory");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 22, 390, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //send
        // assign form textfeild inputs to these String variables,,  green text is form feild variable names
        DateFormat dx = new SimpleDateFormat("yyyy-MM-dd");
        Date day_;
        day_ = Date.getDate();
        String date = dx.format(day_);

        String idfeild = id.getText();
        String quntity = qty.getText();
        String namefeild = name1.getText();
        String selected = jComboBox1.getSelectedItem().toString();
        String abc = currentday();
        
        // after assign input to this variable ,,it converts into string value

        if ((idfeild.compareTo("") != 0) && (quntity.compareTo("") != 0) && (namefeild.compareTo("") != 0))  {

           
                if(selected.equals("Wedding")||selected.equals("Party"))
                {
                    //if ((quntity.matches("[0-700]"))) {
                        try {

                            String DB = "INSERT INTO eventorder (ItemId,ItemName,Qty,Date,RequiredDate,Type,Status) values('" + idfeild + "'  , '" + namefeild + "' , '" + quntity + "' ,'" + abc + "' ,'" + date + "' ,'"+selected+"','Not send' )";//concat method//in java  to input values to a db
                            pst = conn.prepareStatement(DB);
                            pst.execute();
                            //load table after every insert
                            // tableload();//load table
                            //insert_date();
                        } catch (Exception x) {
                            //JOptionPane.showMessageDialog(null,x);
                        }
                      JOptionPane.showMessageDialog(null, "Order Sent");
                    }
                 else{

              //  if ((quntity.matches("[0-700]"))) {
                    try {

                        String DB1 = "INSERT INTO dailyorder (ItemId,ItemName,Qty,Date,RequiredDate,Type,Status) values('" + idfeild + "'  , '" + namefeild + "' , '" + quntity + "' ,'" + abc + "' ,'" + date + "','Restaurant','Not send'  )";//concat method//in java  to input values to a db
                        pst = conn.prepareStatement(DB1);
                        pst.execute();
                        //load table after every insert
                        // tableload();//load table
                       // insert_date();
                    } catch (Exception x) {
                        //JOptionPane.showMessageDialog(null,x);
                    }
              
                     JOptionPane.showMessageDialog(null, "Order Sent");
               
            }

                
            }
           else{
            JOptionPane.showMessageDialog(null,"Select Menu Item To Update! ");
        }
            //((itemcodefeild.startsWith("E")))
            // if
            //  {
                //  JOptionPane.showMessageDialog(null, "Forum is complete");
                //
                // }
            //  else {
                //      JOptionPane.showMessageDialog(null, "Forum is incomplete");
                //  }

            id.setText("");
            name1.setText("");
            qty.setText("");
            Date.setDate(null);

       // }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String IDD =searchItem.getText();

        String sql = "SELECT  ItemId,ItemName FROM rawmaterials  where ItemName LIKE '%"+ IDD +"%'   "    ;

        try {
            pst=conn.prepareStatement(sql);

            rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            //  tableload();//load table

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r = jTable1.getSelectedRow();

        String itemid_ = jTable1.getValueAt(r, 0).toString();   // r is selected row ,0 is 0 th col
        String name_ = jTable1.getValueAt(r, 1).toString();
        // String discription_ = jTable1.getValueAt(r, 2) .toString();      //assign select table row and col
        // String price_ = jTable1.getValueAt(r, 3) .toString();

        name1.setText(name_);
        id.setText(itemid_);
        // set values for each and every text feilds

        //
    }//GEN-LAST:event_jTable1MouseClicked

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        
         int key=evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD0) ||key==KeyEvent.VK_BACK_SPACE)

        {
            qty.setEditable(true);
            qty.setBackground(Color.white);
        }
        else
        {
            getToolkit().beep();
            qty.setEditable(false);
            qty.setBackground(Color.red);
        }
    }//GEN-LAST:event_qtyKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField searchItem;
    // End of variables declaration//GEN-END:variables
}
