package Resturant;



import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUNESH
 */
public class InventoryMain extends javax.swing.JFrame {

      Connection conn = null;
    PreparedStatement pst = null;
    
    ResultSet rs = null; 
    
    public InventoryMain() {
        initComponents();
        conn = DBconnectionNew.connect(); //connect to Db when page is open
        party();
    }
  public String currentday() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int yr = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        return (yr + "-" + (month + 1) + "-" + day);

    }
    
    
     public void party() {
        String today = currentday();
        try {
            String sql = "SELECT * FROM event_booking";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
                if (rs.next()) {
                   
                    
                    ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/equipmenthandling_msg.png"));
                    jLabel10.setIcon(III);
                } else {
                 
                    ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/equipmenthandling.png"));
                    jLabel10.setIcon(III);
                }
            
        } catch (Exception e) {
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hallname = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ovel = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home1 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ehandling = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainmenu = new javax.swing.JLabel();
        mainmenuicon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        estock = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        purchasing = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        supplier = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        hallname.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        hallname.setForeground(new java.awt.Color(255, 255, 255));
        hallname.setText("RAVINDRA RECEPTION HALL");
        jPanel1.add(hallname);
        hallname.setBounds(660, 40, 580, 50);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Resturant Main");
        jPanel1.add(title);
        title.setBounds(860, 110, 170, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(170, 22, 1580, 10);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.setText(" ");
        jPanel1.add(logo);
        logo.setBounds(10, 10, 200, 160);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(230, 92, 1460, 10);

        ovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/logoutback.png"))); // NOI18N
        ovel.setText(" ");
        jPanel1.add(ovel);
        ovel.setBounds(1740, 30, 100, 100);

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setIcon(new javax.swing.ImageIcon("C:\\Users\\MUNESH\\Desktop\\tharanga.jpg")); // NOI18N
        user.setText(" ");
        user.setOpaque(true);
        jPanel1.add(user);
        user.setBounds(1740, 30, 100, 100);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("S.T. Pathiratne");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(name);
        name.setBounds(1750, 140, 120, 20);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/minimize.png"))); // NOI18N
        minimize.setText(" ");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(1840, 10, 40, 32);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/close.png"))); // NOI18N
        close.setText(" ");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1880, 10, 40, 32);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 160);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(320, 1080));
        jPanel2.setLayout(null);

        home1.setBackground(new java.awt.Color(0, 0, 0));
        home1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                home1MouseReleased(evt);
            }
        });
        home1.setLayout(null);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/home.png"))); // NOI18N
        home.setText(" ");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        home1.add(home);
        home.setBounds(130, 0, 70, 70);

        jPanel2.add(home1);
        home1.setBounds(0, 230, 320, 70);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        logout.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");
        logout.add(jLabel7);
        jLabel7.setBounds(120, 20, 80, 22);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/logout.png"))); // NOI18N
        jLabel21.setText(" ");
        logout.add(jLabel21);
        jLabel21.setBounds(10, 0, 64, 64);

        jPanel2.add(logout);
        logout.setBounds(0, 980, 320, 70);

        ehandling.setBackground(new java.awt.Color(0, 0, 0));
        ehandling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ehandling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ehandlingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ehandlingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ehandlingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ehandlingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ehandlingMouseReleased(evt);
            }
        });
        ehandling.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("   Cashier");
        ehandling.add(jLabel5);
        jLabel5.setBounds(73, 23, 75, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/currency.png"))); // NOI18N
        jLabel6.setText(" ");
        ehandling.add(jLabel6);
        jLabel6.setBounds(10, 0, 64, 64);

        jPanel2.add(ehandling);
        ehandling.setBounds(0, 340, 320, 70);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 160, 320, 2);

        mainmenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainmenu.setForeground(new java.awt.Color(255, 255, 255));
        mainmenu.setText("MAIN MENU");
        jPanel2.add(mainmenu);
        mainmenu.setBounds(100, 170, 130, 30);

        mainmenuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/red.png"))); // NOI18N
        mainmenuicon.setText(" ");
        jPanel2.add(mainmenuicon);
        mainmenuicon.setBounds(10, 170, 32, 32);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 210, 320, 2);

        estock.setBackground(new java.awt.Color(0, 0, 0));
        estock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estockMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                estockMouseReleased(evt);
            }
        });
        estock.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  Event Details");
        estock.add(jLabel9);
        jLabel9.setBounds(80, 20, 210, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/equipment.png"))); // NOI18N
        jLabel10.setText(" ");
        estock.add(jLabel10);
        jLabel10.setBounds(10, 0, 64, 64);

        jPanel2.add(estock);
        estock.setBounds(0, 430, 320, 70);

        purchasing.setBackground(new java.awt.Color(0, 0, 0));
        purchasing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purchasing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                purchasingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                purchasingMouseReleased(evt);
            }
        });
        purchasing.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("  KOT Orders");
        purchasing.add(jLabel13);
        jLabel13.setBounds(80, 20, 163, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/waiter.png"))); // NOI18N
        jLabel14.setText(" ");
        purchasing.add(jLabel14);
        jLabel14.setBounds(10, 0, 64, 64);

        jPanel2.add(purchasing);
        purchasing.setBounds(0, 520, 320, 70);

        supplier.setBackground(new java.awt.Color(0, 0, 0));
        supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supplierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                supplierMouseReleased(evt);
            }
        });
        supplier.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("  Report");
        supplier.add(jLabel15);
        jLabel15.setBounds(80, 20, 163, 22);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/equipmenthandling.png"))); // NOI18N
        jLabel22.setText(" ");
        supplier.add(jLabel22);
        jLabel22.setBounds(10, 0, 64, 64);

        jPanel2.add(supplier);
        supplier.setBounds(0, 610, 320, 70);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 1080);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1596, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jDesktopPane1);
        jDesktopPane1.setBounds(320, 160, 1600, 920);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ehandlingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseEntered
        ehandling.setBackground(Color.BLUE);
    }//GEN-LAST:event_ehandlingMouseEntered

    private void ehandlingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseExited
        ehandling.setBackground(Color.BLACK);
    }//GEN-LAST:event_ehandlingMouseExited

    private void ehandlingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMousePressed
        ehandling.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_ehandlingMousePressed

    private void ehandlingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseReleased
        ehandling.setForeground(Color.BLACK);
    }//GEN-LAST:event_ehandlingMouseReleased

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
//        home1.setBackground(Color.BLUE);
    }//GEN-LAST:event_home1MouseEntered

    private void home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseExited
  //      home1.setBackground(Color.BLACK);
    }//GEN-LAST:event_home1MouseExited

    private void home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MousePressed
  //      home1.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_home1MousePressed

    private void home1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseReleased
  //      home1.setForeground(Color.BLACK);
    }//GEN-LAST:event_home1MouseReleased

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(Color.BLUE);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
         logout.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
         logout.setForeground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseReleased

    private void supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseEntered
        supplier.setBackground(Color.BLUE);
    }//GEN-LAST:event_supplierMouseEntered

    private void supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseExited
        supplier.setBackground(Color.BLACK);
    }//GEN-LAST:event_supplierMouseExited

    private void supplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMousePressed
       supplier.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_supplierMousePressed

    private void supplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseReleased
       supplier.setForeground(Color.BLACK);
    }//GEN-LAST:event_supplierMouseReleased

    private void estockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseEntered
        estock.setBackground(Color.BLUE);
    }//GEN-LAST:event_estockMouseEntered

    private void estockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseExited
        estock.setBackground(Color.BLACK);
    }//GEN-LAST:event_estockMouseExited

    private void estockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMousePressed
        estock.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_estockMousePressed

    private void estockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseReleased
        estock.setForeground(Color.BLACK);
    }//GEN-LAST:event_estockMouseReleased

    private void purchasingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseEntered
        purchasing.setBackground(Color.BLUE);
    }//GEN-LAST:event_purchasingMouseEntered

    private void purchasingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseExited
        purchasing.setBackground(Color.BLACK);
    }//GEN-LAST:event_purchasingMouseExited

    private void purchasingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMousePressed
        purchasing.setBackground(new Color(10,122,192));
    }//GEN-LAST:event_purchasingMousePressed

    private void purchasingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseReleased
         purchasing.setForeground(Color.BLACK);
    }//GEN-LAST:event_purchasingMouseReleased

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/homehover.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/home.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/homepressed.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/home.png"));
        home.setIcon(III);
    }//GEN-LAST:event_homeMouseReleased

    private void ehandlingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehandlingMouseClicked
             jDesktopPane1.removeAll();
       resturantmainpage_ rest = new resturantmainpage_();
       jDesktopPane1.add(rest).setVisible(true);
        
    }//GEN-LAST:event_ehandlingMouseClicked

    private void estockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estockMouseClicked
            jDesktopPane1.removeAll();
       menuorderedbyeventmanagement_ event = new menuorderedbyeventmanagement_();
       jDesktopPane1.add(event).setVisible(true);
    }//GEN-LAST:event_estockMouseClicked

    private void supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseClicked
           jDesktopPane1.removeAll();
       reportgenarate_ reportgenarate = new reportgenarate_();
       jDesktopPane1.add(reportgenarate).setVisible(true);
    }//GEN-LAST:event_supplierMouseClicked

    private void purchasingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseClicked
         jDesktopPane1.removeAll();
       kot_ kot__ = new kot_();
       jDesktopPane1.add(kot__).setVisible(true);
    }//GEN-LAST:event_purchasingMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/minimize_hover.png"));
        minimize.setIcon(III);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/minimize.png"));
        minimize.setIcon(III);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        this.setState(InventoryMain.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/close_hover.png"));
        close.setIcon(III);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon III = new ImageIcon(getClass().getResource("/Inventory/imgs/close.png"));
        close.setIcon(III);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
     // kitchen manager 
     
     int x=JOptionPane.showConfirmDialog(null,"Do you want to proceed to the Kitchen Main page");
     
     if(x==0)
     {
     kitchen_ kitchennew = new kitchen_();
     kitchennew.setVisible(true);
     this.dispose();
     
     }
     
     
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryMain().setVisible(true);
//                try {
//                    UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(InventoryMain.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (InstantiationException ex) {
//                    Logger.getLogger(InventoryMain.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IllegalAccessException ex) {
//                    Logger.getLogger(InventoryMain.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (UnsupportedLookAndFeelException ex) {
//                    Logger.getLogger(InventoryMain.class.getName()).log(Level.SEVERE, null, ex);
//                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JPanel ehandling;
    private javax.swing.JPanel estock;
    private javax.swing.JLabel hallname;
    private javax.swing.JLabel home;
    private javax.swing.JPanel home1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel mainmenu;
    private javax.swing.JLabel mainmenuicon;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel ovel;
    private javax.swing.JPanel purchasing;
    private javax.swing.JPanel supplier;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
