package Resturant;

import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sulakshana
 */
public class kotOrderItemAdd extends javax.swing.JInternalFrame {

      Connection conn = null;
  PreparedStatement pst = null;
  
  ResultSet rs = null;   //get data base data and save all data in re variable

    String a2=null,a3=null;
    public kotOrderItemAdd() {
        initComponents();
        
          conn = dbconnect.connect();//connect to Db when page is open
           tableload();//load table
    }
    
    
    public kotOrderItemAdd(String b,String c) {
        initComponents();
       // a1=a;
       a2=b;
         a3=c;
         
          conn = dbconnect.connect();//connect to Db when page is open
           tableload();//load table
           
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    
     public String currentday() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int yr = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        return (yr + "-" + (month + 1) + "-" + day);

    }
      public void tableload()//mrthod for gat data nto table
    {
        try {
               String sql = "SELECT Item_code,Name FROM menu";  //get values from table viewitemlist
        pst=conn.prepareStatement(sql); 
        
      rs=  pst.executeQuery();  //to eexecute Query and result save in rs 
      
      kot item = new kot();
       //  item.table123.setModel(DbUtils.resultSetToTableModel(rs));

      
      
      
      
        } catch (Exception e) 
            
   
        {
System.out.println("HEllo");            
        }
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchitem_ = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(710, 350));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel5.setText("Add & Edit Items");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));
        jPanel1.add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 200, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Item Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        jPanel1.add(itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
        });
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 120, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Apply(F11)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 130, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 100, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 650, 180));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 100, 70, -1));
        jPanel1.add(searchitem_, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // assign form textfeild inputs to these String variables,,  green text is form feild variable names
         kot item = new kot();
         
         String abc = currentday();
        
     //  String cusname_ = a1;
       String waitername_=a2;
       String tableno_ = a3;
         /*jComboBox1.getSelectedItem().toString();*/
        //String kot__q = item.kotno12.getText();
        
        
        String itemcodefeild=itemcode.getText();
        String namefeild = itemname.getText();
        String qtyfeild = qty.getText();
        
       
         
       // String pricefeild=price.getText(); // after assign input to this variable ,,it converts into string value

       if((namefeild.compareTo("")!=0)&&(itemcodefeild.compareTo("")!=0)&&(qtyfeild.compareTo("")!=0))
       {

           // if((itemcodefeild.startsWith("E")))
           // {
               // if((qtyfeild.matches("[0-700]+")))
                 //   {
                try{

                    String DB = "INSERT INTO  kot_orders(Date,WaiterName,TableNo,ItemCode,ItemName,qty) values('" + abc + "'  , '" +waitername_+ "' , '" +Integer.parseInt(tableno_)+ "' ,'" +itemcodefeild+ "','" +namefeild+ "','" +qtyfeild+ "')";//concat method//in java  to input values to a db
                    pst=conn.prepareStatement(DB);
                    pst.execute();
                    //load table after every insert
                    item.tableload();//load table
                        
                    
                      JOptionPane.showMessageDialog(null, "Order send to the Kitchen");
                    
                   }
                catch(Exception x )
                {
                    JOptionPane.showMessageDialog(null, x);
                }
                    }

            else{
                JOptionPane.showMessageDialog(null, "Fill the form");
                }
            
           // else
            //    {
            //    JOptionPane.showMessageDialog(null, "Enter a item code start with E");
                //}

           
        //}
        //((itemcodefeild.startsWith("E")))
        // if
        //  {
            //  JOptionPane.showMessageDialog(null, "Forum is complete");
            //
            // }

       // else
      //  {
       //     JOptionPane.showMessageDialog(null, "Forum is incomplete");
       // }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          String IDD =searchitem_.getText();
        
        String sql = "SELECT Item_code,Name FROM menu  where Name LIKE '%"+ IDD +"%'   "    ;
        
        
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
               jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
               //  tableload();//load table
            
            
        } catch (Exception ex) {
          
        }  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
           int r = jTable1.getSelectedRow();

        String itemcode__ = jTable1.getValueAt(r, 0) .toString();   // r is selected row ,0 is 0 th col
        String name_ = jTable1.getValueAt(r, 1) .toString();
      //  String discription_ = jTable1.getValueAt(r, 2) .toString();      //assign select table row and col
      //  String price_ = jTable1.getValueAt(r, 3) .toString();

        itemname.setText(name_);
        itemcode.setText(itemcode__);
      //  discription.setText(discription_);
      //  price.setText(price_);       // set values for each and every text feilds
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP   )
        {
             int r = jTable1.getSelectedRow();

        String name_ = jTable1.getValueAt(r, 0) .toString();   // r is selected row ,0 is 0 th col
        String itemcode__ = jTable1.getValueAt(r, 1) .toString();
      //  String discription_ = jTable1.getValueAt(r, 2) .toString();      //assign select table row and col
      //  String price_ = jTable1.getValueAt(r, 3) .toString();

        itemname.setText(name_);
        itemcode.setText(itemcode__);
      //  discription.setText(discription_);
      //  price.setText(price_);       // set values for each and every text feilds
        
        }

        
        
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
                int key=evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD0) ||key==KeyEvent.VK_BACK_SPACE)
            
        {
            qty.setEditable(true);
            qty.setBackground(Color.white);
        }
        else
        {
            getToolkit().beep();
            qty.setEditable(false);
            qty.setBackground(Color.red);
        }
    }//GEN-LAST:event_qtyKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField itemcode;
    private javax.swing.JTextField itemname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField searchitem_;
    // End of variables declaration//GEN-END:variables
}
