package Resturant;

import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sulakshana
 */
public class reportgenarate_ extends javax.swing.JInternalFrame {

 Connection conn = null;
  PreparedStatement pst = null;
  
  ResultSet rs = null;   //get data base data and save all data in re variable

    public reportgenarate_() {
        initComponents();
        
         conn = dbconnect.connect();//connect to Db when page is open
         
           //this.getContentPane().setBackground(Color.white);
          // tableload();//load table
    }
   
   public void tableload()//mrthod for gat data nto table
    {
        try {
            //String date_ =datesearch.getText();
             DateFormat dx = new SimpleDateFormat("yyyy-MM-dd");
                 Date day_;
        day_ = jDateChooser1.getDate();
        String date = dx.format(day_);
            
             String sql = "SELECT date    FROM bill_info  where date LIKE '%"+ date +"%'   "    ;  //get values from table addstudnt
        pst=conn.prepareStatement(sql); 
        
      rs=  pst.executeQuery();  //to eexecute Query and result save in rs 
      
      jTable1.setModel(DbUtils.resultSetToTableModel(rs));
      
      
      
      
        } catch (Exception e) {
        }
           
        
    }
   
    public void tableload1()//mrthod for gat data nto table
    {
        try {
                String IDD =billid__.getText();
             String sql = "SELECT BillID,date,total,payment,itemname,itemcode,qty FROM bill_info where BillID LIKE '%"+ IDD +"%'";   //get values from table addstudnt
        pst=conn.prepareStatement(sql); 
        
      rs=  pst.executeQuery();  //to eexecute Query and result save in rs 
      
      jTable2.setModel(DbUtils.resultSetToTableModel(rs));
      
      
      
      
        } catch (Exception e) {
        }
           
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        billid__ = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 153));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 100, 80));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel6.setText("Report Generate");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 390, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Net income of the day");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 67, 270, 27));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 960, 180));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 162, 180, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Check Daily Actiyity");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 260, 50));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 79, 27));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("I report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/body.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 260));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Search By Bill Number");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 134, 240, 56));

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Date", "Total", "Payment", "Item Name", "Item Code", "Qty"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 13, 959, 204));

        billid__.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                billid__KeyPressed(evt);
            }
        });
        jPanel2.add(billid__, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 76, 90, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("I report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1485, 457, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/imgs/body.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 590));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1590, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
           // String date_ =datesearch.getText();
         DateFormat dx = new SimpleDateFormat("yyyy-MM-dd");
        Date day_;
        day_ = jDateChooser1.getDate();
        String date = dx.format(day_);

            
        
        if((date.compareTo("")!=0))
        {
        String sql = "SELECT date, sum(total) as Total  FROM bill_info  where date LIKE '%"+ date +"%'  group by date "    ;
        
        
        
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
               jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next())
            {
            String e = rs.getString("Total");
            System.out.print(e);
                //tableload();//load table
            System.out.println("fill");
            }
        }
        catch (Exception ex) {
          System.out.println(ex);
        } 
        
        }
        else
            {
            System.out.println("fill");
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
           
           String IDD =billid__.getText();
        
        String sql = "SELECT BillID,date,total,payment,itemname,itemcode,qty FROM bill_info where BillID LIKE '%"+ IDD +"%'   "    ;
        
        
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
               jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            
            
              tableload1();//load table
            
            
        } catch (Exception ex) {
          
        } 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void billid__KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billid__KeyPressed
       
              int key=evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD0) ||key==KeyEvent.VK_BACK_SPACE)
            
        {
            billid__.setEditable(true);
            billid__.setBackground(Color.white);
        }
        else
        {
            getToolkit().beep();
            billid__.setEditable(false);
            billid__.setBackground(Color.red);
        }
    }//GEN-LAST:event_billid__KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String rep="C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\Netincome.jrxml";
            JasperReport jr=JasperCompileManager.compileReport(rep);
            JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            String rep="C:\\Users\\MUNESH\\Documents\\NetBeansProjects\\itp_new_template\\ireport\\Billinfo.jrxml";
            JasperReport jr=JasperCompileManager.compileReport(rep);
            JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billid__;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
