package Resturant;

import dbconnect.dbconnect;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sulakshana
 */

public class resturantmainpage_ extends javax.swing.JInternalFrame {
    String TabN=null;
    double Total=0;
    Connection conn = null;
    PreparedStatement pst = null;
   
double amount = 0;
    ResultSet rs = null;   //get data base data and save all data in re variable
    //double sum;

    int tabno;
 String names[]=new String[5];
 int i=0;
 
    
    public resturantmainpage_() {
        initComponents();

        initComponents();

        conn = dbconnect.connect();//connect to Db when page is open
        
        showdate();                                         //calling date method
        showtime();
        
       
        
        
        
        
    }

    
    public resturantmainpage_(int a) {
        initComponents();

        conn = DBconnectionNew.connect();//connect to Db when page is open

        this.getContentPane().setBackground(Color.white);
        this.tabno = a;

    }

    public String currentday() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int yr = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        return (yr + "-" + (month + 1) + "-" + day);

    }

    public void tableload()//mrthod for gat data nto table
    {
        try {

            String sql = "SELECT Item_code,Name FROM menu ";  //get values from table addstudnt

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();  //to eexecute Query and result save in rs 

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }
    
     public void tableload1()//mrthod for gat data nto table
    {
        try {

            String sql = "SELECT ItemName,ItemCode,qty FROM kot_orders " ;

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();  //to eexecute Query and result save in rs 

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }
    
    
      void showdate()                                         //date method
    {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        date1.setText(s.format(d));
    }
    
    void showtime()                                         //time method
    {
        new Timer(0,new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent ae) {
              Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");   
                
               
           time.setText(s.format(d));
            
            
            }
   
        }
        

        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        itemcodesearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtxt = new javax.swing.JTextArea();
        time = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        balance = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        payment = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemcode_ = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 30)); // NOI18N
        jLabel5.setText("Payment handling");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 390, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel8.setText("Bill");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 70, 80, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Item code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 110, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 550, 290));
        getContentPane().add(itemcodesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 140, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 110, 40));

        billtxt.setColumns(20);
        billtxt.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        billtxt.setRows(5);
        billtxt.setText("--------------Ravindra Resturant-----------\n-------------------Kosgama-----------------\n-----------------011-2519586---------------\n*******************************************\n");
        jScrollPane2.setViewportView(billtxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 130, 400, 490));

        time.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 160, 30));

        date1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setText("Balance");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 66, 19));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Save & Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 130, 40));
        jPanel1.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 190, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Balance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 130, 40));

        payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentKeyPressed(evt);
            }
        });
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 170, 40));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 66, 19));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel11.setText("Total");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 66, 19));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Calculate ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityKeyPressed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 108, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel4.setText("Item code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel1.add(itemcode_, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 108, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 470, 610));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBox1InputMethodTextChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 80, 40));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel2.setText("Table No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 100, 27));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/body.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 890));

        jButton5.setText("Calculate ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         // assign form textfeild inputs to these String variables,,  green text is form feild variable names
        String itemcodefeild = itemcode_.getText();
        String itemnamefeild = name.getText();
        String qtyfeild=quantity.getText();
        String totalfeild = total.getText();
        String paymentfeild=payment.getText(); // after assign input to this variable ,,it converts into string value
        String balancefeild = balance.getText();
        String sum = billtxt.getText();
         String abc=currentday();

        if((qtyfeild.compareTo("")!=0)&&(itemcodefeild.compareTo("")!=0)&&(totalfeild.compareTo("")!=0)&&(paymentfeild.compareTo("")!=0)&&(balancefeild.compareTo("")!=0))
        {

           //if((paymentfeild.matches("[0-400]+"))  )
            //{
                try{

                    String DB = "INSERT INTO bill_info (date,total,payment,itemname,itemcode,qty) values('" +abc+ "'  , '" +totalfeild+ "' , '" +paymentfeild+ "' , '" +sum+ "' , '" +itemcodefeild+ "' , '" +qtyfeild+ "' )";//concat method//in java  to input values to a db
                    pst=conn.prepareStatement(DB);
                    pst.execute();
                    //load table after every insert
                    tableload();//load table
                        
              billtxt.setText("");
              
           
       
           String sql = "DELETE FROM kot_orders where TableNo='"+TabN+"'";

            try {
                pst=conn.prepareStatement(sql);
                pst.execute();
               //tableload1();

            } catch (Exception ex) {

            }
                 
                  
                }
                catch(Exception x )
                {
                    JOptionPane.showMessageDialog(null, x);
                }
            //}

            //else{
               // JOptionPane.showMessageDialog(null, "Enter a number");
            //}
            }
            else{
                JOptionPane.showMessageDialog(null, "Fill the form");
            }
                      itemcode_.setText(" ");
                    name.setText("");
                    quantity.setText(" ");
                    total.setText("");
                    payment.setText(" ");
                   balance.setText("");
       tableload();//load table
        
  
       
       
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // calculate button
        int y = 0;     //check for valid item code
        String sql = " SELECT * FROM menu where Item_code=? ";

       double price=0;
       
            double quantity_=0;
            try {
                pst = conn.prepareStatement(sql);

                pst.setString(1, itemcode_.getText());

                rs = pst.executeQuery();

                if (rs.next()) {

                    String itemcode__ = itemcode_.getText();//
                    // String quantity_ =quantity.getText();//
                    price = Double.parseDouble(rs.getString("Price"));
                    quantity_ = Double.parseDouble(quantity.getText());

                    try {

                        String sqsl = "SELECT Price  FROM menu  where Item_code='" + itemcode_ + "'   ";
                        pst = conn.prepareStatement(sqsl);

                        rs = pst.executeQuery();
                        pst.execute();

                        amount = amount + (price * quantity_);

                        total.setText(Double.toString(amount));
                        
                         double total=0;

                        //load table after every insert
                        // tableload();//load table
                         
                       // for(int i=0;i<5;i++)
                       //  {
                        //     names[i]=name.getText();
                             
                     
                        // }
                    } catch (Exception x) {

                        //JOptionPane.showMessageDialog(null, "Error: This ID has been used earlier");
                        y++;
                    }
                    if (y == 0) {
                        // JOptionPane.showMessageDialog(null,"Submited") ;
                        // call page
                      
                    }
               } else {
                   // JOptionPane.showMessageDialog(null, "Invalid Item code");
               }

            } catch (Exception x) {
                    System.out.println(x);
            }

            //printing the bill
            
               // assign form textfeild inputs to these String variables,,  green text is form feild variable names
        String itemcodefeild = itemcode_.getText();
        String itemnamefeild = name.getText();
        String qtyfeild=quantity.getText();
        String totalfeild = total.getText();
        String paymentfeild=payment.getText(); // after assign input to this variable ,,it converts into string value
        String balancefeild = balance.getText();
        
        
        // billtxt.append("\t\tRavindra Hotel \n\n " + "\t\tKosgama \n\n"  
       // );
                    
         billtxt.append(" " + itemnamefeild + " " + qtyfeild + " " + (price * quantity_) + "\n " 
        );
        
             
     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // balance create

        double payment_ = Double.parseDouble(payment.getText());
        double sum_ = Double.parseDouble(total.getText());
        double balance_ = payment_ - sum_;

        balance.setText(Double.toString(balance_));

          String totalfeild = total.getText();
        String paymentfeild=payment.getText(); // after assign input to this variable ,,it converts into string value
        String balancefeild = balance.getText();
        
        
  billtxt.append("\nTotal " + " " + totalfeild +"\nPayment"+ " " + paymentfeild + "\nBalance" +" " + balancefeild + "\n "  + "\n--------Thank you for visit--------\n"+ "---------Please come again---------\n"
        );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        
        
           String IDD =itemcodesearch.getText();
        
        String sql = "SELECT Name,Item_Code FROM menu  where Item_Code LIKE '%"+ IDD +"%'   "    ;
        
        
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
               jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
               //  tableload();//load table
            
            
        } catch (Exception ex) {
          
        }  
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
          int r = jTable1.getSelectedRow();
          TabN=jTable1.getValueAt(r, 0) .toString();
        String name_ = jTable1.getValueAt(r, 1) .toString();   // r is selected row ,0 is 0 th col
        String itemcode__ = jTable1.getValueAt(r, 2) .toString();
      String qty = jTable1.getValueAt(r, 3) .toString();      //assign select table row and col
      //  String price_ = jTable1.getValueAt(r, 3) .toString();

        name.setText(name_);
        itemcode_.setText(itemcode__);
        quantity.setText(qty);
      //  price.setText(price_);       // set values for each and every text feilds
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
      
        
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP   )
        {
             int r = jTable1.getSelectedRow();

        //String name_ = jTable1.getValueAt(r, 0) .toString();   // r is selected row ,0 is 0 th col
        String itemcode__ = jTable1.getValueAt(r, 1) .toString();
      //  String discription_ = jTable1.getValueAt(r, 2) .toString();      //assign select table row and col
      //  String price_ = jTable1.getValueAt(r, 3) .toString();

      //  name.setText(name_);
        itemcode_.setText(itemcode__);
      //  discription.setText(discription_);
      //  price.setText(price_);       // set values for each and every text feilds
        
        }



    }//GEN-LAST:event_jTable1KeyPressed

    private void quantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD0) ||key==KeyEvent.VK_BACK_SPACE)
            
        {
            quantity.setEditable(true);
            quantity.setBackground(Color.white);
        }
        else
        {
            getToolkit().beep();
            quantity.setEditable(false);
            quantity.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_quantityKeyPressed

    private void paymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentKeyPressed
        
           int key=evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD0) ||key==KeyEvent.VK_BACK_SPACE)
            
        {
            payment.setEditable(true);
            payment.setBackground(Color.white);
        }
        else
        {
            getToolkit().beep();
            payment.setEditable(false);
            payment.setBackground(Color.red);
        }
    }//GEN-LAST:event_paymentKeyPressed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
  
 //dropbox
       /* String dropbox=jComboBox1.getSelectedItem().toString();
        String sql = "SELECT TableNo,ItemName,ItemCode,qty FROM kot_orders  where TableNo='"+ dropbox +"'"    ;
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
               //  tableload();//load table
            //tableload1();
            
        } catch (Exception ex) {
          
        } 
        */
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBox1InputMethodTextChanged
        String dropbox=jComboBox1.getSelectedItem().toString();
        String sql = "SELECT TableNo,ItemName,ItemCode,qty FROM kot_orders  where TableNo='"+ dropbox +"'"    ;
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
               //  tableload();//load table
            //tableload1();
            
        } catch (Exception ex) {
          
        }
    }//GEN-LAST:event_jComboBox1InputMethodTextChanged

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
       //dropbox
/*        String dropbox=jComboBox1.getSelectedItem().toString();
        String sql = "SELECT TableNo,ItemName,ItemCode,qty FROM kot_orders  where TableNo='"+ dropbox +"'"    ;
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
               //  tableload();//load table
            //tableload1();
            
        } catch (Exception ex) {
          
        } */
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased
        // TODO add your handling code here:
        
         String dropbox=jComboBox1.getSelectedItem().toString();
        String sql = "SELECT TableNo,ItemName,ItemCode,qty FROM kot_orders  where TableNo='"+ dropbox +"'"    ;
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
               //  tableload();//load table
            //tableload1();
            
        } catch (Exception ex) {
          
        } 
        
    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String dropbox=jComboBox1.getSelectedItem().toString();
        String sql = "SELECT TableNo,ItemName,ItemCode,qty FROM kot_orders  where TableNo='"+ dropbox +"'"    ;
        try {
            pst=conn.prepareStatement(sql);
            
            rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
               //  tableload();//load table
            //tableload1();
            
        } catch (Exception ex) {
          
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JTextArea billtxt;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField itemcode_;
    private javax.swing.JTextField itemcodesearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField payment;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel time;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
