package Resturant;

import dbconnect.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sulakshana
 */
public class updatemenu_ extends javax.swing.JInternalFrame {

  Connection conn = null;
  PreparedStatement pst = null;
  
  ResultSet rs = null;   //get data base data and save all data in re variable
    
  public updatemenu_() {
        initComponents();
        
        
        
           conn = dbconnect.connect();//connect to Db when page is open
           
       this.getContentPane().setBackground(Color.white);    
           
           
          tableload();//load table 
    }
    
        public void tableload()//mrthod for gat data nto table
    {
        try {
               String sql = "SELECT Name,Item_code,Discription,Price FROM menu ";  //get values from table addstudnt
        pst=conn.prepareStatement(sql); 
        
      rs=  pst.executeQuery();  //to eexecute Query and result save in rs 
      
      jTable1.setModel(DbUtils.resultSetToTableModel(rs));
      
      
      
      
        } catch (Exception e) {
        }
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        name = new javax.swing.JTextField();
        itemcode = new javax.swing.JTextField();
        discription = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 108, 516, 263));
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 130, 175, -1));
        jPanel3.add(itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 174, 175, -1));
        jPanel3.add(discription, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 215, 175, -1));
        jPanel3.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 263, 175, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 317, -1, -1));

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 317, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 125, 79, 27));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Item code");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 170, 79, 25));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Discription");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 213, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Price");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 261, -1, -1));

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel5.setText("Update Menu");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 22, 190, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 380, 260));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r = jTable1.getSelectedRow();

        String name_ = jTable1.getValueAt(r, 0) .toString();   // r is selected row ,0 is 0 th col
        String itemcode_ = jTable1.getValueAt(r, 1) .toString();
        String discription_ = jTable1.getValueAt(r, 2) .toString();      //assign select table row and col
        String price_ = jTable1.getValueAt(r, 3) .toString();

        name.setText(name_);
        itemcode.setText(itemcode_);
        discription.setText(discription_);
        price.setText(price_);       // set values for each and every text feilds

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //clear button

        name.setText("");
        itemcode.setText("");
        discription.setText("");
        price.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        int x=  JOptionPane.showConfirmDialog(null,"Do you really want to Update? ");  // if you select
        // yes-->>>it will get that as 0
        // if you select
        // No-->>>it will get that as 1
        // if you select
        // cancel-->>>it will get that as 2

        if(x==0)
        {
            String  namee = name.getText();
            String itemcode_ = itemcode.getText();
            String  discription_ = discription.getText();
            String  price_ = price.getText();

            if((itemcode_.startsWith("E")))
            {

            }
            else{
                JOptionPane.showMessageDialog(null, "Enter a item code start with E");
            }
            if((price_.matches("[0-9]+")))
            {

                String sql = "UPDATE menu SET Name = '"+namee+"', Item_code= '"+itemcode_+"',  Discription= '"+discription_+"' ,Price= '"+price_+"' WHERE  Item_code ='"+itemcode_+"'   "; // concat
                try {
                    pst=conn.prepareStatement(sql);
                    pst.execute();

                    tableload();//load table
                } catch (Exception ex) {

                }

            }

            else{
                JOptionPane.showMessageDialog(null, "Enter a number");
            }

        }

    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField discription;
    private javax.swing.JTextField itemcode;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
